<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ModalVistaPrevia_Cerrar</name>
   <tag></tag>
   <elementGuidId>64553ce9-80b3-4e6c-bdd8-c86055c67d06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='javascript:VentanaModal.Ocultar();']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.cerrar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cf8e9720-58c2-4e97-b559-06a1f541589f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cerrar</value>
      <webElementGuid>7468cd1b-0981-4b46-bb55-0b06194a1cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cerrar</value>
      <webElementGuid>bcbd14eb-a8ce-4d05-adef-90806f3db07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:VentanaModal.Ocultar();</value>
      <webElementGuid>a9ab0586-d246-40c1-b658-3c3ef0695f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divVentanaModal&quot;)/div[@class=&quot;ventanaModalEnvoltura cajaMover ui-draggable&quot;]/div[@class=&quot;ventanaModalTitulo d-flex justify-content-between&quot;]/div[@class=&quot;ventanaModalTituloHerramientas d-flex align-content-center justify-content-center order-1&quot;]/a[@class=&quot;cerrar&quot;]</value>
      <webElementGuid>00b76d02-5e86-41c3-b595-109ea2c34ea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='javascript:VentanaModal.Ocultar();']</value>
      <webElementGuid>981a0f5b-3706-43c2-872a-c9e6f000a125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divVentanaModal']/div/div[2]/div/a[2]</value>
      <webElementGuid>db74385e-4540-46ee-a5e2-35944d01cc33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciel Ingeniería'])[1]/following::a[2]</value>
      <webElementGuid>db7095e6-2251-4854-a8df-3e3b0faf54c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='es un'])[1]/following::a[3]</value>
      <webElementGuid>48eed723-0a6e-4912-a0b3-1d812b2b7f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Información Importante ...'])[1]/preceding::a[1]</value>
      <webElementGuid>940d6b4f-0a24-488b-a320-d5cdfe903186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[1]</value>
      <webElementGuid>c3fa9c00-47ab-48f0-98ee-02e4024b56cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/a[2]</value>
      <webElementGuid>eb64a25b-7941-455f-8ae9-e3b7b4d79289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Cerrar']</value>
      <webElementGuid>9d9a9a63-af51-4d88-9b48-de50897f1190</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
