<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_VistaPreviaUsuario</name>
   <tag></tag>
   <elementGuidId>c829fd62-529e-45e6-8a6b-2ce886295239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_btnVistaPreviaUsuario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_btnVistaPreviaUsuario</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34fb410b-56da-47d6-b49c-a017bdb2543c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>39079acc-3fa9-46da-8363-447a80db5061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$btnVistaPreviaUsuario</value>
      <webElementGuid>8332ddeb-25fe-4536-a7af-0b4790dc8e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Vista previa</value>
      <webElementGuid>074cb130-f5d6-48f3-85de-171fd8f49446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_btnVistaPreviaUsuario</value>
      <webElementGuid>e28c966a-3a37-43da-9391-bab518e5f7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnVistaPrevia</value>
      <webElementGuid>3ede0804-8652-4249-ac0b-249e624694ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_btnVistaPreviaUsuario&quot;)</value>
      <webElementGuid>137f9af7-5f9f-455b-bc9c-097af164a06d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_btnVistaPreviaUsuario']</value>
      <webElementGuid>a47005c2-8640-4f35-834e-0439c1b6dcde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_UpdatePanel1']/div/div/div/div/div[2]/div[4]/input</value>
      <webElementGuid>3c5fd8a1-9c53-4977-97ef-586f90b34dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>aaae0174-d448-4142-92a4-6f50c091b054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder2$btnVistaPreviaUsuario' and @id = 'ctl00_ContentPlaceHolder2_btnVistaPreviaUsuario']</value>
      <webElementGuid>39cda307-952f-4e20-98b0-f312d4ffcbdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
