<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Habilitado</name>
   <tag></tag>
   <elementGuidId>5568e57f-aa8b-44b3-9e57-e5847377fbcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_UpdatePanel1']/div/div/div/div/div[2]/div/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1750aa5f-e8d3-4e24-b4c5-d16fa877aa81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_chkMsjUsuario</value>
      <webElementGuid>243ffeb8-6707-4bcb-83d9-b2ec5c412cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Habilitado: </value>
      <webElementGuid>27997df7-b113-4f5e-9cab-9416c3017577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_UpdatePanel1&quot;)/div[@class=&quot;divCentral container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;divVenModalCliente col-sm-12 col-md-5 col-lg-4 col-xxl-4 mb-3&quot;]/div[@class=&quot;caja&quot;]/div[@class=&quot;cajaContenido&quot;]/div[@class=&quot;divCheckBox&quot;]/span[1]/label[1]</value>
      <webElementGuid>14e4a762-c0d6-49ca-926d-c15602ec0890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_UpdatePanel1']/div/div/div/div/div[2]/div/span/label</value>
      <webElementGuid>53f8a697-3144-46e1-98b7-aadc602a05a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ventana Modal Clientes'])[1]/following::label[1]</value>
      <webElementGuid>cde7a0d9-ac40-43c8-b81d-3547bfcdb42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensajes de inicio'])[2]/following::label[1]</value>
      <webElementGuid>9716822d-5e07-47d2-80f1-d27613415a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje Principal'])[1]/preceding::label[1]</value>
      <webElementGuid>c31c078b-e01f-49f9-bcf3-c02eba5e7540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje Adicional'])[1]/preceding::label[1]</value>
      <webElementGuid>12df1a98-b50c-4d91-b414-184ceda1cddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Habilitado:']/parent::*</value>
      <webElementGuid>88730db3-b35c-4d38-a4dc-c19c7ca6506e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>db75ff8a-39cc-4ae9-93be-e6cec2b40a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Habilitado: ' or . = 'Habilitado: ')]</value>
      <webElementGuid>d9761ca1-1253-45b1-87da-80aa576cc266</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
