<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Seleccionar Todo</name>
   <tag></tag>
   <elementGuidId>5897190a-6fab-4d17-a4ff-8561d6535502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_grvPlantillas']/tbody/tr/th[11]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5b2a59c7-b403-4615-b319-57ed5c6f5e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grvPlantillas_ctl01_chkSelTodo</value>
      <webElementGuid>a3fb0f3f-68be-46f7-b256-cd5b67afd331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvPlantillas&quot;)/tbody[1]/tr[1]/th[11]/label[1]</value>
      <webElementGuid>f60d2aff-daff-49d3-be0f-d5671c899f7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvPlantillas']/tbody/tr/th[11]/label</value>
      <webElementGuid>7c13ec62-402e-4398-ae97-5bbdf9f46aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>52338ec6-c600-4b03-8c45-77bbfcb76733</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
