<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Nombre</name>
   <tag></tag>
   <elementGuidId>98aaa6ed-5149-4a5a-a216-ab76ae0f2037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tbody > tr > th:nth-of-type(8)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvRecepcionCitas']/tbody/tr/th[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>124489df-b0c4-4043-9078-84b2f63ddf46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>5c2eb70c-6ca7-420b-ab9e-3d2ba36a6bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nombre</value>
      <webElementGuid>ec73b9e7-7030-445d-be13-97aa62d8029c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvRecepcionCitas&quot;)/tbody[1]/tr[1]/th[8]</value>
      <webElementGuid>ef7fd052-d151-4d7b-8039-ccdb78bfdf3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvRecepcionCitas']/tbody/tr/th[8]</value>
      <webElementGuid>51885958-4034-46f7-95af-8ec79845ac4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N° Identificación'])[1]/following::th[1]</value>
      <webElementGuid>013a4572-bc13-4f62-8642-1aaab213ecdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Identificación'])[1]/following::th[2]</value>
      <webElementGuid>30324bac-8be2-4703-9e15-3ee932d172f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turno atención'])[1]/preceding::th[1]</value>
      <webElementGuid>378481ba-51f1-48e7-ac2b-dbe9728f58b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado de la Cita'])[1]/preceding::th[2]</value>
      <webElementGuid>471059c2-5a93-43c4-9eda-d9ec7b94849e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nombre']/parent::*</value>
      <webElementGuid>c9b74fa4-7702-4c67-aa7a-28fd27864e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th[8]</value>
      <webElementGuid>9aa600d8-33e4-4c84-b5e2-d47a036dba6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Nombre' or . = 'Nombre')]</value>
      <webElementGuid>931dcf7e-7866-4d27-90e6-f29f3cae0f5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
