<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NoRelacionar5</name>
   <tag></tag>
   <elementGuidId>4030b727-f7ed-4b3c-abbf-7b4ab3e221bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnUncheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnUncheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac2b0790-3695-4cb4-acd8-c616f13f68eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>3a065eb6-ca65-4d9e-a223-91a059f3bfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvEspecialidades$ctl06$btnUncheck</value>
      <webElementGuid>b2c00310-c094-4dd0-ab49-508b8abd8aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnUncheck</value>
      <webElementGuid>d6199689-b2bb-46cb-b6a1-ea53b645c171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Desmarcar servicio</value>
      <webElementGuid>53a88341-fb81-4d27-a968-7b1765ee0058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Imagenes/Cancel.svg</value>
      <webElementGuid>c0f18ee9-db2d-42dd-9b00-c89431dfdd75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnUncheck&quot;)</value>
      <webElementGuid>299dabf0-12b0-4b19-b200-6279ef4bb6d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnUncheck']</value>
      <webElementGuid>7750e07b-607a-4227-96cb-467abfc97a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvEspecialidades']/tbody/tr[6]/td[5]/input</value>
      <webElementGuid>739cf022-300d-488b-81fc-dd4a240ebdc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[5]/input</value>
      <webElementGuid>5a43d206-9958-4e6c-b01d-ec6239de4aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$gvEspecialidades$ctl06$btnUncheck' and @id = 'ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnUncheck' and @title = 'Desmarcar servicio' and @src = '../../../Imagenes/Cancel.svg']</value>
      <webElementGuid>add867f0-4e43-4d68-9f3c-e1163e4edcac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
