<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NoRelacionar6</name>
   <tag></tag>
   <elementGuidId>cb361a69-e9b9-4c2d-8067-910b8cd3a297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnUncheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnUncheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90e9fb18-d14a-495c-9f24-f9ff47abbcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>5e9e69c1-4765-4dd3-b2a6-4d1ed3cabdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvEspecialidades$ctl07$btnUncheck</value>
      <webElementGuid>311d0097-7d01-40ed-9a6e-af4823e6a3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnUncheck</value>
      <webElementGuid>a9a06d84-e144-44e5-8a98-14e8ce1b81d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Desmarcar servicio</value>
      <webElementGuid>3546a9b2-f643-424b-95ec-e5faa5fddaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Imagenes/Cancel.svg</value>
      <webElementGuid>02897f6d-c3d7-49c3-b05e-bbab451355e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnUncheck&quot;)</value>
      <webElementGuid>3515f8c0-98c2-401c-9cab-ed0f95a9c772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnUncheck']</value>
      <webElementGuid>2f4c3334-a785-4ee7-adbb-47bfcd63dcf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvEspecialidades']/tbody/tr[7]/td[5]/input</value>
      <webElementGuid>318ccd6c-8859-4ffd-aeed-f75a0aea035a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[5]/input</value>
      <webElementGuid>8784af27-8ca3-4652-9dcd-100a84a98a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$gvEspecialidades$ctl07$btnUncheck' and @id = 'ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnUncheck' and @title = 'Desmarcar servicio' and @src = '../../../Imagenes/Cancel.svg']</value>
      <webElementGuid>7d4d4771-2685-4790-b330-3e8104d332e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
