<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>relacionar1</name>
   <tag></tag>
   <elementGuidId>f3ff629e-ff49-4918-86be-2e8a72a740f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnCheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnCheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b8f9823-b1f8-4700-a447-33df128c32f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>00add313-41e0-4c1a-a8f0-d28d4d2c807b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvEspecialidades$ctl02$btnCheck</value>
      <webElementGuid>63512b41-8f3a-43fd-aff5-ea94f7cb0708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnCheck</value>
      <webElementGuid>3dfbe7fe-5f0f-4b63-abc8-6d55cbfe4f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marcar servicio</value>
      <webElementGuid>64f3c7b0-62bb-4a5f-a06b-8f9a419a9570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Imagenes/Update.svg</value>
      <webElementGuid>074a0148-34a0-45bf-9998-491c6c880721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnCheck&quot;)</value>
      <webElementGuid>09e7aeda-4342-4731-943d-0a1a9d7747da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnCheck']</value>
      <webElementGuid>c861bcf3-23fc-4d97-a3f0-1f9e5bf7205d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvEspecialidades']/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>877e97bd-225d-41d9-8645-946cc9e0f639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>9fb39dd8-1753-4f79-9d2e-791e383cd94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$gvEspecialidades$ctl02$btnCheck' and @id = 'ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnCheck' and @title = 'Marcar servicio' and @src = '../../../Imagenes/Update.svg']</value>
      <webElementGuid>d4583cb1-dec3-4d28-97dc-5166944240f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
