<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Relacionar6</name>
   <tag></tag>
   <elementGuidId>c5afd49f-f348-4071-9ecb-6d75f1a306c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnCheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnCheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66dded00-5f65-4884-8412-77aeb2dbc2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>27affdff-e9ec-4c9e-be81-9eb77abd63bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvEspecialidades$ctl07$btnCheck</value>
      <webElementGuid>ce2ff5c7-271f-4840-ae20-c3530f0ecf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnCheck</value>
      <webElementGuid>8d78982a-294c-4e22-a810-eb624557e4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marcar servicio</value>
      <webElementGuid>266896b0-7281-4940-aa36-fa43891b3d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Imagenes/Update.svg</value>
      <webElementGuid>0c6c9879-835f-495b-b8ec-e8fe97449250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnCheck&quot;)</value>
      <webElementGuid>269f653b-a631-4bfc-bec0-a707fdb115a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnCheck']</value>
      <webElementGuid>fe0cfb89-d30d-4120-b22b-3d853434cd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvEspecialidades']/tbody/tr[7]/td[4]/input</value>
      <webElementGuid>fac72151-1d42-4740-8cce-5b9732afc5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[4]/input</value>
      <webElementGuid>65b2ac97-f5b5-4305-9ee1-1f2ce83c7ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$gvEspecialidades$ctl07$btnCheck' and @id = 'ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnCheck' and @title = 'Marcar servicio' and @src = '../../../Imagenes/Update.svg']</value>
      <webElementGuid>3e3d5af2-3bae-4fc5-bb11-913d5388324b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
