<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Relacionar5</name>
   <tag></tag>
   <elementGuidId>03f19e2e-3f53-4789-8917-dbdf44092741</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnCheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnCheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b960b24-452d-45df-adc5-79093ca485b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>dac4e361-b089-478c-b409-b42abbe695c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvEspecialidades$ctl06$btnCheck</value>
      <webElementGuid>af69a56f-a3d1-4f47-9591-59dea2cb0902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnCheck</value>
      <webElementGuid>eb4dc9d3-df0b-4746-899a-604f6dab9ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marcar servicio</value>
      <webElementGuid>9f05920a-f29c-47b6-b205-27f60a54f25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Imagenes/Update.svg</value>
      <webElementGuid>f1a8f167-177b-41f5-aab4-905aef9f5436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnCheck&quot;)</value>
      <webElementGuid>d9a5ce2d-9faa-4962-ad7f-d9b132e7634d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnCheck']</value>
      <webElementGuid>dee60b63-f192-4fd7-9771-8eff8deeee47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvEspecialidades']/tbody/tr[6]/td[4]/input</value>
      <webElementGuid>3b20dcfb-fae1-469c-be9a-44c784d7b185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[4]/input</value>
      <webElementGuid>a43dc484-bbde-4c74-bc4b-22a2fa0bac7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$gvEspecialidades$ctl06$btnCheck' and @id = 'ctl00_ContentPlaceHolder2_gvEspecialidades_ctl06_btnCheck' and @title = 'Marcar servicio' and @src = '../../../Imagenes/Update.svg']</value>
      <webElementGuid>df0f98ae-dafb-4df0-a3ae-c3fe5f6a8d3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
