<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>28468443-1fd0-46ec-ab44-448285e38355</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvPoliticasDatos']/tbody/tr[2]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.trClick > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4a1e7ac3-ddf7-4903-b6b1-aa4a3ee680e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>826314ff-05b8-48f3-8228-81ac561502ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>7c1b1a95-0478-4f52-859c-d318b21092fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>91723976-7af6-4dca-8f1a-d06a8c2ce870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvPoliticasDatos&quot;)/tbody[1]/tr[@class=&quot;trClick&quot;]/td[1]</value>
      <webElementGuid>94fe41e8-e626-4dc4-aa0b-54421eb55f10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvPoliticasDatos']/tbody/tr[2]/td</value>
      <webElementGuid>3975809f-62e7-42fc-b7fe-c3606e745bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Política por defecto'])[1]/following::td[1]</value>
      <webElementGuid>af776123-6261-4536-ae10-a5f80b41fdb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo archivo'])[1]/following::td[1]</value>
      <webElementGuid>a8467360-3d6e-4d03-b536-38a55010b6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TXT'])[1]/preceding::td[1]</value>
      <webElementGuid>985b0cf3-d3fd-4b20-ae04-4130affd6e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Texto'])[1]/preceding::td[2]</value>
      <webElementGuid>82855339-71f0-4464-af1a-dc06f96fae27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>2380a9f5-4f38-4c16-8512-298be1fe7faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/table/tbody/tr[2]/td</value>
      <webElementGuid>78df7e37-ffa5-44b1-8bee-089fdb8be36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '1' or . = '1')]</value>
      <webElementGuid>55d66d4c-99c1-4f31-80aa-ce970e567e74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
