<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td3_6 - rea General - General (G) - Radicaciones</name>
   <tag></tag>
   <elementGuidId>830ed3a0-c9b2-4c29-bd8f-fac497a0d6d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00__2']/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1baa20a3-221b-4ecc-b940-6412d886c832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>56e37211-88e9-4e92-8b99-a5c68f62ae72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>f7c5942d-8ed8-4d15-bf12-c46acc25b104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6 - Área General - General (G) - Radicaciones</value>
      <webElementGuid>2cb6560b-8304-419b-99f1-8e4e03ae707d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_RadGrid1_ctl00__2&quot;)/td[2]</value>
      <webElementGuid>74fa74e4-ceff-4309-9bb0-b9a22dd4c2e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00__2']/td[2]</value>
      <webElementGuid>ba7081b7-84ac-4ecb-a339-0cb06f818ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Presencial'])[3]/following::td[4]</value>
      <webElementGuid>85c0ee69-8812-4b9f-9057-24e27bab1983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Presencial'])[2]/following::td[12]</value>
      <webElementGuid>a70a07b1-4a68-43dd-841a-b2bdeb174645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Presencial'])[4]/preceding::td[4]</value>
      <webElementGuid>9070f55e-b15d-4270-be41-b1f58eda4b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Presencial'])[5]/preceding::td[12]</value>
      <webElementGuid>51e8fe5f-24da-4229-83f1-f214cf40f8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6 - Área General - General (G) - Radicaciones']/parent::*</value>
      <webElementGuid>eb6f43cb-4975-4714-9b6c-f14bed0db113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>eb58e681-a1e5-4899-be86-65fe160ddeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '6 - Área General - General (G) - Radicaciones' or . = '6 - Área General - General (G) - Radicaciones')]</value>
      <webElementGuid>f95c6ae4-f046-4b8a-932b-fcbafe32be81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
