<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DOWN MM Inicio</name>
   <tag></tag>
   <elementGuidId>8fc97f02-d066-4a42-8537-b14f46dd5fd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cea377a8-c8c8-45a8-aa3a-b6a05329ea97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b49e9bec-b938-41a7-89b6-49df7f7027f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown</value>
      <webElementGuid>f6ae4a54-62cd-43be-b5a0-f56789de87ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>18cc4d56-d860-4767-9e2f-ce1285996eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown&quot;)</value>
      <webElementGuid>622c585f-0e29-4a5e-85dc-79abe81f7266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown']</value>
      <webElementGuid>7594f3d9-b59d-4385-b572-b263e7091839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divEdicionJornada']/div/div[2]/div/table/tbody/tr[3]/td[2]/div/div[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>4a598b7a-c8db-4992-a7ff-00186088ac43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>96ea851b-318c-44a3-bdda-1ad11cfa19df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown']</value>
      <webElementGuid>ebd4683a-ddfe-4d97-bace-6780c70c14d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
