<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MM Fin</name>
   <tag></tag>
   <elementGuidId>18a8def8-4a56-4765-b701-9096e49baddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraFin_txtMinuto']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_tspHoraFin_txtMinuto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39cd761b-79e6-4ea1-839d-1df35f6563f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$tspHoraFin$txtMinuto</value>
      <webElementGuid>905e244e-b20a-4290-97e6-86337b99f588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e81a7a9-768a-48ce-a7f5-3776dc5dcf78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00</value>
      <webElementGuid>d24bdb67-bf6b-464d-b17f-fed742c17e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3f072020-d500-400c-b363-e2c2a7baad90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_tspHoraFin_txtMinuto</value>
      <webElementGuid>b17d60ea-ab5b-4c00-be2b-a7610e6bea58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c5ad98c7-8ca0-4f9c-b29f-b5ba9bbf8021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_tspHoraFin_txtMinuto&quot;)</value>
      <webElementGuid>d4a34c45-1dbe-45f3-b1ad-9115d1b5adfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraFin_txtMinuto']</value>
      <webElementGuid>4b39d18d-949e-4995-a81d-9bbce88cae63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divEdicionJornada']/div/div[2]/div/table/tbody/tr[4]/td[2]/div/div[2]/div/table/tbody/tr/td/input</value>
      <webElementGuid>57d5fc01-74c8-4ec6-9ab8-2eb6a1034e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div[2]/div/table/tbody/tr/td/input</value>
      <webElementGuid>af38b49f-1c7d-47bd-aa3b-e1abcf89079e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$tspHoraFin$txtMinuto' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_tspHoraFin_txtMinuto']</value>
      <webElementGuid>9f8e5dc3-b07c-43ac-b9d0-6899ee46818e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
