<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HH_Inicio</name>
   <tag></tag>
   <elementGuidId>6fcbc315-b198-46c4-a313-9a8b7a18fb52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bcc6681-3d8f-4998-9130-01902db59ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$tspHoraInicio$txtHora</value>
      <webElementGuid>8d9cf649-39a5-4657-8bb2-feb7bf5ae156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c810cc7a-f89a-4868-bf1f-049edcb11468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00</value>
      <webElementGuid>b2946f11-6af8-4341-9c89-e6ba4e7d6a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f39ea399-73d1-413a-abc5-fc257dc71378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora</value>
      <webElementGuid>f719a275-63c7-4568-8dba-35b249ffa089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9c73fdd9-1760-414b-a344-5dc2ff5cf10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora&quot;)</value>
      <webElementGuid>aa7593e4-8112-4bfc-bc2c-b003aa9ad569</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora']</value>
      <webElementGuid>f1bc4b15-11c1-4642-8d3f-4450ef12053d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divEdicionJornada']/div/div[2]/div/table/tbody/tr[3]/td[2]/div/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>7f9aaeab-b2db-4651-a7b2-baff86442804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>ae5f8f55-bad1-4532-b787-40c9b5dc06ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$tspHoraInicio$txtHora' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora']</value>
      <webElementGuid>af2b215f-e1fc-476c-bb6a-8a32b6c28d01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
