<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Regional</name>
   <tag></tag>
   <elementGuidId>af0ce476-0da6-4eb4-b059-ce1d778a8241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_ContentPlaceHolder2_ddlEditRegional']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_ddlEditRegional</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3b6b5472-60dc-46ef-ad4f-1e265cde8199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$ddlEditRegional</value>
      <webElementGuid>39525ad3-a844-4d23-9359-856df56b4998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$ContentPlaceHolder2$ddlEditRegional\',\'\')', 0)</value>
      <webElementGuid>7eaab77b-848e-47e2-b0e4-91cc3067d57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ddlEditRegional</value>
      <webElementGuid>404230e7-2ed9-42f8-95ce-6edd02b63bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Bogota
		Cali
		Cartagena
		Manizales
		Medellin
		Virtual
		WorkFlow

	</value>
      <webElementGuid>60d1b1c0-78ca-4124-bd9c-f43c4ae6bc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_ddlEditRegional&quot;)</value>
      <webElementGuid>785464dc-5950-4ff9-8c6d-35fe8e7af056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_ContentPlaceHolder2_ddlEditRegional']</value>
      <webElementGuid>72b1f20a-c400-408d-b2cc-ae040e337fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_upRegional']/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>ec90e30e-0894-4c76-9458-a9ea7425213a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regional:'])[1]/following::select[1]</value>
      <webElementGuid>e13280f4-a710-4580-a0e5-cc3761f4b760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>c1c66b75-fc6e-4147-8e53-d1f71514ad22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>3a826d56-3d28-4d42-a022-c61410d332d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código Ciudad:'])[1]/preceding::select[1]</value>
      <webElementGuid>9b6afbf0-7ffd-4b12-adcb-60b1a86f8308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/select</value>
      <webElementGuid>77754812-77ac-47cd-ab67-f125bc6f661e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder2$ddlEditRegional' and @id = 'ctl00_ContentPlaceHolder2_ddlEditRegional' and (text() = '
		Bogota
		Cali
		Cartagena
		Manizales
		Medellin
		Virtual
		WorkFlow

	' or . = '
		Bogota
		Cali
		Cartagena
		Manizales
		Medellin
		Virtual
		WorkFlow

	')]</value>
      <webElementGuid>ce2bafb7-2dd4-430b-bc67-aa11862bb63c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
