<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fecha Inicial Mes siguiente</name>
   <tag></tag>
   <elementGuidId>afc52d16-9ffc-4113-88dc-137aaa9857a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN' and @title = '>' and @href = '#' and (text() = '>' or . = '>')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05945fb3-3e59-4a55-87f2-9b295d22b251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN</value>
      <webElementGuid>769aa049-048f-4e94-ad6c-1183736c7851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-button rcNext</value>
      <webElementGuid>9b073cbc-d0c1-406f-8ac6-33553827943a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>></value>
      <webElementGuid>6ccc2862-313c-4207-a9b9-2a1d02cb26ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>226dbc24-d714-4ad1-b9c9-55a36ef8c796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>></value>
      <webElementGuid>57d716f5-d24c-4b0a-9e22-5e02d77ffb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN&quot;)</value>
      <webElementGuid>682b213a-8f1c-46f2-a8b4-14cd79861d95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN']</value>
      <webElementGuid>1b751e62-892c-494d-99f5-e762518aebab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar']/thead/tr/td/table/tbody/tr/td[4]/a</value>
      <webElementGuid>7b551f39-6642-4166-8e36-ff5d61258795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'>')]</value>
      <webElementGuid>ae18c4ce-b7aa-4bc1-8da2-124abfb324f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='julio de 2022'])[1]/following::a[1]</value>
      <webElementGuid>efcd41df-296e-462a-995b-55e32629a4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title and navigation'])[2]/following::a[3]</value>
      <webElementGuid>b312443c-ce43-4507-b41d-d76576b2582b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='julio de 2022'])[2]/preceding::a[2]</value>
      <webElementGuid>56b5d7f2-1f82-4dd4-b453-3688001beabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[1]/preceding::a[2]</value>
      <webElementGuid>dce893aa-9bf4-4598-9b1f-4b8cb19e4e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='>']/parent::*</value>
      <webElementGuid>ecf8caa9-d7af-4dec-841a-3daa2c277fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>143cea23-bde4-46b6-b4ae-73cd72d5dc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>81fcf577-c91f-46f7-9661-076a076cfb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN' and @title = '>' and @href = '#' and (text() = '>' or . = '>')]</value>
      <webElementGuid>830b7cbe-928f-4255-951a-60bc1991eff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
