<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Final</name>
   <tag></tag>
   <elementGuidId>0553f022-aaee-471b-9c4a-ed42f6dbe6c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_rdpFechaFin_dateInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_rdpFechaFin_dateInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4be0eba3-5333-4b82-80bf-eec825f70adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_rdpFechaFin_dateInput</value>
      <webElementGuid>c585ea45-1b12-4201-8c3a-6d616b94e780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$rdpFechaFin$dateInput</value>
      <webElementGuid>868ee978-085a-4477-87b7-5dfbd072425e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>riTextBox riDisabled</value>
      <webElementGuid>0aeb126f-155c-4d04-a72e-5a1eb4ed25dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>a308276c-ecc9-407b-9cbd-e8f6a43e495d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab75d6d8-57a6-4d69-95a7-d6a866d28caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_rdpFechaFin_dateInput&quot;)</value>
      <webElementGuid>4b1be287-1cd8-4185-86a8-f127be4af3e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_rdpFechaFin_dateInput']</value>
      <webElementGuid>3ddf08c6-a499-4412-b0d6-f05952644402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ContentPlaceHolder2_rdpFechaFin_dateInput_wrapper']/input</value>
      <webElementGuid>9cdfa4a1-f62d-4eee-930f-4eacb7e77572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>614ab8e7-de44-4520-acc3-c44f7ddfdd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ContentPlaceHolder2_rdpFechaFin_dateInput' and @name = 'ctl00$ContentPlaceHolder2$rdpFechaFin$dateInput' and @type = 'text']</value>
      <webElementGuid>6b12e666-5d70-4932-b60f-3e01053f2ed6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
