<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Modo Diseno MenPrincipal</name>
   <tag></tag>
   <elementGuidId>27815d17-82a6-4782-ac1e-0d35161c0e4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl03_ctl00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl03_ctl00</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5a3bd233-c2ae-478d-9627-c7508e782793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/WebResource.axd?d=K6hBBt7cIA91H1qzdLBxg10QNh7DXghXL-t9a9srjCReFadxAKoJXRJmdVUvwHpvv_lG5pk30fBg3aIZBse7dEQkaAa1A8hbMpNi2yF6ETNy0zEhETgvyBQYw9xWUepep23mP_0DteY0DLylqmvn4VFcMTA1&amp;t=637866756480000000</value>
      <webElementGuid>57a983bb-e9c2-43fe-8d20-34e1261bb18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl03_ctl00</value>
      <webElementGuid>0836531d-202f-4b0a-b282-a0f0e0b211f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Design mode</value>
      <webElementGuid>23f7ec39-02bd-4e75-9db3-7055af9bcc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_toolbar_button ajax__htmleditor_toolbar_button_active ajax__htmleditor_toolbar_button_hover</value>
      <webElementGuid>8e3e5fc4-e833-4f88-9481-7f724554eece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl03_ctl00&quot;)</value>
      <webElementGuid>685b810f-bef3-4879-a169-d0fba2bb3232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl03_ctl00']</value>
      <webElementGuid>4f6980e4-8671-4f62-b285-d9e5a63eb7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl03']/img</value>
      <webElementGuid>ed86d2f2-7a51-46de-833a-36cafb56eb26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Design mode'])[3]</value>
      <webElementGuid>14edf2ca-9ec7-4cb1-8598-a6777430d96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/table/tbody/tr[3]/td/div/img</value>
      <webElementGuid>fa057ac8-dba8-4905-9b5b-5a624a3c6288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/WebResource.axd?d=K6hBBt7cIA91H1qzdLBxg10QNh7DXghXL-t9a9srjCReFadxAKoJXRJmdVUvwHpvv_lG5pk30fBg3aIZBse7dEQkaAa1A8hbMpNi2yF6ETNy0zEhETgvyBQYw9xWUepep23mP_0DteY0DLylqmvn4VFcMTA1&amp;t=637866756480000000' and @id = 'ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl03_ctl00' and @title = 'Design mode']</value>
      <webElementGuid>2a65aee0-b031-472b-ba48-d5b864499769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
