<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Modo HTML MenPrincipal</name>
   <tag></tag>
   <elementGuidId>6520c6f7-c0e0-4998-b9f3-0fc88bdcc1ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>03831fb2-e3ac-446d-9020-a7bd45066d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01</value>
      <webElementGuid>e5caf252-c518-4d47-adbd-8dc0ab9e7c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_htmlpanel_default</value>
      <webElementGuid>553f4de2-c79e-485a-bd51-4452d9964811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01&quot;)</value>
      <webElementGuid>d1c042e8-4ff8-41ce-a96e-ea5d6d8d62e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01']</value>
      <webElementGuid>9c59792f-e598-4424-9843-0db336d5859c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02']/textarea</value>
      <webElementGuid>6f26bbd3-9f3e-4902-95ac-95493964e181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/table/tbody/tr[2]/td/div/textarea</value>
      <webElementGuid>364575bc-64c0-48b1-b8ef-0875f97706f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01']</value>
      <webElementGuid>c336d3c7-6175-4d11-bf8a-3d115e311267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
