<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Modo Diseno MenPrincipal</name>
   <tag></tag>
   <elementGuidId>f75a7768-a801-407f-94b2-41e896abfc40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c089e519-3b9f-4ab2-a7e5-24af58c61e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01</value>
      <webElementGuid>0c78d726-cf7a-44ce-8ecb-862e2b7a644d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_htmlpanel_default</value>
      <webElementGuid>cd9b8afd-c9c8-46c0-bc73-2bcfcbb2e082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01&quot;)</value>
      <webElementGuid>659667f2-836d-4fad-ab9e-744a5b5be645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01']</value>
      <webElementGuid>4031ea0d-de04-4672-bd67-3bdcec6f4821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02']/textarea</value>
      <webElementGuid>7063b37f-f5a2-4b03-a097-f40f4122f9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/table/tbody/tr[2]/td/div/textarea</value>
      <webElementGuid>faac9e9c-4c87-47b9-a3e3-2e30da946f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ctl00_ContentPlaceHolder2_edtMensajeAdmin_ctl02_ctl01']</value>
      <webElementGuid>fd4ca209-e4ee-4cf7-8394-84798fbae2da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
