<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Regional</name>
   <tag></tag>
   <elementGuidId>2542cd11-3d0e-487e-a1a2-65ea28ae33b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_ContentPlaceHolder2_ddlRegionalBusqueda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_ddlRegionalBusqueda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d65fcc13-3ec0-430f-9ce2-7ca9495cc3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$ddlRegionalBusqueda</value>
      <webElementGuid>51119e3b-f60d-48be-ab1a-08e7bf60e395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ddlRegionalBusqueda</value>
      <webElementGuid>5a910d01-dc38-4396-b3d4-9739a512eaab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		-- Seleccione --
		Bogota
		Cali
		Cartagena
		Manizales
		Medellin
		Virtual
		WorkFlow

	</value>
      <webElementGuid>6f131d96-adbb-49f6-8028-7c47ae544600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_ddlRegionalBusqueda&quot;)</value>
      <webElementGuid>35a36930-9605-436c-a833-977a3b105745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_ContentPlaceHolder2_ddlRegionalBusqueda']</value>
      <webElementGuid>7f8810ad-0c41-42ef-b4b2-3266f5d3d681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divFiltrosCitas']/div[4]/select</value>
      <webElementGuid>91f9777d-36a8-4e69-bdc9-0d029053fd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regional:'])[1]/following::select[1]</value>
      <webElementGuid>52b34ec2-4546-4b61-97e0-665322d179c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departa. / Estado:'])[1]/following::select[2]</value>
      <webElementGuid>f4f4cca1-665e-4d7e-bd77-f0b3c7764365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/preceding::select[1]</value>
      <webElementGuid>63fb5a93-741f-4c9d-96ce-a17b75e3bc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código de Ciudad'])[1]/preceding::select[1]</value>
      <webElementGuid>925a6746-6741-4fe0-a732-8255a2611e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>7a7c2f08-8d18-4900-8b6e-dc43b4588e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder2$ddlRegionalBusqueda' and @id = 'ctl00_ContentPlaceHolder2_ddlRegionalBusqueda' and (text() = '
		-- Seleccione --
		Bogota
		Cali
		Cartagena
		Manizales
		Medellin
		Virtual
		WorkFlow

	' or . = '
		-- Seleccione --
		Bogota
		Cali
		Cartagena
		Manizales
		Medellin
		Virtual
		WorkFlow

	')]</value>
      <webElementGuid>978067ea-c7ab-4dfc-9ba2-dc6c578c32cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
