<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_91 Prueba</name>
   <tag></tag>
   <elementGuidId>f23fd983-da74-46c0-b450-72e4a6bd84f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvCiudades']/tbody/tr[9]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fd432c45-9005-4e88-8aee-d44c09038620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prueba</value>
      <webElementGuid>f9ede444-9a90-4570-b293-0fac1d9264fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvCiudades&quot;)/tbody[1]/tr[@class=&quot;trClick&quot;]/td[2]</value>
      <webElementGuid>8449e08f-ae39-4e62-ad59-8a53f102471f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvCiudades']/tbody/tr[9]/td[2]</value>
      <webElementGuid>94459de0-7262-4de1-9e05-4b0551eccc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bogota'])[3]/following::td[4]</value>
      <webElementGuid>fa6589d3-fafc-4822-9b0d-07de28e5f93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cundinamarca'])[2]/following::td[5]</value>
      <webElementGuid>419af719-24c0-4522-9cc9-7f53061d1549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cundinamarca'])[3]/preceding::td[1]</value>
      <webElementGuid>9d02f7b9-e83a-45e9-be34-1c1d7c7f3fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bogota'])[4]/preceding::td[2]</value>
      <webElementGuid>65025811-2ab7-49ef-9f12-6a0dc46c22e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]</value>
      <webElementGuid>0e382090-7da9-4bc5-b590-a64dac471b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Prueba' or . = 'Prueba')]</value>
      <webElementGuid>b08d2eb1-fc82-4e7c-85a5-93a6eb9d67c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
