<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Modo Diseno MenPrincipal</name>
   <tag></tag>
   <elementGuidId>9c84d72e-189a-4452-8eaa-8394fddc21a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl03_ctl00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl03_ctl00</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1762c0e8-32e0-4c78-aba4-e7fbf357ecd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/WebResource.axd?d=K6hBBt7cIA91H1qzdLBxg10QNh7DXghXL-t9a9srjCReFadxAKoJXRJmdVUvwHpvv_lG5pk30fBg3aIZBse7dEQkaAa1A8hbMpNi2yF6ETNy0zEhETgvyBQYw9xWUepep23mP_0DteY0DLylqmvn4VFcMTA1&amp;t=637866756480000000</value>
      <webElementGuid>7f25dbfe-b50c-4c82-8a6c-4616afe89930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl03_ctl00</value>
      <webElementGuid>c8beec95-b453-442a-a6db-59d86b8d53dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Design mode</value>
      <webElementGuid>dc06a070-c2a9-4fa0-a86c-f3a75d0334b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_toolbar_button ajax__htmleditor_toolbar_button_active ajax__htmleditor_toolbar_button_hover</value>
      <webElementGuid>593d13ae-61ba-4c42-a359-0d0d63f12a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl03_ctl00&quot;)</value>
      <webElementGuid>bf53e7bf-15ae-4953-b3e8-c84a5aed1309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl03_ctl00']</value>
      <webElementGuid>6a22dfe9-92ca-40ac-a92d-40906ab56520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl03']/img</value>
      <webElementGuid>99cf707d-4e46-47e4-a029-5cd757598fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Design mode']</value>
      <webElementGuid>e1416fff-92e9-4b32-9179-2bdaf2ae04a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/img</value>
      <webElementGuid>4a201945-3a53-48b6-879a-0f858fc81f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/WebResource.axd?d=K6hBBt7cIA91H1qzdLBxg10QNh7DXghXL-t9a9srjCReFadxAKoJXRJmdVUvwHpvv_lG5pk30fBg3aIZBse7dEQkaAa1A8hbMpNi2yF6ETNy0zEhETgvyBQYw9xWUepep23mP_0DteY0DLylqmvn4VFcMTA1&amp;t=637866756480000000' and @id = 'ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl03_ctl00' and @title = 'Design mode']</value>
      <webElementGuid>6092602a-b1b2-4cf6-90c2-5afab281c9e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
