<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Modo Diseno Mensaje Principal</name>
   <tag></tag>
   <elementGuidId>21d1d22c-742e-4b41-8ab8-48f7fa9ab361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl02_ctl01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl02_ctl01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d7b6e577-93db-416f-880b-acc2ac397986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl02_ctl01</value>
      <webElementGuid>bbf9d797-4025-4fbe-923a-44f6cd12f830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_htmlpanel_default</value>
      <webElementGuid>e86ea3a0-c1e4-452e-83be-3dc1e8898dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl02_ctl01&quot;)</value>
      <webElementGuid>90f75754-f5b5-49a4-b2c2-04367ef772f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl02_ctl01']</value>
      <webElementGuid>6103f039-b85f-48d6-b813-00d978e9ab91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl02']/textarea</value>
      <webElementGuid>a141be3e-ba97-46d4-82e7-c8a5a907d4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5bc570bf-ccee-4d5d-a0e4-a54d38942560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ctl00_ContentPlaceHolder2_edtMensajeUsuario_ctl02_ctl01']</value>
      <webElementGuid>7229c088-ce9a-4ce7-83db-9407bdac80ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
