<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Aplica Nombres y Apellidos</name>
   <tag></tag>
   <elementGuidId>64400f1d-f19a-4ac3-b23a-94c1704e247f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divTipoDocEdit']/div/div[2]/table/tbody/tr[6]/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>70e72ecd-83e1-4912-b9bb-feae39cd1fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ckbAplicaNombreApellido</value>
      <webElementGuid>79a8fd9d-d09d-46ab-8db2-5861e3d3a288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divTipoDocEdit&quot;)/div[@class=&quot;caja&quot;]/div[@class=&quot;cajaContenido&quot;]/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[6]/td[2]/span[1]/label[1]</value>
      <webElementGuid>fea73f50-ca36-443b-93a4-c26ad7e21ff9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divTipoDocEdit']/div/div[2]/table/tbody/tr[6]/td[2]/span/label</value>
      <webElementGuid>91ff3a99-22e2-4aee-8c8c-b4d00c9f14aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/span/label</value>
      <webElementGuid>9af49048-d12b-4faa-aa47-69a06741299a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
