<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Activo</name>
   <tag></tag>
   <elementGuidId>28dac299-617a-4dd8-8df4-0c9abe63c77f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divTipoDocEdit']/div/div[2]/table/tbody/tr[5]/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c44bd631-23a9-4abd-bab8-ce68310375d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ckbActivo</value>
      <webElementGuid>6359ee5b-4ec6-47e9-af91-cec5274dfc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divTipoDocEdit&quot;)/div[@class=&quot;caja&quot;]/div[@class=&quot;cajaContenido&quot;]/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[5]/td[2]/span[1]/label[1]</value>
      <webElementGuid>ebb43eaf-a8b3-4ec2-95f9-4cc41b63be6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divTipoDocEdit']/div/div[2]/table/tbody/tr[5]/td[2]/span/label</value>
      <webElementGuid>ea25a279-4086-483e-b8df-7e91b506aa10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>28150b7d-a017-4add-b895-ca6b28a0fa96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
