<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_1 Activo</name>
   <tag></tag>
   <elementGuidId>21073ce4-8185-4384-8d8d-6a4e6827e6b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_grvGrupos']/tbody/tr[2]/td[4]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>52cbf068-6fa7-45a9-882d-777ed95236b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grvGrupos_ctl02_ctl03</value>
      <webElementGuid>51bd3e09-1600-4966-bd36-b0caa4878a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvGrupos&quot;)/tbody[1]/tr[@class=&quot;trClick&quot;]/td[4]/span[1]/label[1]</value>
      <webElementGuid>da3952b6-b794-47ae-bef2-f11b4df6dfd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvGrupos']/tbody/tr[2]/td[4]/span/label</value>
      <webElementGuid>88a191d7-fa9f-4234-9671-5d53c3688959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/span/label</value>
      <webElementGuid>bf756b71-4ba9-4e33-af33-2b3c90cfe177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
