<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_3 Prueba</name>
   <tag></tag>
   <elementGuidId>a6d009fa-dddb-4178-8ef3-91c3d3542b87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_grvGrupos']/tbody/tr[4]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d08d8d79-240c-41d9-bf45-e8f21841f782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>bc65f6ad-4457-430c-a34c-2e00a67b0299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>2372523c-3d2a-450a-a8bd-589057f9052b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Prueba
                            </value>
      <webElementGuid>c8748480-7273-440d-b6b7-85080ad41ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvGrupos&quot;)/tbody[1]/tr[@class=&quot;trClick&quot;]/td[2]</value>
      <webElementGuid>65a2e146-d4da-4ebd-b523-ef13e8ad1413</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvGrupos']/tbody/tr[4]/td[2]</value>
      <webElementGuid>bbdea8ef-347b-4d9c-b9fe-ed3f14cf7ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferencial (P)'])[1]/following::td[6]</value>
      <webElementGuid>0b62a213-d80b-4947-b178-bcb0723baa2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General (G)'])[1]/following::td[12]</value>
      <webElementGuid>0f4908aa-6dd1-466f-a73b-1cfcd5cbc1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/table/tbody/tr[4]/td[2]</value>
      <webElementGuid>2fe7c27c-a99a-4ab9-afa4-32aa4e4760c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                Prueba
                            ' or . = '
                                Prueba
                            ')]</value>
      <webElementGuid>d038adca-e809-4f19-9aa6-e35fae67ba8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
