<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1 Ver detalle Prueba</name>
   <tag></tag>
   <elementGuidId>0172420a-53e3-4112-a20b-e351b0a3b3d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnVerDetalle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnVerDetalle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8cbc45b7-d0c3-4509-b0fd-11ebe4d58461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnVerDetalle</value>
      <webElementGuid>9f613f3e-07c4-4ab7-a113-fa37723edcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ver detalle</value>
      <webElementGuid>7db143e9-b108-40e6-96bf-78e54307aed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnVerDetalleImg</value>
      <webElementGuid>9b9af66c-bb64-40e1-bcf8-5606d84a4769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvAgendasXOficina$ctl02$btnVerDetalle&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>b467c1f3-aa17-47f5-b514-8eeff9c325d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnVerDetalle&quot;)</value>
      <webElementGuid>d569abbc-a8af-4442-b678-c115846b782e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnVerDetalle']</value>
      <webElementGuid>75818c78-9489-49dc-b414-c30ba0fa823f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAgendasXOficina']/tbody/tr[2]/td[10]/div/a</value>
      <webElementGuid>b7d1a9ce-c4cc-406d-8024-ce816b9b66e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvAgendasXOficina$ctl02$btnVerDetalle&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>dfd22c96-3d1d-4ab4-b325-01bf232fde09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/a</value>
      <webElementGuid>2eb8bb4d-3afa-47ba-8150-8d112366f4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnVerDetalle' and @title = 'Ver detalle' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvAgendasXOficina$ctl02$btnVerDetalle&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))']</value>
      <webElementGuid>a8d24187-724c-4e93-a331-863b681efbe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
