<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_1 ExportarExcel</name>
   <tag></tag>
   <elementGuidId>2884296a-45fb-4927-8482-e8321290b40a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnExportarExcel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnExportarExcel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc7c0023-4dab-4694-b147-e77758f2107c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnExportarExcel</value>
      <webElementGuid>72dd8978-fb71-499e-8692-815c3e26c2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Exportar a Excel</value>
      <webElementGuid>26f9b783-e148-4ab6-8edb-71701d197bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnExportarExcelImg</value>
      <webElementGuid>0967c3ab-83d5-4077-a762-d57ad34af896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvAgendasXOficina$ctl02$btnExportarExcel&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>1500bb22-fedf-49d2-ba66-c9aab953405d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnExportarExcel&quot;)</value>
      <webElementGuid>ca72eb51-a701-4a24-b62c-4bd10883184c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnExportarExcel']</value>
      <webElementGuid>80f34385-b1e4-43ee-8d76-a2c5f1c2971c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAgendasXOficina']/tbody/tr[2]/td[10]/div/a[2]</value>
      <webElementGuid>0473a1b2-9a3e-4c28-9c59-446020337c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvAgendasXOficina$ctl02$btnExportarExcel&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>398cc8e9-d79b-4bc8-a890-86374642d7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/a[2]</value>
      <webElementGuid>61bc177b-a1b5-40aa-9a0d-8bac0c19bd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvAgendasXOficina_ctl02_btnExportarExcel' and @title = 'Exportar a Excel' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvAgendasXOficina$ctl02$btnExportarExcel&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))']</value>
      <webElementGuid>36f4be7f-58c2-4029-9a30-be07acfa6199</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
