<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Hora Inicio MM Down</name>
   <tag></tag>
   <elementGuidId>edc9b720-ce53-4d35-bd84-cf2e8a6eaaf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cefe207c-6503-4c47-8920-a5db3212def1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90ddd3eb-e666-49a4-bd6e-de37be2c48cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown</value>
      <webElementGuid>f51f0440-d8d4-4227-9f70-092db2549c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>dc702e3a-6d74-4e79-a4be-b9711cfd000c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown&quot;)</value>
      <webElementGuid>68028cd1-2bfd-4d20-8a07-910f824a24b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown']</value>
      <webElementGuid>deb5d82d-22e2-430d-8340-20c943f7406f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divRolEdit']/table/tbody/tr[8]/td[2]/div/div[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>2ed8b3d8-2f2e-4769-a654-c2a8a7338cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>24c167a4-4719-4d00-88de-0b186bb7df54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bDown']</value>
      <webElementGuid>8145bc00-3ade-4de8-8e60-d8c6e6d60304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
