<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Viernes</name>
   <tag></tag>
   <elementGuidId>5cb24e62-b75a-4528-9278-661fd850f192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder2_divCalDetalle']/div/div[2]/table/tbody/tr[2]/td/span[6]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ed384249-699b-4863-823b-17b264bb93b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_chkViernes</value>
      <webElementGuid>d4eeedf0-810b-4eff-90f4-e6505879f32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Viernes</value>
      <webElementGuid>da67fad4-5e82-456b-b40d-0fb188af2444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_divCalDetalle&quot;)/div[@class=&quot;caja&quot;]/div[@class=&quot;cajaContenido&quot;]/table[1]/tbody[1]/tr[2]/td[1]/span[6]/label[1]</value>
      <webElementGuid>9b4b3e1b-6bcd-4b9b-abf0-281d4ba0db13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_divCalDetalle']/div/div[2]/table/tbody/tr[2]/td/span[6]/label</value>
      <webElementGuid>f324d2ce-151b-4a99-8538-153afa04e6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jueves'])[1]/following::label[1]</value>
      <webElementGuid>6c6530dc-bfc5-43b7-8796-aca2dfcc4284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Miércoles'])[1]/following::label[2]</value>
      <webElementGuid>690eb458-da36-4cfc-b4bf-49310f87f97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sábado'])[1]/preceding::label[1]</value>
      <webElementGuid>58f3a5e7-9294-4565-a828-b6a4ae71e3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fechas no laborables:'])[1]/preceding::label[2]</value>
      <webElementGuid>ee412502-9085-47bc-9129-5089b7b564d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Viernes']/parent::*</value>
      <webElementGuid>feb14084-bad2-4b83-83c1-09137ea0d9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/label</value>
      <webElementGuid>ec154643-6e89-4a01-bd1d-5b0df58ed742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Viernes' or . = 'Viernes')]</value>
      <webElementGuid>e0b31f31-d10d-4d9b-ba2b-4191fae71004</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
