<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Miercoles</name>
   <tag></tag>
   <elementGuidId>1d93f863-51ff-48f1-ab21-5028abe31bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder2_divCalDetalle']/div/div[2]/table/tbody/tr[2]/td/span[4]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>070d3e30-a077-48e9-a60b-0d8e8dedade0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_chkMiercoles</value>
      <webElementGuid>873acaf1-9f5b-4b84-b8c7-e23c07a40b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Miércoles</value>
      <webElementGuid>0a658379-4160-4b8e-8e95-c39009cdd73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_divCalDetalle&quot;)/div[@class=&quot;caja&quot;]/div[@class=&quot;cajaContenido&quot;]/table[1]/tbody[1]/tr[2]/td[1]/span[4]/label[1]</value>
      <webElementGuid>49ce9050-950d-4b77-89ba-cfc40c8082e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_divCalDetalle']/div/div[2]/table/tbody/tr[2]/td/span[4]/label</value>
      <webElementGuid>1caa9020-a698-49c7-849c-2ccb58bf3aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Martes'])[1]/following::label[1]</value>
      <webElementGuid>9061d77b-2b6c-455d-ab18-95988fda7a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lunes'])[1]/following::label[2]</value>
      <webElementGuid>ffeb7517-554e-423f-af5a-3a2b715ccede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jueves'])[1]/preceding::label[1]</value>
      <webElementGuid>0f1980dd-333d-4141-b0d7-bb5ac23b7113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Viernes'])[1]/preceding::label[2]</value>
      <webElementGuid>1c514346-53e8-42e9-8d97-2ba764877ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Miércoles']/parent::*</value>
      <webElementGuid>43493ca4-07ef-4d59-9cc2-a5d63bf88e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/label</value>
      <webElementGuid>b2070b5b-2df5-4c26-9e8f-c81a98299721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Miércoles' or . = 'Miércoles')]</value>
      <webElementGuid>e0500825-5b9c-4f96-8c28-73473ed19019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
