<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Domingo</name>
   <tag></tag>
   <elementGuidId>4044506e-374e-4736-ac89-cf27dddba8af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder2_divCalDetalle']/div/div[2]/table/tbody/tr[2]/td/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>575a11c0-4f12-4bef-a34d-c7e236e5a651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_chkDomingo</value>
      <webElementGuid>eeec8ed3-7a79-4d94-a85f-0611241258b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Domingo</value>
      <webElementGuid>82cd848b-b120-42d9-9ef3-dcb07ab69a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_divCalDetalle&quot;)/div[@class=&quot;caja&quot;]/div[@class=&quot;cajaContenido&quot;]/table[1]/tbody[1]/tr[2]/td[1]/span[1]/label[1]</value>
      <webElementGuid>e27c79b3-5060-446b-8c80-7e35949ba763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_divCalDetalle']/div/div[2]/table/tbody/tr[2]/td/span/label</value>
      <webElementGuid>7154e084-e565-4a49-9fd6-2d26f5cf390e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Días no laborables:'])[1]/following::label[1]</value>
      <webElementGuid>0459cbd4-e4eb-4cc7-a0a5-a69aa156514d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalle del calendario'])[1]/following::label[1]</value>
      <webElementGuid>786da8e4-9f41-499e-a014-5d11740431ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lunes'])[1]/preceding::label[1]</value>
      <webElementGuid>6ba186f5-f68e-408a-b643-ba0614b03fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Martes'])[1]/preceding::label[2]</value>
      <webElementGuid>a8e3cb3d-9790-4a2d-bf44-988706fe1e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Domingo']/parent::*</value>
      <webElementGuid>9c741d17-c2bb-4ed7-ace0-e71ec3daf092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>5d6bab5f-efd4-4b65-8e33-85cf283bdcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Domingo' or . = 'Domingo')]</value>
      <webElementGuid>977b8e81-dc98-41ab-934e-1d9c4b5959bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
