<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_prueba</name>
   <tag></tag>
   <elementGuidId>1355d4d2-8b98-40e0-91ae-999a6e2e5eea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_rblRoles']/tbody/tr[2]/td/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>63c0b540-a678-4265-b563-08d3a4fefa67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_rblRoles_1</value>
      <webElementGuid>b077beb5-8f6e-4530-a2fe-dfed7386ee6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>prueba</value>
      <webElementGuid>52d1c2ec-dfb0-46bd-8d7f-2fd2bb887106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_rblRoles&quot;)/tbody[1]/tr[2]/td[1]/label[1]</value>
      <webElementGuid>a437d34c-40c6-451a-af9c-b7cb3b17c5cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_rblRoles']/tbody/tr[2]/td/label</value>
      <webElementGuid>f264187d-218c-4917-8604-edfad1b2335e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIEL'])[2]/following::label[1]</value>
      <webElementGuid>6a0d47c3-36e0-4b6d-935e-bea755ecd7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles de Agendamiento'])[1]/following::label[2]</value>
      <webElementGuid>4cd94a15-c5ed-43e3-a961-28b2d83827c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Páginas por rol'])[3]/preceding::label[1]</value>
      <webElementGuid>b6cc57ed-92ab-4e6d-b6f3-9dd6c76395bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Página'])[1]/preceding::label[1]</value>
      <webElementGuid>7ed46b38-bbbd-494e-8841-37672014c32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='prueba']/parent::*</value>
      <webElementGuid>4ff46044-b51b-4add-b250-22f3d9b8de57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/label</value>
      <webElementGuid>10b42401-7a2e-4bae-aa4b-9f6b7cdc7d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'prueba' or . = 'prueba')]</value>
      <webElementGuid>8f308a30-df69-4394-98ae-6668ca7a13fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
