<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_2 Fin de Jornada</name>
   <tag></tag>
   <elementGuidId>dc523369-1bdc-46e2-8a66-447f3d23369a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_mcMotivosXOficina_gvMotivos']/tbody/tr[3]/td[5]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>98acfd9c-8728-410d-82ce-5610d79d52a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_mcMotivosXOficina_gvMotivos_ctl03_chkSeleccionar</value>
      <webElementGuid>3e1abee0-8418-46a1-841f-97e10d088562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_mcMotivosXOficina_gvMotivos&quot;)/tbody[1]/tr[3]/td[5]/span[@class=&quot;chkAspGeneric&quot;]/label[1]</value>
      <webElementGuid>3aea9a02-c1ac-4010-99a6-d62272163115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_mcMotivosXOficina_gvMotivos']/tbody/tr[3]/td[5]/span/label</value>
      <webElementGuid>0741492a-e31b-46a3-a982-d55f71377e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/span/label</value>
      <webElementGuid>a3cf996a-3769-4e39-8fce-333e030e0ae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
