<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Seleccionar Todo</name>
   <tag></tag>
   <elementGuidId>bd207f50-7565-4fc0-afc4-5a4dfa1958c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_mcMotivosXOficina_gvMotivos']/tbody/tr/th[5]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a5df0d82-80c8-4a49-9979-33f0f910988e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_mcMotivosXOficina_gvMotivos_ctl01_chkSelTodo</value>
      <webElementGuid>2ace53b5-de14-435b-9079-de8c0b6d53b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_mcMotivosXOficina_gvMotivos&quot;)/tbody[1]/tr[1]/th[5]/label[1]</value>
      <webElementGuid>f5b2f8ae-0961-47a9-80e3-bedc1ab2c872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_mcMotivosXOficina_gvMotivos']/tbody/tr/th[5]/label</value>
      <webElementGuid>18612c6a-49cf-40c4-9e48-045a6f50a0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>5cb60675-0d6f-4550-964b-1527ecdc92b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
