<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_NO 1 GG Informacion</name>
   <tag></tag>
   <elementGuidId>6dbb738c-be2f-475c-9780-3fa055a06311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_grvServicios_ctl02_btnDesSeleccionar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_grvServicios_ctl02_btnDesSeleccionar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1de03d52-a1ee-4ae0-b049-ba813e7cc1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>8d07a45f-c767-4c08-a78b-5ce79219605c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$grvServicios$ctl02$btnDesSeleccionar</value>
      <webElementGuid>aef5c5b1-d948-4e5c-8639-e64758006667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grvServicios_ctl02_btnDesSeleccionar</value>
      <webElementGuid>cd21f639-7caa-4bbd-b81e-a18ce61ca831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Imagenes/Cancel.svg</value>
      <webElementGuid>f787d470-117d-4695-b0d1-84212c8f0ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvServicios_ctl02_btnDesSeleccionar&quot;)</value>
      <webElementGuid>cc3d3845-8755-47d2-80a0-afd6d4250e32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_grvServicios_ctl02_btnDesSeleccionar']</value>
      <webElementGuid>acfddbad-117b-49d3-b7ba-c28fdc56b967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvServicios']/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>188376ca-fc46-41ed-bc4c-9f911138285a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>acaa4e86-4013-49a6-875f-82b6e5184caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$grvServicios$ctl02$btnDesSeleccionar' and @id = 'ctl00_ContentPlaceHolder2_grvServicios_ctl02_btnDesSeleccionar' and @src = '../../../Imagenes/Cancel.svg']</value>
      <webElementGuid>d5249ecf-7bea-4e6e-83a4-0194ef724274</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
