<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_NO 2 GG PQRS</name>
   <tag></tag>
   <elementGuidId>fbfb740f-6f33-4253-919d-8e04fad833d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_grvServicios_ctl03_btnDesSeleccionar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_grvServicios_ctl03_btnDesSeleccionar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ca27504-c156-4d13-ba1e-cd3c64807625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>8a7157b6-ead7-47ba-9c76-ad8e85890144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$grvServicios$ctl03$btnDesSeleccionar</value>
      <webElementGuid>50d04c6b-f0c1-486c-900f-9c4b26da14af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grvServicios_ctl03_btnDesSeleccionar</value>
      <webElementGuid>b0439f6f-8b6e-4ba4-8498-d290ecb7342b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Imagenes/Cancel.svg</value>
      <webElementGuid>125cd5aa-2110-42be-a96f-329eb2b9a0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvServicios_ctl03_btnDesSeleccionar&quot;)</value>
      <webElementGuid>d5770cc8-0cd9-43dd-b416-d5467e999960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_grvServicios_ctl03_btnDesSeleccionar']</value>
      <webElementGuid>1954f2f9-8f37-4768-a5af-d049d82f0e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvServicios']/tbody/tr[3]/td[4]/input</value>
      <webElementGuid>3fa71f63-98ba-423a-884a-1015ab59a4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/input</value>
      <webElementGuid>6ad00417-7e31-4a4e-835a-b3944e2c331b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$grvServicios$ctl03$btnDesSeleccionar' and @id = 'ctl00_ContentPlaceHolder2_grvServicios_ctl03_btnDesSeleccionar' and @src = '../../../Imagenes/Cancel.svg']</value>
      <webElementGuid>18a69e32-ed50-4e5f-82ad-af3fcb3aabf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
