<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_SI 6 GP Radicaciones</name>
   <tag></tag>
   <elementGuidId>b18cf076-566e-469a-b227-f781f770ac3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_grvServicios_ctl07_btnSeleccionar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_grvServicios_ctl07_btnSeleccionar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>617b95d1-1408-4a39-8123-d92c3c370cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>77435ede-b8ac-4a2b-a372-7e5378bf7200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$grvServicios$ctl07$btnSeleccionar</value>
      <webElementGuid>18eff618-8848-4940-ab84-3c3e118fa834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grvServicios_ctl07_btnSeleccionar</value>
      <webElementGuid>35aff55e-9876-441f-95ce-16552b586d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Imagenes/Update.svg</value>
      <webElementGuid>b1396b4d-c303-4f3c-9958-73b6d197f35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvServicios_ctl07_btnSeleccionar&quot;)</value>
      <webElementGuid>73a6c116-2f1b-4e0c-8b7d-6f558f99436b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_grvServicios_ctl07_btnSeleccionar']</value>
      <webElementGuid>d4439dc7-8f0f-4eda-a6a0-3fceb9180536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvServicios']/tbody/tr[7]/td[3]/input</value>
      <webElementGuid>386bd3c0-2a03-4735-9eef-aad8eca7710e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[3]/input</value>
      <webElementGuid>5fe66619-1e16-418d-98fa-538c7e681b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$grvServicios$ctl07$btnSeleccionar' and @id = 'ctl00_ContentPlaceHolder2_grvServicios_ctl07_btnSeleccionar' and @src = '../../../Imagenes/Update.svg']</value>
      <webElementGuid>6dc7ec45-66a1-4a2c-9271-22dd58ef038f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
