<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_NO 4 GP Informacion</name>
   <tag></tag>
   <elementGuidId>f66fc4fd-664a-4fe0-a7dc-4c774be70b8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_grvServicios_ctl05_btnDesSeleccionar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_grvServicios_ctl05_btnDesSeleccionar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>788781d2-7920-4826-b770-21bfdf16c4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>64cb7b18-7613-4a2e-81e1-92aca8be1f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$grvServicios$ctl05$btnDesSeleccionar</value>
      <webElementGuid>ed23d06c-9175-479d-8525-d697827a51d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grvServicios_ctl05_btnDesSeleccionar</value>
      <webElementGuid>be06e5be-229a-4439-94fd-066b5baa18f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Imagenes/Cancel.svg</value>
      <webElementGuid>1b45bf27-3626-4299-b668-7c01c23baddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvServicios_ctl05_btnDesSeleccionar&quot;)</value>
      <webElementGuid>b57a2041-0942-4c93-994a-79c2d6c84332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_grvServicios_ctl05_btnDesSeleccionar']</value>
      <webElementGuid>1c0a9709-ff55-4d28-ae33-1c738b844bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvServicios']/tbody/tr[5]/td[4]/input</value>
      <webElementGuid>5398352e-d77f-473a-b36c-af9beb125187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/input</value>
      <webElementGuid>98b42003-13c4-4a66-8828-511816444734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$grvServicios$ctl05$btnDesSeleccionar' and @id = 'ctl00_ContentPlaceHolder2_grvServicios_ctl05_btnDesSeleccionar' and @src = '../../../Imagenes/Cancel.svg']</value>
      <webElementGuid>32acd52c-4fa9-45c2-a26b-9f440003edb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
