<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_SI 7 Prueba</name>
   <tag></tag>
   <elementGuidId>8b93a454-0ce5-43f3-9ad6-84925375559b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_grvServicios_ctl08_btnSeleccionar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_grvServicios_ctl08_btnSeleccionar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4107f1a9-3605-4253-a4e3-48260ebd8f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>2acceb42-42bf-4018-80ee-2a52a27e661d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$grvServicios$ctl08$btnSeleccionar</value>
      <webElementGuid>7090b2cb-a01b-4f3b-8e1b-2845727ccb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grvServicios_ctl08_btnSeleccionar</value>
      <webElementGuid>11a1558d-4b11-477d-accd-ea0d212a1d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Imagenes/Update.svg</value>
      <webElementGuid>65b0befe-ea44-4364-8fb9-cf265dff54f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvServicios_ctl08_btnSeleccionar&quot;)</value>
      <webElementGuid>95e9ae60-ecdc-4c9c-add7-3f1ed7da8014</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_grvServicios_ctl08_btnSeleccionar']</value>
      <webElementGuid>c6d10b43-6742-4f2b-b06a-0ce70365b27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvServicios']/tbody/tr[8]/td[3]/input</value>
      <webElementGuid>5a686291-5946-4316-bb99-ba158912ea23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[3]/input</value>
      <webElementGuid>67ee852a-bb24-4216-bd65-20b2f76ba374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$grvServicios$ctl08$btnSeleccionar' and @id = 'ctl00_ContentPlaceHolder2_grvServicios_ctl08_btnSeleccionar' and @src = '../../../Imagenes/Update.svg']</value>
      <webElementGuid>bc10dd8b-e62a-4b7a-a018-208654115480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
