<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_2 Cali</name>
   <tag></tag>
   <elementGuidId>c636dd7f-8523-4821-b202-e0f765477f34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvOficinas']/tbody/tr[3]/td[3]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>dd85ef47-b799-4642-91d8-b91b3f8df1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvOficinas_ctl03_chkSeleccionar</value>
      <webElementGuid>0821768a-1eb6-4486-b590-4f3c706bfacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvOficinas&quot;)/tbody[1]/tr[3]/td[3]/span[@class=&quot;chkAspGeneric&quot;]/label[1]</value>
      <webElementGuid>0e2f0318-c962-49af-b577-ac5d824f4933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvOficinas']/tbody/tr[3]/td[3]/span/label</value>
      <webElementGuid>9036d0e9-913e-4b7d-b92f-41560b930ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/span/label</value>
      <webElementGuid>52708add-ce19-43f5-b9d4-c8b2582c53b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
