<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Seleccionar Todas</name>
   <tag></tag>
   <elementGuidId>2dd8745a-47e1-46be-ab1b-38ad70b3ad3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvOficinas']/tbody/tr/th[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9e5fba64-bb3c-481b-92e4-82360ab62349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvOficinas_ctl01_chkSelTodo</value>
      <webElementGuid>6d8fe5ee-5d8a-4382-9fa4-58716ef6e303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvOficinas&quot;)/tbody[1]/tr[1]/th[3]/label[1]</value>
      <webElementGuid>69e4b868-47e1-4a0e-ad50-d44850572451</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvOficinas']/tbody/tr/th[3]/label</value>
      <webElementGuid>d3772a73-44b2-4b2f-827d-8a7296ea7970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/label</value>
      <webElementGuid>1341904e-13f5-4178-b8be-015d237a74af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
