<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_3 Cartagena</name>
   <tag></tag>
   <elementGuidId>949c2839-4590-4e3c-9d07-47045423f24e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvOficinas']/tbody/tr[4]/td[3]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cb779fe1-65cb-44ad-8f4f-e401131666fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvOficinas_ctl04_chkSeleccionar</value>
      <webElementGuid>70320a8d-9a12-434c-bb85-b2f3ed0ad633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvOficinas&quot;)/tbody[1]/tr[4]/td[3]/span[@class=&quot;chkAspGeneric&quot;]/label[1]</value>
      <webElementGuid>e1b1622d-b44b-4563-9f03-9088c4264192</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvOficinas']/tbody/tr[4]/td[3]/span/label</value>
      <webElementGuid>1b6f3d1d-9bb2-412a-9ee5-0728a09b8a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/span/label</value>
      <webElementGuid>759ba7d8-00ef-4962-8fbc-b87a2b7bfe8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
