<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label1</name>
   <tag></tag>
   <elementGuidId>c3cab16d-088c-4cd9-861e-06c55fa8d3f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvHistoricoCitas']/tbody/tr[2]/td[12]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.chkGrilla > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e8b31f89-82fd-47a8-ad23-fa06d1bbaace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvHistoricoCitas_ctl02_chkSeleccionNotificar</value>
      <webElementGuid>7d0ce4f8-3940-412b-97f3-4c03a57ccf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvHistoricoCitas&quot;)/tbody[1]/tr[2]/td[12]/span[@class=&quot;chkGrilla&quot;]/label[1]</value>
      <webElementGuid>4c3aa67a-0559-445d-8ed6-c0b98068d167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvHistoricoCitas']/tbody/tr[2]/td[12]/span/label</value>
      <webElementGuid>dfb0f7f1-666f-480b-bf9f-da312602a1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>d50631fa-0d29-4b79-b6ee-0af767dd4a61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
