<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label2</name>
   <tag></tag>
   <elementGuidId>9be37f79-03cb-4872-9adb-fc97b8ace346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvHistoricoCitas']/tbody/tr[3]/td[12]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td:nth-of-type(12) > span.chkGrilla > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>30870bf7-61a3-4de5-8f44-554b86234570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvHistoricoCitas_ctl03_chkSeleccionNotificar</value>
      <webElementGuid>cc3efe30-266e-441a-9da6-0d60703e8f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvHistoricoCitas&quot;)/tbody[1]/tr[3]/td[12]/span[@class=&quot;chkGrilla&quot;]/label[1]</value>
      <webElementGuid>a73e7a57-2a43-45f3-9124-0fe75e3bd922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvHistoricoCitas']/tbody/tr[3]/td[12]/span/label</value>
      <webElementGuid>6e554d96-0172-4df2-bc34-bcba48f8dbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[12]/span/label</value>
      <webElementGuid>57c5979a-64da-4891-a916-ec47dea6a228</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
