<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5 RC_Borrar</name>
   <tag></tag>
   <elementGuidId>42211d65-59e8-4683-a7dd-1cb3746d5620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl06_btnBorrar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl06_btnBorrar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1af17c20-4c3e-4526-bce6-c1808ec98938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('¿Desea eliminar el tipo de documento?');</value>
      <webElementGuid>88793623-2589-4ca2-ac50-a5054fa94c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl06_btnBorrar</value>
      <webElementGuid>55bf0a34-4f78-4306-a32d-6ec2d02bc028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnBorrarImg</value>
      <webElementGuid>af958e59-1866-4b20-a00f-9eca7396f562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvrTiposDocumentos$ctl06$btnBorrar','')</value>
      <webElementGuid>b06e1fbd-2297-4573-bf49-59182e96b73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl06_btnBorrar&quot;)</value>
      <webElementGuid>097679ef-a120-4b76-a6f5-6813daf82151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl06_btnBorrar']</value>
      <webElementGuid>3919ab14-c02e-4e92-8a34-f19099a610fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvrTiposDocumentos']/tbody/tr[6]/td[7]/div/a[2]</value>
      <webElementGuid>12c1424d-0eb2-4d41-9407-5bc3460b831b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvrTiposDocumentos$ctl06$btnBorrar','')&quot;)]</value>
      <webElementGuid>d1373894-5fbe-4d1b-93ce-9daeabbd11e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[7]/div/a[2]</value>
      <webElementGuid>5e5c05ec-ce55-4f06-a752-792cf719faac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl06_btnBorrar' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder2$gvrTiposDocumentos$ctl06$btnBorrar&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;)]</value>
      <webElementGuid>72a22cb4-f591-4861-aa15-2767e5f5beb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
