<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_6 Prueba_Borrar</name>
   <tag></tag>
   <elementGuidId>a461a424-d863-4e4c-bf3e-aadf632c86da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl07_btnBorrar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl07_btnBorrar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9cd40f34-8020-494b-9ef3-816197ba54b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('¿Desea eliminar el tipo de documento?');</value>
      <webElementGuid>d6923045-562e-40b2-84ab-cac69074c2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl07_btnBorrar</value>
      <webElementGuid>06a06212-60f6-42ba-908e-1c1b7f6c4c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnBorrarImg</value>
      <webElementGuid>e8ab1514-c779-445d-be7d-0f3042ea9b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvrTiposDocumentos$ctl07$btnBorrar','')</value>
      <webElementGuid>f73d7d09-3ca1-4cf1-bd6c-c8110d22f1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl07_btnBorrar&quot;)</value>
      <webElementGuid>000282a2-c6c2-46ea-b1dc-e5d087d95f01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl07_btnBorrar']</value>
      <webElementGuid>903950a2-c9ac-449c-b2b8-865bebab532c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvrTiposDocumentos']/tbody/tr[7]/td[7]/div/a[2]</value>
      <webElementGuid>a3df4048-5e0c-466d-98dc-a2a8c8ee4c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvrTiposDocumentos$ctl07$btnBorrar','')&quot;)]</value>
      <webElementGuid>75a1f605-63ea-40db-b171-fa404a14aae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[7]/div/a[2]</value>
      <webElementGuid>1d514816-2054-403a-a7c7-94889cc1a89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvrTiposDocumentos_ctl07_btnBorrar' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder2$gvrTiposDocumentos$ctl07$btnBorrar&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;)]</value>
      <webElementGuid>2a63661d-83af-4120-a472-a8ee323e8aa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
