<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a3_Ver Detalle</name>
   <tag></tag>
   <elementGuidId>6f4733b6-fe9b-4a54-8007-0ea836e51b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvAgendasXFechas_ctl04_btnVerDetalle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvAgendasXFechas_ctl04_btnVerDetalle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>41b92d79-cb1e-4a89-ad34-bf0184006814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvAgendasXFechas_ctl04_btnVerDetalle</value>
      <webElementGuid>9c68445e-5afc-4f18-be88-cea62d8e0288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ver detalle</value>
      <webElementGuid>c47800a4-f562-4e18-8864-47a2b8a08297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnVerDetalleImg</value>
      <webElementGuid>72576989-16c5-42e4-8933-d7ca123c0591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvAgendasXFechas$ctl04$btnVerDetalle&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>a040465c-8ee3-45ea-acea-839c2b4ce4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAgendasXFechas_ctl04_btnVerDetalle&quot;)</value>
      <webElementGuid>2afd46f7-36cc-4d0c-80ee-7635ca307683</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvAgendasXFechas_ctl04_btnVerDetalle']</value>
      <webElementGuid>1dcbbf7b-d389-41e4-b111-47fbb9d73fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAgendasXFechas']/tbody/tr[4]/td[8]/div/a</value>
      <webElementGuid>571f9223-fc48-4456-b357-6e148dc1b1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvAgendasXFechas$ctl04$btnVerDetalle&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>04742b60-bfbb-42f3-bee1-05fcb6e46b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[8]/div/a</value>
      <webElementGuid>3505d771-a146-49f6-bd85-d18c69f1f4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvAgendasXFechas_ctl04_btnVerDetalle' and @title = 'Ver detalle' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvAgendasXFechas$ctl04$btnVerDetalle&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))']</value>
      <webElementGuid>543a19e0-bbd8-41f7-a834-6bbbf1dd2b5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
