<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Eliminar Suspendidas</name>
   <tag></tag>
   <elementGuidId>197d6310-e00a-463d-b0d9-9f193cffd825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_btnEliminarAgendasSuspendidas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_btnEliminarAgendasSuspendidas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c0ee033-0a95-4009-9c38-e14f23d5e044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>14343160-5010-43af-86bf-418806028647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$btnEliminarAgendasSuspendidas</value>
      <webElementGuid>d0d8172e-7f78-4aea-956f-3769225413c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Eliminar suspendidas</value>
      <webElementGuid>1caa6c81-9408-48f7-877c-e5a00f9f291d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Se eliminarán todas las agendas de los registros seleccionados teniendo en cuenta el flitro de Estado Agenda exceptuando las agendas confirmadas. \n¿Está seguro de realizar la acción?');WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$btnEliminarAgendasSuspendidas&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>01ff2d11-75a9-40dc-b755-d4dd79c7010e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_btnEliminarAgendasSuspendidas</value>
      <webElementGuid>dcadeadc-c9cb-4a07-a07e-c859ac3d4a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Recuerde que el filtro de Estado Agenda se tendrá en cuenta para la eliminación de las agendas seleccionadas</value>
      <webElementGuid>3edb53b7-53e9-4154-b861-df4d2f4f7b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton</value>
      <webElementGuid>74062ee6-5788-4b85-8c28-f2b43cf9c3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_btnEliminarAgendasSuspendidas&quot;)</value>
      <webElementGuid>cef2fb0b-7734-438e-8d7f-92a2f4a357af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_btnEliminarAgendasSuspendidas']</value>
      <webElementGuid>a86bd331-e655-4091-9fd7-0f91edf31569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_divGrillaAgeConData']/div[2]/input[4]</value>
      <webElementGuid>dbce4012-d6b3-4edb-92dd-115e59349e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>993431b5-724a-46f2-9bcc-adef647ba27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder2$btnEliminarAgendasSuspendidas' and @id = 'ctl00_ContentPlaceHolder2_btnEliminarAgendasSuspendidas' and @title = 'Recuerde que el filtro de Estado Agenda se tendrá en cuenta para la eliminación de las agendas seleccionadas']</value>
      <webElementGuid>3cfeb507-5437-44b5-bcde-e79ba5b8885b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
