<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Reservadas a Disponible</name>
   <tag></tag>
   <elementGuidId>0f6be493-7179-46ae-86b2-8abc78a40cf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04e68f33-c765-4226-9f69-1adb565e834b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1c3d2008-f0a3-4249-aaa6-1d89bb429902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$btnHabilitarCitasReservadas</value>
      <webElementGuid>43b3dd67-ad7a-455f-b589-fa2b2c7ee8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Reservadas a disponible</value>
      <webElementGuid>7261b665-92d5-4bb7-ab61-be614836e782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Se habilitarán todas las agendas reservadas de los registros seleccionados. \n¿Está seguro de realizar la acción?');WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$btnHabilitarCitasReservadas&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>b4954288-9048-45f8-a5b6-d3ced2e689ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas</value>
      <webElementGuid>1f88e4d7-100d-49ee-955e-87387cc38f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>botonIcono btnCambio btnCambio3</value>
      <webElementGuid>ed6726f0-7376-4692-b6f5-781476204f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas&quot;)</value>
      <webElementGuid>ea30dced-2779-4596-ad25-2721ee464185</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas']</value>
      <webElementGuid>9211c3a3-8d26-451d-854a-766e5347baa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_divGrillaAgeConData']/div[2]/input[3]</value>
      <webElementGuid>2d49663b-ef3a-4ae5-a687-a7b7e5288749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>785cb5cf-d9b5-4fec-8373-a6eedc97e467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder2$btnHabilitarCitasReservadas' and @id = 'ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas']</value>
      <webElementGuid>2ffbe75e-4b94-4b13-912b-2c7afbca5e12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
