<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clave</name>
   <tag></tag>
   <elementGuidId>d0ce7347-82ce-4616-b165-ba1a74437d3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtClave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;txtClave&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a27f0db4-d192-47e9-baba-f98f9bf29e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtClave</value>
      <webElementGuid>e2075add-50e6-40da-bbf3-a79eb39d93f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a1be204a-ef1b-4ad2-aa72-7ddc4a3849b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtClave</value>
      <webElementGuid>7420c7e7-6034-4c68-bc1b-26e47d6fc0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtClave&quot;)</value>
      <webElementGuid>bbd4f0be-0553-4f82-975a-32206f76b79a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtClave']</value>
      <webElementGuid>91944c8e-c503-4a6e-b147-57bbd65f2c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trContrasena']/td[2]/input</value>
      <webElementGuid>b28e12a6-573c-4998-8f91-a749ef5c48fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>b1442a10-2971-4db2-a7a0-2e38f20310c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtClave' and @type = 'password' and @id = 'txtClave']</value>
      <webElementGuid>dcf67b19-cfb1-4838-b34a-3e9b5cc7a94a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
