<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_8 Origenes</name>
   <tag></tag>
   <elementGuidId>2d4adc0e-e249-4d78-9a7d-b9d361606364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='Utilidades.establecerEfectoHeader()'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3c4f1a52-01a4-46c6-a317-a6972adb770a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>idpagina</name>
      <type>Main</type>
      <value>51</value>
      <webElementGuid>23bbdb6d-a7de-4d9b-a61d-89585702bca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Paginas/Configuracion/Sistema/frmOrigenes.aspx</value>
      <webElementGuid>c922b53c-5363-4e3b-80b8-76bd4c72afaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utilidades.establecerEfectoHeader()</value>
      <webElementGuid>ec0362b4-ba07-449c-ab46-778379ba7cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemnumber</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>20bb079c-3a35-423e-af20-62394c8fed79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        
                        Orígenes
                    </value>
      <webElementGuid>774762b4-ab29-44ef-8eb9-34dc2f3849a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_UpdatePanel1&quot;)/div[@class=&quot;divCentral container-fluid&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center&quot;]/div[@class=&quot;contenedorMenuIconos&quot;]/div[@class=&quot;menuIconos&quot;]/div[1]/a[8]</value>
      <webElementGuid>46571d34-d669-48d5-8d73-82e7f66714da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='Utilidades.establecerEfectoHeader()'])[8]</value>
      <webElementGuid>0781a74b-efb5-4203-ba4b-9979947c1869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_UpdatePanel1']/div/div/div/div[2]/div/a[8]</value>
      <webElementGuid>eb56850b-0527-4580-a0b1-7a7d1c1afab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motivos de cancelación'])[2]/following::a[1]</value>
      <webElementGuid>53f90d85-a4bf-4d03-957f-64d5503b1169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Módulos y personalizaciones'])[2]/following::a[2]</value>
      <webElementGuid>5445b72c-8fe8-42aa-9719-bdf871e03b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Paginas/Configuracion/Sistema/frmOrigenes.aspx')]</value>
      <webElementGuid>3213b834-ed28-4bb4-a3b4-f572018ef0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[8]</value>
      <webElementGuid>453b6ff0-656e-4876-90a8-09b38b4b731f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Paginas/Configuracion/Sistema/frmOrigenes.aspx' and (text() = '
                        
                        Orígenes
                    ' or . = '
                        
                        Orígenes
                    ')]</value>
      <webElementGuid>21365273-3319-4760-8c21-94b3b2918f81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
