<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cerrar sesion</name>
   <tag></tag>
   <elementGuidId>7bbf13b5-9fbe-4260-92f5-54fad868f5b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_HlCerrarSesion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_HlCerrarSesion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bef99dfd-482e-4330-a5d2-28ba2fe99f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_HlCerrarSesion</value>
      <webElementGuid>cbde3011-fb9f-4d8e-ba8b-8e3cc1f78da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>me-1</value>
      <webElementGuid>f88e6684-575a-4131-ac90-5cdf31d365b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$HlCerrarSesion','')</value>
      <webElementGuid>390f396f-f5f3-4e2d-b85c-464a3eb5b57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cerrar sesión</value>
      <webElementGuid>0fce9840-cab4-42c1-bb92-93631098de7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_HlCerrarSesion&quot;)</value>
      <webElementGuid>10bc9372-75f7-4ad7-b7b6-7efa93e24aff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_HlCerrarSesion']</value>
      <webElementGuid>d716c854-256f-467c-a3c8-225eedfacc28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/div[2]/div/div/div[2]/div[2]/div[2]/a</value>
      <webElementGuid>e0175415-78bd-4f7b-a1f3-38f07773f8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cerrar sesión')]</value>
      <webElementGuid>abf0a04a-c173-4002-a4a9-8cfb3193d017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIEL'])[1]/following::a[1]</value>
      <webElementGuid>3733e0c1-ae73-4bbc-bd78-60506c17617e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciel'])[2]/following::a[1]</value>
      <webElementGuid>da6ba9fd-6984-4a2c-910b-60b94521a9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambiar clave'])[1]/preceding::a[1]</value>
      <webElementGuid>3365d9c7-9f23-4888-bb2e-2f02f823d788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[1]/preceding::a[4]</value>
      <webElementGuid>d430240c-78bb-4f02-b6d3-b8cb607fceb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cerrar sesión']/parent::*</value>
      <webElementGuid>b061ab27-26f1-42e5-a0d4-286e134157c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$HlCerrarSesion','')&quot;)]</value>
      <webElementGuid>8807963b-29f1-4a33-9849-ab30af6c69bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/a</value>
      <webElementGuid>20fb940d-70cb-467b-92a1-d84f7e52c994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_HlCerrarSesion' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$HlCerrarSesion&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Cerrar sesión' or . = 'Cerrar sesión')]</value>
      <webElementGuid>230e079f-cd69-4dc3-9932-bcadd14aa54a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
