<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_1</name>
   <tag></tag>
   <elementGuidId>6ab5c692-9f21-4ea4-812c-6448e7dcdf4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_grvEspecialidadesXCampo']/tbody/tr[2]/td[3]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.chkAspGeneric.chkCampo > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>67aa5cd3-5dea-4f54-aaa4-d936397900aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grvEspecialidadesXCampo_ctl02_chkSeleccionar</value>
      <webElementGuid>5ec57b63-4639-4a30-9663-50c3148d7ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvEspecialidadesXCampo&quot;)/tbody[1]/tr[2]/td[3]/span[@class=&quot;chkAspGeneric chkCampo&quot;]/label[1]</value>
      <webElementGuid>14aaaafc-3ad8-4bb8-93c9-003c5610cc18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvEspecialidadesXCampo']/tbody/tr[2]/td[3]/span/label</value>
      <webElementGuid>57d97229-e00a-4113-98a2-20a2df866ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span/label</value>
      <webElementGuid>84b0392b-531c-4548-8ab4-27ebf52867e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
