<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fecha Inicio Mes Siguiente</name>
   <tag></tag>
   <elementGuidId>3ec169be-ef85-452e-9983-1e881b0c33a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e30b7edf-7f8f-4c72-b818-11cb4814150a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN</value>
      <webElementGuid>40a82a6c-be46-469a-bc0c-dc22b027f310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-button rcNext</value>
      <webElementGuid>07c6a0e9-4ac3-4fcc-94a4-2325a3a657a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>></value>
      <webElementGuid>3a177165-f454-4635-81e7-c8d27010b7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e127441b-dedd-4a71-9eb1-5869e1e99b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>></value>
      <webElementGuid>ce1c3489-25fa-42a3-abbd-4d7be1edc832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN&quot;)</value>
      <webElementGuid>13dc10c5-2485-4037-8c88-6fcbe9da7e29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN']</value>
      <webElementGuid>caec93c9-872e-4c57-94e9-cd2bc4ef957f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar']/thead/tr/td/table/tbody/tr/td[4]/a</value>
      <webElementGuid>d10ebac3-ebab-4696-946a-34b29076bef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'>')]</value>
      <webElementGuid>8cfaaedf-e750-438c-b4d5-0364c2df8896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='julio de 2022'])[1]/following::a[1]</value>
      <webElementGuid>6d1280dc-1785-4ce8-a5bf-3b8cf448946d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title and navigation'])[2]/following::a[3]</value>
      <webElementGuid>bf78ed7b-3e6f-4ee7-b910-dfbcb6cd2429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='julio de 2022'])[2]/preceding::a[2]</value>
      <webElementGuid>ab21832c-26d2-46ce-ac16-5175f62ce634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[1]/preceding::a[2]</value>
      <webElementGuid>fa318b98-1dec-4123-a58d-c690f3950dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='>']/parent::*</value>
      <webElementGuid>c4b41f4a-b90b-4bb7-b7b9-1f27dd124226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>452b553f-123f-4406-b531-8da5eea95063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>7b99849b-1753-451a-a2c7-c40401026791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_rdpFechaInicio_calendar_NN' and @title = '>' and @href = '#' and (text() = '>' or . = '>')]</value>
      <webElementGuid>04306be2-a6d0-488e-ae9a-33fe3f33fc84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
