<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Descendente</name>
   <tag></tag>
   <elementGuidId>c4539dec-ae40-4e0b-8518-b8a2597501f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divFiltrosCitas']/div[10]/div[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4140e19a-2af9-4353-995b-8957ba8f703c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_rbtOrdenFechaDesc</value>
      <webElementGuid>af6f29fc-ede8-4b6e-9450-6ff7260a558a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descendente</value>
      <webElementGuid>6f985624-6123-4208-a0a4-e383fcee34a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divFiltrosCitas&quot;)/div[@class=&quot;input-group&quot;]/div[@class=&quot;divFechaOrden&quot;]/span[1]/label[1]</value>
      <webElementGuid>b0afd3cc-8515-46c1-8c0b-ad0d0dd9893d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divFiltrosCitas']/div[10]/div[2]/span/label</value>
      <webElementGuid>7f15a3b9-6f3f-4970-99e8-4646fc82a0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ascendente'])[1]/following::label[1]</value>
      <webElementGuid>ebe881ea-c376-4d3b-8ca3-44e790046d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::label[2]</value>
      <webElementGuid>8d7794e4-ab3b-4c78-ad96-f8c94a16038b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha y hora'])[1]/preceding::label[1]</value>
      <webElementGuid>48811690-dc8f-45ac-9db7-0b916c475681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Punto de contacto'])[1]/preceding::label[1]</value>
      <webElementGuid>1be72d98-a9e4-4968-aa89-f4e0a9d4de97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Descendente']/parent::*</value>
      <webElementGuid>a9711dcb-1546-4b53-8ba4-a2178e00ce7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/label</value>
      <webElementGuid>5a4866c5-fc80-4903-b2d0-a6b5bb1fb666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Descendente' or . = 'Descendente')]</value>
      <webElementGuid>7dc57846-e87c-4255-945f-83d24b4dca02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
