<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Limpiar</name>
   <tag></tag>
   <elementGuidId>07b938a1-1756-43c9-bd3d-837b2a61e6e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Button1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Button1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0430c90a-3262-421c-a2e5-3415aab4343c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>516de313-596e-4807-97f7-b752302e3473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Button1</value>
      <webElementGuid>f4802a20-5c3a-4add-a2e9-4cc2993b308a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Limpiar</value>
      <webElementGuid>0b019ed1-e229-4b32-bbdd-0deb9502e3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>BuscarGrilla.LimpiarBusqueda();</value>
      <webElementGuid>45a0cda5-bf6a-4c07-b23e-e5e920f1b21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Button1&quot;)</value>
      <webElementGuid>2680a15a-cf50-425f-852a-38adf32e684c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Button1']</value>
      <webElementGuid>979b66fb-174a-4c3d-b884-49e2bc051853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_UpdatePanel1']/div/div/div[2]/div/div[2]/div/input[3]</value>
      <webElementGuid>d62d5f0b-a0fd-4d85-acc1-7787fc5c4910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[3]</value>
      <webElementGuid>92af37b9-7ee1-4d4a-97b0-a90142ca02e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'Button1']</value>
      <webElementGuid>fa620ae4-ea86-454b-a8ab-d5520ac93dcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
