<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ActualizarDesdeDigiturno</name>
   <tag></tag>
   <elementGuidId>501e7282-5369-40ac-bab7-15d7eadfd487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_btnActualizarDesdeDigiturno']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_btnActualizarDesdeDigiturno</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3d141b1-9484-4615-b379-6d3f703e3151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2f16c3a8-ed7a-4b13-9da6-16dbc96f9af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$btnActualizarDesdeDigiturno</value>
      <webElementGuid>5cad2324-d22c-46e7-a39a-1754f19dc1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Actualizar desde Digiturno</value>
      <webElementGuid>952c8806-bf72-401b-aaff-81611a245703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_btnActualizarDesdeDigiturno</value>
      <webElementGuid>773ecce1-fbda-4305-ae2b-49a8abfb66b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton</value>
      <webElementGuid>cbc48466-7a7c-4080-86d1-0c30972e514a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_btnActualizarDesdeDigiturno&quot;)</value>
      <webElementGuid>eacbac70-0b57-4b83-bb9d-ed62d50e2c40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_btnActualizarDesdeDigiturno']</value>
      <webElementGuid>8439d54a-ef25-47e2-b59d-c00f0bdac478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_UpdatePanel1']/div/div/div[2]/div/table[3]/tbody/tr/td[3]/input</value>
      <webElementGuid>4315c10c-c666-467b-a0d6-3dfd9eae653f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>ecada9aa-dee7-4651-8c18-c1ecb9ad01b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder2$btnActualizarDesdeDigiturno' and @id = 'ctl00_ContentPlaceHolder2_btnActualizarDesdeDigiturno']</value>
      <webElementGuid>fb1ddc19-fbea-4ff1-b8de-e0e2e69bab90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
