<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Activo</name>
   <tag></tag>
   <elementGuidId>ae903e93-fd53-431b-bb11-59d497431778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ctl00_ContentPlaceHolder2_trEsActivoBloqueado']/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3ec210ad-5919-44d5-9dfc-442c7a6c3d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_chkEsActivo</value>
      <webElementGuid>5bfc7016-ff15-451f-9d76-483306821fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_trEsActivoBloqueado&quot;)/td[2]/span[1]/label[1]</value>
      <webElementGuid>79d0a052-6538-42bc-8b2a-ebf748229aea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ContentPlaceHolder2_trEsActivoBloqueado']/td[2]/span/label</value>
      <webElementGuid>20e260b6-32fb-4921-8269-38238801d11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>7dc88295-213f-4d9b-9f46-ff4ab625b2d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
