<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descripcion</name>
   <tag></tag>
   <elementGuidId>20516683-a0ac-44a3-9dad-1215573d6a8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Descripcion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Descripcion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fc7c2d2-ef5a-415e-8df8-05da0dbec20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl02$ctl02$FilterTextBox_Descripcion</value>
      <webElementGuid>986caa2b-521d-42e4-b662-a724b44a0922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>baf7270b-0679-4402-8036-4f50fab9069c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2b50b2d0-bafb-4f75-b328-5dffbbf3f2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Descripcion</value>
      <webElementGuid>0236f76d-ed16-4d52-92db-c0615b0354e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rgFilterBox</value>
      <webElementGuid>456b2877-2cb5-41a9-9297-a9dba189a925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Filter Descripcion column</value>
      <webElementGuid>5e2e51a2-2dc3-4959-960c-da4df610c9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if((event.keyCode == 13)) return false;</value>
      <webElementGuid>4a58f757-02d2-44f9-bd53-5c53eb2b7909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0fa69b21-2cdf-40d0-bb0e-6fef9f7a1322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Descripcion&quot;)</value>
      <webElementGuid>386bc624-cbd8-4cdc-a575-e5124b695ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Descripcion']</value>
      <webElementGuid>36210ce8-8d96-4d1d-ae81-4f1ccd4879d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00']/thead/tr[2]/td[4]/input</value>
      <webElementGuid>757f8c29-57f7-4fdb-9f77-59e4be949fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>2fb20dd3-08f0-4110-bde3-a70bd9a362bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl02$ctl02$FilterTextBox_Descripcion' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Descripcion' and @alt = 'Filter Descripcion column']</value>
      <webElementGuid>67e35b1b-f904-4a61-84e2-146dbcbf654d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
