<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Descendente</name>
   <tag></tag>
   <elementGuidId>5a989184-27a1-483a-bc51-d61fed2ee1d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divFiltrosCitas']/div[10]/div[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e149db0d-d0d4-4955-8929-15f19d8d8716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_rbtOrdenFechaDesc</value>
      <webElementGuid>59c99069-5bbb-4519-ad7b-1184589a35c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descendente</value>
      <webElementGuid>fc7c84ff-8514-4fda-b0c6-d27c010334ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divFiltrosCitas&quot;)/div[@class=&quot;input-group&quot;]/div[@class=&quot;divFechaOrden&quot;]/span[1]/label[1]</value>
      <webElementGuid>86db603a-7529-4e1a-bcad-d8a572287a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divFiltrosCitas']/div[10]/div[2]/span/label</value>
      <webElementGuid>66bda662-f304-4201-8edd-5ac14a3ab1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ascendente'])[1]/following::label[1]</value>
      <webElementGuid>42398e79-6494-4c99-a56e-ac5dc3ac15b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::label[2]</value>
      <webElementGuid>aee47114-cfd4-4c82-bf4e-63235e0513c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha y hora'])[1]/preceding::label[1]</value>
      <webElementGuid>417f151a-25a3-4dc2-bfc8-2571e6be28c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Punto de contacto'])[1]/preceding::label[1]</value>
      <webElementGuid>384fb9cf-63b2-4743-ba5b-d5a867dfecd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Descendente']/parent::*</value>
      <webElementGuid>93cfa02d-2ca7-4731-a61a-12e4dfe657ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/label</value>
      <webElementGuid>d7b6b864-0ae0-4112-b418-a214343cface</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Descendente' or . = 'Descendente')]</value>
      <webElementGuid>35e1e781-06fe-437f-99e4-357fd2bb234b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
