<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Ascendente</name>
   <tag></tag>
   <elementGuidId>bb14adab-aa18-46f4-85ae-68681775a425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divFiltrosCitas']/div[10]/div/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.divFechaOrden > span > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5e12276c-92d9-46c0-84c4-cd73fbfdc02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_rbtOrdenFechaAsc</value>
      <webElementGuid>65f24933-6ad2-46ae-bb8e-6a623f15ef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ascendente</value>
      <webElementGuid>abaab427-cc6a-4809-9a2a-3520f1bc7ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divFiltrosCitas&quot;)/div[@class=&quot;input-group&quot;]/div[@class=&quot;divFechaOrden&quot;]/span[1]/label[1]</value>
      <webElementGuid>5eaa76d6-ac53-44fa-91ca-23d63424d186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divFiltrosCitas']/div[10]/div/span/label</value>
      <webElementGuid>6b673d31-650e-4552-8d21-e80af03ebb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::label[1]</value>
      <webElementGuid>4f81aa0e-21cd-4b06-a408-ca744dbca71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V'])[2]/following::label[1]</value>
      <webElementGuid>1eff737b-44a9-4120-85b5-d73c945da4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descendente'])[1]/preceding::label[1]</value>
      <webElementGuid>f4f9f472-2b1f-408b-84d1-b78cdfa718c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha y hora'])[1]/preceding::label[2]</value>
      <webElementGuid>67768ad5-6a36-4f82-b88a-ed353a35760f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ascendente']/parent::*</value>
      <webElementGuid>19d12c43-2c5c-425b-9dcc-8c3caed066f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/span/label</value>
      <webElementGuid>73792c5a-21b9-4c5c-b5fa-9ac34ea5897e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Ascendente' or . = 'Ascendente')]</value>
      <webElementGuid>d731a647-ba66-4618-aadf-b8275973853a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
