<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_1</name>
   <tag></tag>
   <elementGuidId>cb9d837f-edae-4643-b3ff-5af9256a3a0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvHistoricoCitas']/tbody/tr[2]/td[12]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.chkGrilla > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>56ec9346-bfcf-4a80-97df-896d7636f7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvHistoricoCitas_ctl02_chkSeleccionEliminar</value>
      <webElementGuid>b6149e0e-3452-431c-b2d3-ad8731eb24a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvHistoricoCitas&quot;)/tbody[1]/tr[2]/td[12]/span[@class=&quot;chkGrilla&quot;]/label[1]</value>
      <webElementGuid>8bf4480a-66f3-4356-a0cb-2e5881d4742a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvHistoricoCitas']/tbody/tr[2]/td[12]/span/label</value>
      <webElementGuid>b1ff4285-a897-4bf0-aacd-639cb170be28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>a2365953-9a6d-429d-9378-f0b5378a89aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
