<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_UP MM Fin</name>
   <tag></tag>
   <elementGuidId>1652530d-833b-4f81-af5a-c3ab0ab0536d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bUp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bUp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5389ec37-18ba-4ca4-b90f-92d5797c17ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91878dd6-a842-49e8-8733-a935bb229c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bUp</value>
      <webElementGuid>6f6327ce-5844-4ac3-a520-9bad31358849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▲</value>
      <webElementGuid>330fb1ec-1c4b-4ad1-8c63-d488d476f832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bUp&quot;)</value>
      <webElementGuid>b39f710c-3020-4273-97af-e0c826d8884f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bUp']</value>
      <webElementGuid>a647df34-2feb-477f-b1e0-3163199b1757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCreacionMotivoLast']/tbody/tr[2]/td[2]/div/div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>f46bcdb6-f6e1-452d-88ae-f8c23e8ad330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>d9ae6548-4855-4360-a9c6-5c3cf19d1b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bUp']</value>
      <webElementGuid>d6f3f7aa-b37a-4197-a527-1dc80080be9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
