<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DOWN HH Fin</name>
   <tag></tag>
   <elementGuidId>22a6f864-5270-4a89-b2de-2c44a172731c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtHora_bDown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtHora_bDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1be97472-8305-42f3-b4fd-fcdb29e767d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c8796f9c-fcbf-490d-a8d4-11628428980f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtHora_bDown</value>
      <webElementGuid>76f39c18-b891-4f36-aa4c-9716615e3bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>7618c8c4-917a-43bd-84d5-4be88d1b97eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtHora_bDown&quot;)</value>
      <webElementGuid>60dfcb0a-f476-450b-b5f8-79de29c6dc38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtHora_bDown']</value>
      <webElementGuid>4a9ec596-7364-457f-8e12-413d225e4c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCreacionMotivoLast']/tbody/tr[2]/td[2]/div/div/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>35491f01-b199-4fbf-9f54-9ef7e0e4172b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>575e07bc-efdf-4905-aa34-446caef71576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtHora_bDown']</value>
      <webElementGuid>64dc99c1-7f27-4ead-8d37-b59f387642ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
