<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DOWN MM Inicio</name>
   <tag></tag>
   <elementGuidId>99ea2ab9-c183-4ac9-9bc5-e283843ef025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_mcMotivos_tspHoraInicio_txtMinuto_bDown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_mcMotivos_tspHoraInicio_txtMinuto_bDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b26db04f-5428-41e4-aef2-41c882b96426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12160a3c-d98c-4cf2-9b6c-10ec1a08eb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_mcMotivos_tspHoraInicio_txtMinuto_bDown</value>
      <webElementGuid>63392de3-c10c-4d8a-acdc-20207b75af90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>88149c31-7191-42c5-b070-07cadd31c5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_mcMotivos_tspHoraInicio_txtMinuto_bDown&quot;)</value>
      <webElementGuid>b0badea6-2326-412a-806f-0415e9e108c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_mcMotivos_tspHoraInicio_txtMinuto_bDown']</value>
      <webElementGuid>25bdf10f-f9b2-40de-ac09-485493dfeaec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCreacionMotivoLast']/tbody/tr/td[2]/div/div[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>7a6ab15d-9650-498d-9998-8fd58f4a1b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>ad6ba94e-94da-46fe-9377-efb1993dfd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_mcMotivos_tspHoraInicio_txtMinuto_bDown']</value>
      <webElementGuid>e2470b8c-6b77-4435-b483-0c6bf601424c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
