<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DOWN MM Fin</name>
   <tag></tag>
   <elementGuidId>3a7c9f6c-9301-4ead-8ca3-2c38805f19b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bDown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>052a5fcf-f7ae-44e3-a6e6-85da07a68b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>936345e8-3900-449b-8403-ec937cd26a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bDown</value>
      <webElementGuid>0a1175e4-3870-4c0b-af95-0b8fe4771efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>09bf33a1-e41a-42b0-a3d3-b237ff75866b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bDown&quot;)</value>
      <webElementGuid>77ef3693-7bbd-407a-a932-7e0d12cd9073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bDown']</value>
      <webElementGuid>1d2e598c-4116-4ddd-9b26-8daa46155681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCreacionMotivoLast']/tbody/tr[2]/td[2]/div/div[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>34d9b2a9-3d0c-4a5c-8510-bb3e42a35e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>b48190ae-5d19-4001-a8f7-68faf1cf44bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_mcMotivos_tspHoraFin_txtMinuto_bDown']</value>
      <webElementGuid>9d13409f-ceb1-4b41-a4d5-7e1b2afceeb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
