<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Modo HTML Requisitos</name>
   <tag></tag>
   <elementGuidId>7a4973d2-663e-4162-9a85-b259dd37bb73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_ContentPlaceHolder2_edtRequisitos_ctl03_ctl01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtRequisitos_ctl03_ctl01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e504983b-3d47-4685-b628-f153dbcd9cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/WebResource.axd?d=v2hrE9eVdmltFqW5yiNif4lPMGg_tdAQL3a6A1k8GLDBSJjCMca5z-ZUERzdJyDrYk649ocI6tyek4aGo71hfF260Ukt9hZoBTljxh6R25HcJpdr2KDHYdrD62uc6Du0gj1qTshffYrtNALIkDrFPLV0HOo1&amp;t=637866756480000000</value>
      <webElementGuid>9a993f92-3ee9-4b86-a780-e3b0c79176f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtRequisitos_ctl03_ctl01</value>
      <webElementGuid>4e90bed0-6a2f-4002-8d40-b91cf7146c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>HTML text</value>
      <webElementGuid>fd8e7100-d91b-45fe-8ab4-b594f053bbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_toolbar_button ajax__htmleditor_toolbar_button_hover</value>
      <webElementGuid>ce92b23a-008c-40cf-8d0a-6c7e1528d032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtRequisitos_ctl03_ctl01&quot;)</value>
      <webElementGuid>0b44274a-426f-4e9a-9a2d-e040b3cccf55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_ContentPlaceHolder2_edtRequisitos_ctl03_ctl01']</value>
      <webElementGuid>9e61de84-ee86-4f77-ae52-ac55743aa11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtRequisitos_ctl03']/img[2]</value>
      <webElementGuid>88ab6417-469a-4b28-a856-815d036729bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='HTML text']</value>
      <webElementGuid>50239333-32ee-46fc-be0f-cc5b6329bf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/img[2]</value>
      <webElementGuid>c3edd3fd-39fd-42d6-b7e4-0c17bcdec7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/WebResource.axd?d=v2hrE9eVdmltFqW5yiNif4lPMGg_tdAQL3a6A1k8GLDBSJjCMca5z-ZUERzdJyDrYk649ocI6tyek4aGo71hfF260Ukt9hZoBTljxh6R25HcJpdr2KDHYdrD62uc6Du0gj1qTshffYrtNALIkDrFPLV0HOo1&amp;t=637866756480000000' and @id = 'ctl00_ContentPlaceHolder2_edtRequisitos_ctl03_ctl01' and @title = 'HTML text']</value>
      <webElementGuid>f469c315-6d99-4223-bbd9-823ca53c1256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
