<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Modo HTML Descripcion</name>
   <tag></tag>
   <elementGuidId>baed89f0-d58b-494b-89bf-b94f8c405e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_ContentPlaceHolder2_edtDescripcion_ctl03_ctl01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtDescripcion_ctl03_ctl01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4e62bba3-c81d-4a02-8bdd-05138c72f8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/WebResource.axd?d=v2hrE9eVdmltFqW5yiNif4lPMGg_tdAQL3a6A1k8GLDBSJjCMca5z-ZUERzdJyDrYk649ocI6tyek4aGo71hfF260Ukt9hZoBTljxh6R25HcJpdr2KDHYdrD62uc6Du0gj1qTshffYrtNALIkDrFPLV0HOo1&amp;t=637866756480000000</value>
      <webElementGuid>a662e08d-18ee-4aae-9115-572c23ee45e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtDescripcion_ctl03_ctl01</value>
      <webElementGuid>e5b43db8-cb81-41a6-bf18-127baa834c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>HTML text</value>
      <webElementGuid>f586dd39-d91b-49d6-80f4-ea29b75efc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_toolbar_button ajax__htmleditor_toolbar_button_hover</value>
      <webElementGuid>668030f8-9d4a-4daf-8cf9-0753a81578b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtDescripcion_ctl03_ctl01&quot;)</value>
      <webElementGuid>bfd555da-6605-4cf6-81c2-70133c0dc902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_ContentPlaceHolder2_edtDescripcion_ctl03_ctl01']</value>
      <webElementGuid>c9c8460c-4d5e-43e3-a8f7-d4598201c6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtDescripcion_ctl03']/img[2]</value>
      <webElementGuid>00ab6120-1c55-43a8-bbdb-b5f59ec379fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='HTML text'])[2]</value>
      <webElementGuid>3dd2efde-1a4e-4979-b178-cb163e43ba3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/table/tbody/tr[3]/td/div/img[2]</value>
      <webElementGuid>14cf5950-1a2b-4d50-9b95-7b503c09e8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/WebResource.axd?d=v2hrE9eVdmltFqW5yiNif4lPMGg_tdAQL3a6A1k8GLDBSJjCMca5z-ZUERzdJyDrYk649ocI6tyek4aGo71hfF260Ukt9hZoBTljxh6R25HcJpdr2KDHYdrD62uc6Du0gj1qTshffYrtNALIkDrFPLV0HOo1&amp;t=637866756480000000' and @id = 'ctl00_ContentPlaceHolder2_edtDescripcion_ctl03_ctl01' and @title = 'HTML text']</value>
      <webElementGuid>ca1ffbf5-d708-40d7-9959-ffd73786f5e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
