<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Tipo especialidad</name>
   <tag></tag>
   <elementGuidId>918774be-a3b6-492c-b39e-8206000878ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_ContentPlaceHolder2_ddlTiposEspecialidad']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_ddlTiposEspecialidad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1b13ab90-3ce5-462c-bbac-77bff5eb8c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$ddlTiposEspecialidad</value>
      <webElementGuid>a3a2d7da-c0da-4d51-9993-3942fa6d7a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ddlTiposEspecialidad</value>
      <webElementGuid>54b6f121-fc39-4933-8643-c06c06b83cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Presencial
		Virtual

	</value>
      <webElementGuid>1d90c97f-a8d6-4677-be08-336d0e554d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_ddlTiposEspecialidad&quot;)</value>
      <webElementGuid>51195c94-b939-4847-98ce-62f11682a9e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_ContentPlaceHolder2_ddlTiposEspecialidad']</value>
      <webElementGuid>e0aa51f4-7fc5-4230-ab81-a37263c68360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divRolEdit']/div/div[2]/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>468ca3aa-784c-46cb-91a1-bda11d90cca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo especialidad:'])[1]/following::select[1]</value>
      <webElementGuid>ef507c6b-0413-40fe-8e86-68fef6421599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>4d23d2da-c329-443e-9c61-bd063380d139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Está Activo:'])[1]/preceding::select[1]</value>
      <webElementGuid>bf981db8-e854-45f5-8282-8d87f101e3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista de Servicios'])[1]/preceding::select[1]</value>
      <webElementGuid>2b070eba-a876-465c-97d2-0e11e0b4fc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/select</value>
      <webElementGuid>e3f5eb6b-9d48-4a51-b2c4-32f39bfbed15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder2$ddlTiposEspecialidad' and @id = 'ctl00_ContentPlaceHolder2_ddlTiposEspecialidad' and (text() = '
		Presencial
		Virtual

	' or . = '
		Presencial
		Virtual

	')]</value>
      <webElementGuid>c152810a-7c9f-42db-88a8-e42bf71b7607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
