<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Diseno Requisitos</name>
   <tag></tag>
   <elementGuidId>63954e1e-578c-4203-b508-233c3c1dff33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_ContentPlaceHolder2_edtRequisitos_ctl02_ctl01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtRequisitos_ctl02_ctl01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d4edc8a2-30db-423e-a4ae-515949a7e72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtRequisitos_ctl02_ctl01</value>
      <webElementGuid>ba925d9c-330f-4ea8-9e20-d09af750c865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_htmlpanel_default</value>
      <webElementGuid>7f6abcf0-e5c2-475c-999d-9a37563d87f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtRequisitos_ctl02_ctl01&quot;)</value>
      <webElementGuid>0d130c40-1e22-44f4-b3a3-11280fea34f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_ContentPlaceHolder2_edtRequisitos_ctl02_ctl01']</value>
      <webElementGuid>08572e6f-1dcc-42b6-ac05-734de6f5fab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtRequisitos_ctl02']/textarea</value>
      <webElementGuid>d795e46b-cd37-4e5c-8207-84f2b9174488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4b8cc907-c163-4058-a0d7-ae208f9c5720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ctl00_ContentPlaceHolder2_edtRequisitos_ctl02_ctl01']</value>
      <webElementGuid>2d304dbc-c5a1-4b22-bea3-995005e3902d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
