<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Editar 1</name>
   <tag></tag>
   <elementGuidId>a8b29fb6-e616-4034-83b7-96548258dec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl04_btnEdit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl04_btnEdit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f10d7c04-d977-4ba0-b9b1-7345434468dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>75e3f948-d0f7-4d41-9627-d15a991d3d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl04$btnEdit</value>
      <webElementGuid>70256c45-752f-4252-93d4-9e634c85f3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl04_btnEdit</value>
      <webElementGuid>d7312fe7-d0a9-4321-8955-d4657542df61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Recursos/img/ico/editar.svg</value>
      <webElementGuid>737f3dee-1285-4b92-bfba-90b6d98a4b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>6fa74279-0ca0-48c9-9841-165f545ce849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl04$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmParametroEdit.aspx?ParametroId=811d8cdb-f62f-4d3b-a692-60da26c4f9d1&amp;Codigo=57&quot;, false, false))</value>
      <webElementGuid>55923470-b017-4266-a90b-363d1f263c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl04_btnEdit&quot;)</value>
      <webElementGuid>56fc66b3-1764-41e6-949a-cdb487f5314c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl04_btnEdit']</value>
      <webElementGuid>105090d0-5cc4-42da-a719-2cd011a9f8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00__0']/td/input</value>
      <webElementGuid>8dd9e534-898a-4b27-a75b-513c5b2c045b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td/input</value>
      <webElementGuid>772bb04e-5f18-43cc-a051-42c5cd2147ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl04$btnEdit' and @id = 'ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl04_btnEdit' and @src = '../../../Recursos/img/ico/editar.svg']</value>
      <webElementGuid>db37ad7f-0487-4d93-800b-edc1f8888775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
