<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Hora Fin MM UP</name>
   <tag></tag>
   <elementGuidId>0caa3cb1-6f93-444e-bede-fa42078b2db0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtMinuto_bUp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtMinuto_bUp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee384bde-e23b-4799-910a-25560ba8ab06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50721f52-7021-48f7-b9ba-c919fe77436f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtMinuto_bUp</value>
      <webElementGuid>23cdb6f5-90d3-4c11-a4d0-5b22abac0b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▲</value>
      <webElementGuid>2d4779b9-6012-402e-aa1e-9e5a6c7ea75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtMinuto_bUp&quot;)</value>
      <webElementGuid>83e1c921-76f9-43a3-80b5-b76d0b3c9c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtMinuto_bUp']</value>
      <webElementGuid>d101e0ba-f33b-4c12-81d6-174d81a772ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCreacionMotivoLast']/tbody/tr[2]/td[2]/div/div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>577286e4-c68c-4d69-bf92-e0f7a5fbb7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>5d8ee423-d381-4e68-9486-f83d48ee0d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtMinuto_bUp']</value>
      <webElementGuid>6246e949-0146-4fb5-82dc-76402ac28e54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
