<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Hora Fin HH UP</name>
   <tag></tag>
   <elementGuidId>4efb4cd3-f668-4d98-8d74-5f92ed9c23e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bUp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bUp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>206b3b4c-ab5f-4126-aa68-61416b30c1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ef6661d-b6b6-49ec-96ad-42a0d134112a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bUp</value>
      <webElementGuid>70f3dfa1-8b29-4511-a9b5-a7b09802703d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▲</value>
      <webElementGuid>96ea0a28-01c8-43e7-ab1c-d5dc448d8a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bUp&quot;)</value>
      <webElementGuid>64ff2743-b411-42fa-a72f-2735dfda5519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bUp']</value>
      <webElementGuid>e4366b9f-b591-4d38-9680-5b13db4cd3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCreacionMotivoLast']/tbody/tr[2]/td[2]/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>1aad9fcf-3d55-4ae9-bd55-233363317670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>314c5861-c1a0-426f-bc92-9dd5d46180dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bUp']</value>
      <webElementGuid>aabd89e9-4eb0-4ecd-a77a-c8efa2d43cdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
