<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Hora Inicio HH Down</name>
   <tag></tag>
   <elementGuidId>dddbed72-6ac9-4064-a851-071a7b9761ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraInicio_txtHora_bDown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraInicio_txtHora_bDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>236c16c5-e49e-4717-9f94-1edddd698bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee8a1ae3-f290-407a-bfe9-e5babf1f19e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraInicio_txtHora_bDown</value>
      <webElementGuid>795bcd71-cae7-4af3-a69c-cd602b9d4b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>8b8d2de5-600d-4ae4-8644-b6685ecfbcbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraInicio_txtHora_bDown&quot;)</value>
      <webElementGuid>254d417d-985c-4de2-bd88-5382934f0b27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraInicio_txtHora_bDown']</value>
      <webElementGuid>2d7bac65-db3d-4cfa-92cc-a49436034930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCreacionMotivoLast']/tbody/tr/td[2]/div/div/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>c5e0f229-a2d6-4d61-bb39-920d064751c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/div/div/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>fb61eedc-57f9-4143-9367-3d371d836e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraInicio_txtHora_bDown']</value>
      <webElementGuid>cc9c6151-d293-4d7f-bfc4-9086ee88cb48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
