<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Hora Fin HH Down</name>
   <tag></tag>
   <elementGuidId>17333894-86f8-4c49-8cdd-4a38fb9a2219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bDown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a440e11c-9813-4b10-8d3a-8f6f47aa0bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e61a7ace-7d8e-4423-aba0-5984bab71af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bDown</value>
      <webElementGuid>dc95b61c-5f51-48e5-9628-70d1196ea823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>90dc9f00-2561-4270-97d1-ac6859dd5e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bDown&quot;)</value>
      <webElementGuid>8109f4eb-18ad-483d-b74c-e87eb04b1c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bDown']</value>
      <webElementGuid>54c5d0e5-76cb-42a8-9d6c-cde62b7d8063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCreacionMotivoLast']/tbody/tr[2]/td[2]/div/div/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>b0e42ea0-55d7-40d1-abdb-9c0ccef58e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>324128a8-5900-41e9-8478-c3388b254697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_ucMotivosXOficina_tspHoraFin_txtHora_bDown']</value>
      <webElementGuid>676b79bd-828c-4fb3-b3a3-c17a99b13aa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
