<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Descripcion</name>
   <tag></tag>
   <elementGuidId>3b7be758-57f2-4fde-b011-be3c345d7f25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_ContentPlaceHolder2_ucMotivosXOficina_txtDescripcion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_ucMotivosXOficina_txtDescripcion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>be48bf14-591e-4361-b9e7-6a7c853a09c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$ucMotivosXOficina$txtDescripcion</value>
      <webElementGuid>0044888e-7a2b-4cf5-b4e4-461de5e581c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>889e4f01-a98b-4cf3-bdc9-7585051f9cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3fc3d8f3-bbfd-4851-b108-57e9bac4266c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>c9a165dd-5d3a-42d1-be19-cfdd0b13266d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ucMotivosXOficina_txtDescripcion</value>
      <webElementGuid>8966d592-729b-463f-9226-dad17d1cbb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fin de Jornada</value>
      <webElementGuid>30a153e3-b816-44ab-bbfa-fd3a40ae831b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_ucMotivosXOficina_txtDescripcion&quot;)</value>
      <webElementGuid>1907c0ed-03d3-4f73-a66c-44a11ba2598e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_ContentPlaceHolder2_ucMotivosXOficina_txtDescripcion']</value>
      <webElementGuid>a6330ab4-a98e-47b0-8028-908032123d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCreacionMotivoFirst']/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>a305d0ea-9100-470c-b816-3ffeadd54656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción:'])[1]/following::textarea[1]</value>
      <webElementGuid>9c06b980-e8e9-4b96-8fc1-b93082959c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Id Motivo:'])[1]/following::textarea[1]</value>
      <webElementGuid>387d1382-bcf7-43b0-9b16-ca6420948a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/preceding::textarea[1]</value>
      <webElementGuid>453c2094-ddfd-4795-a882-5405aadade7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hora Inicio:'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e612a2fe-55b6-4151-8101-6941d5a85e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fin de Jornada']/parent::*</value>
      <webElementGuid>2ca96a54-6e3f-451c-91d8-4b33421e5262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6905c117-2599-4361-af92-b37f825b49a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$ContentPlaceHolder2$ucMotivosXOficina$txtDescripcion' and @id = 'ctl00_ContentPlaceHolder2_ucMotivosXOficina_txtDescripcion' and (text() = 'Fin de Jornada' or . = 'Fin de Jornada')]</value>
      <webElementGuid>6f3d82a1-4974-469d-93e3-43d37c8392dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
