<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_Filtro</name>
   <tag></tag>
   <elementGuidId>8f871213-2720-4961-acb4-f39c245d82cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_Filter_Nombre']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.t-font-icon.rgIcon.rgFilterIcon.rgFilterActive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ac1a9199-218a-452f-9733-a2a41c03325e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-font-icon rgIcon rgFilterIcon rgFilterActive</value>
      <webElementGuid>17a70076-4d0d-47e4-af21-a15bf124f7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_Filter_Nombre&quot;)/span[@class=&quot;t-font-icon rgIcon rgFilterIcon rgFilterActive&quot;]</value>
      <webElementGuid>37ec2220-857c-481d-829e-cb9785dd0d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_Filter_Nombre']/span</value>
      <webElementGuid>4da7975e-f58b-41dd-a560-0c141e12e449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/button/span</value>
      <webElementGuid>22e63cba-42fb-400c-8e88-2b097ba29993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
