<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre</name>
   <tag></tag>
   <elementGuidId>8c029b4d-fe3d-4c46-bdb4-23e09769a4a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Nombre']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Nombre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0be05096-d398-46e5-9b22-fb80d68b7349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl02$ctl02$FilterTextBox_Nombre</value>
      <webElementGuid>5342e0ad-3809-4e6d-ba3f-e08e503b9c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5eeb5e49-034e-48d9-88b1-a9ff0e261d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9b4c6bff-7422-4f33-be09-d59a90ad4bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Nombre</value>
      <webElementGuid>d24e5bba-ad74-4e2d-8c25-b7b5ff7046a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rgFilterBox</value>
      <webElementGuid>35b7a078-12b8-4a04-9989-4d96f9cc5000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Filter Nombre column</value>
      <webElementGuid>a28161a5-7ca3-4042-84f3-baac12b795dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if((event.keyCode == 13)) return false;</value>
      <webElementGuid>ca689942-b739-4f58-9fe3-a68a56dcb399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>94d0c3b7-9a52-48d0-ba1a-44cd7ce1d9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Nombre&quot;)</value>
      <webElementGuid>762bd770-28b8-4ebb-984e-e7e3ec538ee8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Nombre']</value>
      <webElementGuid>97e04f7e-0638-400c-9f3d-d225df5d4db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00']/thead/tr[2]/td[2]/input</value>
      <webElementGuid>ce7d8b16-83e1-4cd4-a2df-52199c9cc9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//thead/tr[2]/td[2]/input</value>
      <webElementGuid>c26034c4-301e-4341-8997-f8032d92d43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl02$ctl02$FilterTextBox_Nombre' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Nombre' and @alt = 'Filter Nombre column']</value>
      <webElementGuid>d681a719-1ada-4611-8207-bada79d10a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
