<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Reservadas a disponible</name>
   <tag></tag>
   <elementGuidId>eaa8de44-4fa4-48f6-8c42-41f934d4d9a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c7d9d46-39dc-417f-a7bd-9bc7bb77a034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>53431709-c809-4d85-bcae-d2e87f759f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$btnHabilitarCitasReservadas</value>
      <webElementGuid>2cc094c1-5848-4973-bb6b-0b6da422495d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Reservadas a disponible</value>
      <webElementGuid>5f340ce9-1f4f-4c54-9a87-eeece7374cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Se habilitarán todas las agendas reservadas de los registros seleccionados. \n¿Está seguro de realizar la acción?');WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$btnHabilitarCitasReservadas&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>d5fde2bb-4cdf-43fc-8f80-780da91854fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas</value>
      <webElementGuid>a0af964f-c968-45f3-ad56-f61bc8e57385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>botonIcono btnCambio btnCambio3</value>
      <webElementGuid>e4e3ec69-5c2a-447e-bba3-96e833ab34ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas&quot;)</value>
      <webElementGuid>9e691147-63ca-4f12-88cb-109b1edcbf82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas']</value>
      <webElementGuid>68786b9d-a839-49ed-8ce3-352d3a1b7b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_divDetalleAgendaXOficina']/div[2]/div/div[2]/div/input[3]</value>
      <webElementGuid>123a2e23-cbeb-45ba-84c8-5c31bc0e9844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[3]</value>
      <webElementGuid>3d31e5cd-578b-40ac-8b1e-696c0f6e16f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder2$btnHabilitarCitasReservadas' and @id = 'ctl00_ContentPlaceHolder2_btnHabilitarCitasReservadas']</value>
      <webElementGuid>f5fd9c57-1fa0-4b59-a05d-300d5aeb9568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
