<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1 Cerrado_Borrar</name>
   <tag></tag>
   <elementGuidId>76b50868-6757-4fda-a6e1-36b1933a5ae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_grvMotivosCancelacion_ctl02_btnBorrar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_grvMotivosCancelacion_ctl02_btnBorrar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88b9db82-0c86-4fe3-b317-f5c6ce814b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('¿Desea eliminar el motivo de cancelación?');</value>
      <webElementGuid>032adf29-d258-4f12-9ac2-4ca8da682a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grvMotivosCancelacion_ctl02_btnBorrar</value>
      <webElementGuid>610276bb-63ed-4895-847e-60298d936991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnBorrarImg</value>
      <webElementGuid>a267accf-8ec1-4708-ac59-9d9418717160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder2$grvMotivosCancelacion$ctl02$btnBorrar','')</value>
      <webElementGuid>0451926c-6bdb-4cd4-a57f-ed5ff1345458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvMotivosCancelacion_ctl02_btnBorrar&quot;)</value>
      <webElementGuid>6be70379-d353-42e5-904d-e925622c36b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_grvMotivosCancelacion_ctl02_btnBorrar']</value>
      <webElementGuid>d2898ab4-93a7-4840-a857-88323f66750f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvMotivosCancelacion']/tbody/tr[2]/td[4]/div/a[2]</value>
      <webElementGuid>bbc6a2f9-e7a4-4e6b-aaf1-eb5be5b5eae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder2$grvMotivosCancelacion$ctl02$btnBorrar','')&quot;)]</value>
      <webElementGuid>34be3fbd-d73c-464f-b9ea-5b3d85d4f3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/a[2]</value>
      <webElementGuid>aaafe44a-625e-42d5-b7ca-2b1cc9cd1780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_grvMotivosCancelacion_ctl02_btnBorrar' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder2$grvMotivosCancelacion$ctl02$btnBorrar&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;)]</value>
      <webElementGuid>06a0485d-da88-4293-81a4-11191b3d001e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
