<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Codigo Regional</name>
   <tag></tag>
   <elementGuidId>d18dd315-c133-4874-8e02-f973fbf18fd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_txtEditCodigoRegional']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_txtEditCodigoRegional</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>636aa7a5-e26f-4112-8d14-1944499faa0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$txtEditCodigoRegional</value>
      <webElementGuid>6271a40a-a9a6-4e4d-ab34-637e8e262218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5b5dc34-7166-4da2-9527-eb36b5da13f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_txtEditCodigoRegional</value>
      <webElementGuid>d0ae8b84-da9b-42aa-af9c-33e4cfb0bc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_txtEditCodigoRegional&quot;)</value>
      <webElementGuid>60e2f389-9475-4778-9e07-a0ede47b7422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_txtEditCodigoRegional']</value>
      <webElementGuid>0758c9fa-24e4-43c5-9b48-3b00174491e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_upRegional']/table/tbody/tr/td[2]/input[2]</value>
      <webElementGuid>9637e9f6-b809-4cd9-95ba-58d77abefcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>e3f9ae75-3864-4d96-b44e-e48fa6d93f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$txtEditCodigoRegional' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_txtEditCodigoRegional']</value>
      <webElementGuid>ef2dc43f-bba0-414e-854b-71b3eb0cf79c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
