<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Cancelar</name>
   <tag></tag>
   <elementGuidId>735f5e75-e50a-43b7-833e-ee0a117e0dff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_CancelarButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_CancelarButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d98215d-2ace-4f08-b5fa-5a35035fb70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>68eb9531-233d-454a-bbfa-1510842d13ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$PasswordRecovery1$UserNameContainerID$CancelarButton</value>
      <webElementGuid>9abf3716-2b7c-43f7-8116-100636e27dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>8bb502cb-1fe2-4eb4-9716-a7dbb6038cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_CancelarButton</value>
      <webElementGuid>db7ddbb8-ec60-4b0b-9994-5cf87bd813ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton</value>
      <webElementGuid>1dbc6717-9616-4f96-b6ce-32d8e66708bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_CancelarButton&quot;)</value>
      <webElementGuid>7ade83ad-f068-483b-8733-d606c91f51c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_CancelarButton']</value>
      <webElementGuid>208a895e-e33c-4e05-b317-9652b7ff631e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_PasswordRecovery1']/tbody/tr/td/div/div[2]/table/tbody/tr[4]/td/input</value>
      <webElementGuid>6e462b51-a9eb-4140-af02-ab3c1d463212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>6dd7619c-171b-4895-b719-f7258896bbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder2$PasswordRecovery1$UserNameContainerID$CancelarButton' and @id = 'ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_CancelarButton']</value>
      <webElementGuid>91713f08-b042-4aae-8370-c34f4a1ac3d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
