<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre de usuario o funcionario</name>
   <tag></tag>
   <elementGuidId>7ebcbaef-a25a-4fea-be05-6a75c4ef570d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_UserName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_UserName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d74dd7a-4c52-472b-8cc6-166861de75ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$PasswordRecovery1$UserNameContainerID$UserName</value>
      <webElementGuid>e9abda5c-07b8-42e8-9e13-e12ee2f63a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b6f73c2-4a81-42f0-9108-ab29e87a7c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_UserName</value>
      <webElementGuid>1b26e8ce-81d3-4894-9636-0b86a6daee56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5a1407a5-0644-4496-a349-93d1d430d272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_UserName&quot;)</value>
      <webElementGuid>0b64acbb-26d5-42a2-b350-47367b3bd65b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_UserName']</value>
      <webElementGuid>0c928dde-2281-45e8-b4f2-09e4cae358f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_PasswordRecovery1']/tbody/tr/td/div/div[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>612aba91-6ebc-448a-a39a-6dd9ae4b1783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>26a0e3ef-91ae-449e-aed4-71e051148336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$PasswordRecovery1$UserNameContainerID$UserName' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_PasswordRecovery1_UserNameContainerID_UserName']</value>
      <webElementGuid>caf106d4-f41e-4dbf-af52-22efc846bb98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
