<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID oficina</name>
   <tag></tag>
   <elementGuidId>e469dfae-9e86-442c-8536-72137e247d98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_txtEditIdOficina']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_txtEditIdOficina</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a737f79-751b-4f0b-aeb6-65da43cd68ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$txtEditIdOficina</value>
      <webElementGuid>d0c1ad0d-2629-40a9-a662-9d2c91908c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ad1e0ce-ae3b-47b5-86eb-17f98e399d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_txtEditIdOficina</value>
      <webElementGuid>4f0ce843-43c4-4f11-a9be-aabdf6e70fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_txtEditIdOficina&quot;)</value>
      <webElementGuid>43ecd13d-ab29-4794-beb5-d314fb75ae03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_txtEditIdOficina']</value>
      <webElementGuid>a872e338-66a5-44e0-9fcc-32681b59026c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_divOficina']/div/div/div/div[2]/fieldset[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>3ca5540a-c3af-466c-86e3-3f534ca9ad21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>e79886a1-84a5-4b5f-9e95-6dfbf7cc1481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$txtEditIdOficina' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_txtEditIdOficina']</value>
      <webElementGuid>d5e2a7f3-b44d-48bf-aed6-2116dc9bf7e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
