<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Latitud</name>
   <tag></tag>
   <elementGuidId>2385cbee-4548-471f-82b2-e414d5afa24b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_txtEditLatitud']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_txtEditLatitud</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce15c8b2-5b37-4fa7-9a01-286ef9cde98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$txtEditLatitud</value>
      <webElementGuid>c916ecc3-d207-4d12-a922-cd36dd75f67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58881d68-7dfb-4605-a9d4-9f88dba8b070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_txtEditLatitud</value>
      <webElementGuid>5abf8925-3e32-490a-b99b-c0b5d08a4ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_txtEditLatitud&quot;)</value>
      <webElementGuid>740d5361-ab8d-47fb-b68d-442a8f01d484</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_txtEditLatitud']</value>
      <webElementGuid>5b0cd673-bfde-42b9-9a7d-b3931aebbd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_divOficina']/div/div/div/div[2]/fieldset/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>a6b48fc3-d346-4f41-bd99-1a33f95a8117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>82019337-47da-4d83-9d82-4ab01dffa8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$txtEditLatitud' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_txtEditLatitud']</value>
      <webElementGuid>b2bd30b3-cb8f-4a71-bafa-8a1c535257b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
