<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Oficina Activa</name>
   <tag></tag>
   <elementGuidId>3a3244df-1fa9-44cf-b3b5-1bfe675cfbb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder2_upRegional']/table/tbody/tr[7]/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bf47b9b5-dd26-4ab1-b5fa-e6c808f1b7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_chkEditOficinaActiva</value>
      <webElementGuid>de2f70c8-2933-404f-9965-cf78f0ec657e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_upRegional&quot;)/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[7]/td[2]/span[1]/label[1]</value>
      <webElementGuid>15cf7d3c-dbc8-488e-9505-1658d286d39d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_upRegional']/table/tbody/tr[7]/td[2]/span/label</value>
      <webElementGuid>86661c7a-a781-4e41-97ee-fb87b7127bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>63f7b566-6cfb-43d2-b8b1-03683d219e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
