<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Ente del sistema</name>
   <tag></tag>
   <elementGuidId>28b34c52-3d8a-40ae-ac05-a7aed902b2dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_ContentPlaceHolder2_ddlEditEnte']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_ddlEditEnte</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>50427791-452f-42ec-a0a0-4f0a733623fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$ddlEditEnte</value>
      <webElementGuid>9cd6ed79-3367-4346-a034-84a585430754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$ContentPlaceHolder2$ddlEditEnte\',\'\')', 0)</value>
      <webElementGuid>ab7a2b88-6290-48fd-b62b-8977c42af240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ddlEditEnte</value>
      <webElementGuid>2d50ac79-de62-42c9-b11c-a7649355f57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Sala
	Grupo
	Servidor

</value>
      <webElementGuid>a4a17339-6f18-4964-9056-b1df073e1edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_ddlEditEnte&quot;)</value>
      <webElementGuid>be6c01b8-3a75-462c-a068-8921be0fd074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_ContentPlaceHolder2_ddlEditEnte']</value>
      <webElementGuid>77e105c9-bbf4-4030-bf01-bcf85e9a3ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_divOficina']/div/div/div/div[2]/fieldset[2]/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>8ea713d7-f984-4c16-8097-80ba245b9777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ente del sistema:'])[1]/following::select[1]</value>
      <webElementGuid>cfe3dbfd-8512-46d5-9a78-ac1f0f749b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID selector:'])[1]/following::select[1]</value>
      <webElementGuid>0ec654ae-dd7b-4293-a5f4-d304a489ea83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID destino:'])[1]/preceding::select[1]</value>
      <webElementGuid>bccb6ba3-cad1-46e2-821b-0a3e46f2749e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID cola:'])[1]/preceding::select[1]</value>
      <webElementGuid>ea2af4fb-ce5b-423e-b351-d8b974f9b5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>94f118b3-e6b2-43b2-a209-c071b4f3d7a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder2$ddlEditEnte' and @id = 'ctl00_ContentPlaceHolder2_ddlEditEnte' and (text() = '
	Sala
	Grupo
	Servidor

' or . = '
	Sala
	Grupo
	Servidor

')]</value>
      <webElementGuid>d3256730-1cc5-4b80-afab-3ddab2887522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
