<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td1_BaseDatosAgendamiento</name>
   <tag></tag>
   <elementGuidId>9857c026-968e-417c-be42-4c1929d7672f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_grvConsultorClientees']/tbody/tr[2]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.trClick > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fe683c45-608b-4b0b-a24b-99a9526dd3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>ff9b4dc5-2a51-4d93-8d4a-303fc38c8011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>50644762-451b-4b2e-b081-b3696faf8ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            BaseDatosAgendamiento
                                        </value>
      <webElementGuid>86adc748-71e5-465c-9771-35514f882e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvConsultorClientees&quot;)/tbody[1]/tr[@class=&quot;trClick&quot;]/td[1]</value>
      <webElementGuid>39486d24-29c6-4016-91aa-cf3e0d2caddd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvConsultorClientees']/tbody/tr[2]/td</value>
      <webElementGuid>673cd50b-53bd-479a-a7c6-7b777e6bb2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Habilitado'])[1]/following::td[1]</value>
      <webElementGuid>28d01e26-1315-47e5-bb69-dd653c3334d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orden'])[1]/following::td[1]</value>
      <webElementGuid>559b514f-dec0-43af-916a-e3bd692ece88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El usuario va ser consultado por la base de agendamiento'])[1]/preceding::td[1]</value>
      <webElementGuid>4fe724d7-0b86-49a2-a25c-c8b45f1de0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[2]/td</value>
      <webElementGuid>322a803c-8342-438d-80e2-4441034ec399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                            BaseDatosAgendamiento
                                        ' or . = '
                                            BaseDatosAgendamiento
                                        ')]</value>
      <webElementGuid>17e90ef1-0c5f-473a-a093-5e49b193feb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
