<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td2_ProveedorExterno</name>
   <tag></tag>
   <elementGuidId>9150e4c0-f048-4dc8-8d35-64e22ac0bd3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_grvConsultorClientees']/tbody/tr[3]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>03ddc13c-ef80-4219-8f1d-a05ea67739e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>ae6cf18d-d0ae-4c3e-b2d3-825db4212d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>0b05712a-caa6-43ac-bb69-51745acb9352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            ProveedorExterno
                                        </value>
      <webElementGuid>a05d0650-5050-4bd2-a5a4-a532e0e7dcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grvConsultorClientees&quot;)/tbody[1]/tr[@class=&quot;trClick&quot;]/td[1]</value>
      <webElementGuid>a1726592-a1f3-437c-af93-96ec2dc5628b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grvConsultorClientees']/tbody/tr[3]/td</value>
      <webElementGuid>47a875cf-953e-49fe-bf6f-8339b8de1ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El usuario va ser consultado por la base de agendamiento'])[1]/following::td[4]</value>
      <webElementGuid>1895797b-1cad-4f2d-b8cb-1956d849a27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BaseDatosAgendamiento'])[1]/following::td[5]</value>
      <webElementGuid>abae7eab-316d-4258-8813-491cf83cad2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El usuario va ser consultado por un proveedor externo'])[1]/preceding::td[1]</value>
      <webElementGuid>b4242eb2-beda-42f8-b93c-b8bf62cbd5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[3]/td</value>
      <webElementGuid>7f72285c-e655-4c64-b6ec-a00c0d6b2d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                            ProveedorExterno
                                        ' or . = '
                                            ProveedorExterno
                                        ')]</value>
      <webElementGuid>f3459613-7ea3-48ab-bbaa-50934639c688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
