<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Hora Fin HH UP</name>
   <tag></tag>
   <elementGuidId>ea5e5159-5c9f-4e2a-96a7-4b1772829ca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraFin_txtHora_bUp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_tspHoraFin_txtHora_bUp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4126e6ef-60c8-4a1f-b564-8e914e416e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b28d9e23-c1f7-44b9-a8de-1a260b17ad30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_tspHoraFin_txtHora_bUp</value>
      <webElementGuid>e72e7259-b1eb-405b-8ccd-2e7fc3e64147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▲</value>
      <webElementGuid>ad3e7f00-2651-4bd5-99b2-976d8da47735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_tspHoraFin_txtHora_bUp&quot;)</value>
      <webElementGuid>d361aedd-0c21-4dff-b3fd-44db3a4ad99b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraFin_txtHora_bUp']</value>
      <webElementGuid>49af00e2-d186-4b51-b921-edaf5fa01e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divRolEdit']/table/tbody/tr[9]/td[2]/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>765456d3-3421-4bd6-b6c8-e04675dc9a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>59bf0666-a14b-4757-8c14-65fc91ac7671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_tspHoraFin_txtHora_bUp']</value>
      <webElementGuid>cf4e6a7a-7374-4582-962a-df1d1295c49b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
