<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Hora Inicio MM UP</name>
   <tag></tag>
   <elementGuidId>b98ef7e5-185b-4367-b010-8127ea367e22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bUp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bUp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea923a67-319f-4743-8c79-4765d550dfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a9778f1-86aa-442f-8eb3-f2903281ce6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bUp</value>
      <webElementGuid>2b7ad78b-45d1-4925-b423-87fe0d7cd638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▲</value>
      <webElementGuid>55153691-a28f-4b41-a4fc-c161c864b8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bUp&quot;)</value>
      <webElementGuid>dd2070ee-8b40-4a33-9e65-d6194c1023de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bUp']</value>
      <webElementGuid>bb211c97-aba8-42af-abbd-f861d53db75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divRolEdit']/table/tbody/tr[8]/td[2]/div/div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>8cd1bb01-d2d6-4267-ac92-9b3f4ba41d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e3cb040c-ecc7-4e3f-b1a4-1d380914842a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_tspHoraInicio_txtMinuto_bUp']</value>
      <webElementGuid>9a2af5ef-75b9-4f8a-8cff-5c80b46c74cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
