<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Hora Inicio HH UP</name>
   <tag></tag>
   <elementGuidId>b18e285e-51d9-4c82-9558-fd533934ec4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora_bUp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora_bUp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f43bee2-7aec-4625-ae0a-3abf9db3725b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab9c4a34-2b70-445f-b3f4-2c6a236144c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora_bUp</value>
      <webElementGuid>2b9481bd-215e-4be5-9988-f7adbc76f130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▲</value>
      <webElementGuid>ad2a9b58-d6bb-49cc-88d4-22375dd7742e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora_bUp&quot;)</value>
      <webElementGuid>8cd83229-7c6c-4f85-b5a2-6a2268297cd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora_bUp']</value>
      <webElementGuid>a2243061-c262-4517-9965-437a89a5754b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divRolEdit']/table/tbody/tr[8]/td[2]/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>756cc912-da8c-4fad-af19-f59352c3606b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>aaac8104-591e-43b7-8cf7-4195be89a2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_tspHoraInicio_txtHora_bUp']</value>
      <webElementGuid>0a3f753e-8e62-4063-81a2-ea38c2174712</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
