<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Observaciones</name>
   <tag></tag>
   <elementGuidId>2ea9d55d-ed5a-4af8-887e-b44f3a703c6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_ContentPlaceHolder2_txtObservacionesDT5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_txtObservacionesDT5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e4053b12-3a26-413c-9b0d-1c799de19b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$txtObservacionesDT5</value>
      <webElementGuid>5be9bd99-7f5c-465b-9740-40eb1f15fd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>da6237c7-5593-4c63-8797-3c2656b6fb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>588118dd-c25d-4ed4-be30-98317317e45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_txtObservacionesDT5</value>
      <webElementGuid>c0783867-0baa-48a8-a8a8-bf3782c19e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_txtObservacionesDT5&quot;)</value>
      <webElementGuid>988a52df-f7de-4506-8d40-dedacb64aa8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_ContentPlaceHolder2_txtObservacionesDT5']</value>
      <webElementGuid>0fbc2eee-8b1e-432b-81f5-d669e7f4b297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divRolEdit']/div/div[2]/table/tbody/tr[8]/td[2]/textarea</value>
      <webElementGuid>90fe8160-494c-44e7-9213-c9bccd6ae792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>be58906d-c46b-47b1-a3ab-414a984020c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$ContentPlaceHolder2$txtObservacionesDT5' and @id = 'ctl00_ContentPlaceHolder2_txtObservacionesDT5']</value>
      <webElementGuid>abbd426b-d459-494a-8b64-1aeb81d68fd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
