<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Limpiar</name>
   <tag></tag>
   <elementGuidId>f8347b12-a3e0-4ef5-9dbb-2bed53b9f448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_btnLimpiar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_btnLimpiar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96b6d6e7-98e2-4f6a-a727-f69e015bbd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e7b3e5f5-12fb-44e0-b714-38390ddfa5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$btnLimpiar</value>
      <webElementGuid>52e2dcbf-f732-4cad-bd8d-604a59716c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Limpiar</value>
      <webElementGuid>303abb8c-de15-4861-a783-205b26aae9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_btnLimpiar</value>
      <webElementGuid>2b8bc511-4e25-429e-af5d-291cf84f4acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton</value>
      <webElementGuid>c780f0fb-1aab-4e5a-b3f2-e2ea0e7e20ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_btnLimpiar&quot;)</value>
      <webElementGuid>d57e9b8f-1260-4952-a2b0-b8efb3302cbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_btnLimpiar']</value>
      <webElementGuid>a81c80fb-5831-4b6b-afcd-566b96b1e98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divConsultorClienteEdit']/div/div[2]/table/tbody/tr[5]/td/input</value>
      <webElementGuid>6726e6e8-f4c3-49ff-bc9f-1e09947d71ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/input</value>
      <webElementGuid>646a182b-8fec-4e97-ac19-b05ca55fe450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder2$btnLimpiar' and @id = 'ctl00_ContentPlaceHolder2_btnLimpiar']</value>
      <webElementGuid>3f7c1758-1629-4fc7-b469-385a2ab46249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
