<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Activo</name>
   <tag></tag>
   <elementGuidId>570135d3-46ac-497f-8a24-5071ff279948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divConsultorClienteEdit']/div/div[2]/table/tbody/tr[3]/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e01c0cd4-f84d-45ab-9294-363ef75d76d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ckbActivo</value>
      <webElementGuid>78b034fe-3e3a-4171-8ce2-cee9e8b4d824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divConsultorClienteEdit&quot;)/div[@class=&quot;caja&quot;]/div[@class=&quot;cajaContenido&quot;]/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[3]/td[2]/span[1]/label[1]</value>
      <webElementGuid>c3613a5d-0b60-44f9-9415-ff5f666339a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divConsultorClienteEdit']/div/div[2]/table/tbody/tr[3]/td[2]/span/label</value>
      <webElementGuid>310a355a-8527-4202-8f04-6e75d29237c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>3c935800-24e0-487c-bb2a-9cd8fe662131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
