<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Orden validacion</name>
   <tag></tag>
   <elementGuidId>6d831bc0-8951-4717-a1a5-dd1af572a1aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_ContentPlaceHolder2_ddlOrdenConsultorCliente']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_ddlOrdenConsultorCliente</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>db668f1e-cf22-42d1-9a38-e593dd37d9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$ddlOrdenConsultorCliente</value>
      <webElementGuid>bd5e9bc4-9b0e-43ce-b130-94d1730ede4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ddlOrdenConsultorCliente</value>
      <webElementGuid>aa47cb17-b7cc-43f0-a2f6-eab266e6ba6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_ddlOrdenConsultorCliente&quot;)</value>
      <webElementGuid>c9ab68ca-4f81-470d-bf69-fd50abdc8cf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_ContentPlaceHolder2_ddlOrdenConsultorCliente']</value>
      <webElementGuid>87fc30a5-7717-48c7-84e8-dc6e14605981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divConsultorClienteEdit']/div/div[2]/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>65253c4b-9a96-4e37-ad09-c88c2ccc8142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orden validación:'])[1]/following::select[1]</value>
      <webElementGuid>2c04d6cd-8f84-4a8e-b194-0f5b62a36e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activo:'])[1]/following::select[1]</value>
      <webElementGuid>64bbf21d-646d-440f-8293-ba19a697e3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista de consultores clientes'])[1]/preceding::select[1]</value>
      <webElementGuid>a3044c14-2a16-472d-bf81-78b9b7137874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>dc215fbf-56a7-486d-98d1-d9f0929a8478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder2$ddlOrdenConsultorCliente' and @id = 'ctl00_ContentPlaceHolder2_ddlOrdenConsultorCliente']</value>
      <webElementGuid>84f9f18f-2fb2-4739-8d52-1ed9260d8693</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
