<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Activo</name>
   <tag></tag>
   <elementGuidId>b7594860-a8bb-4b94-b635-24289a4fa3a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divRolEdit']/div/div[2]/div/table/tbody/tr[3]/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>77b314b2-593c-419f-9c59-faf94fc29387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ckbActivo</value>
      <webElementGuid>0d456f99-f8e2-467e-9623-2953db7a4648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divRolEdit&quot;)/div[@class=&quot;caja&quot;]/div[@class=&quot;cajaContenido&quot;]/div[1]/table[1]/tbody[1]/tr[3]/td[2]/span[1]/label[1]</value>
      <webElementGuid>12d53bae-e43b-435e-98b3-d3b98edd230b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divRolEdit']/div/div[2]/div/table/tbody/tr[3]/td[2]/span/label</value>
      <webElementGuid>c3250a0f-62ea-4bb1-9b40-826c0dec7c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>89b1bda3-5cf4-4654-9a25-4080e2c69b38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
