<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1 G.G.Informacion_Editar</name>
   <tag></tag>
   <elementGuidId>654921e6-b59c-4f11-bf0b-9bf48858b6b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnEdit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnEdit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c05c514-30a7-4154-9806-8984d17fb4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnEdit</value>
      <webElementGuid>bb9215d7-909a-4386-838d-b87d019f8763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnEditarImg mostrarEditar</value>
      <webElementGuid>5197080f-074f-4333-8c7f-aff32c3d6d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>imagealign</name>
      <type>Main</type>
      <value>Middle</value>
      <webElementGuid>a8fa8a99-add6-40fc-847d-e585c0f27865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl02$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=771689cd-f2df-4d0b-95e5-49c431c6ee7b&quot;, false, true))</value>
      <webElementGuid>68b0a7f3-3647-4e83-bfcc-6b43717aade1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnEdit&quot;)</value>
      <webElementGuid>21d1bcc8-1d98-49f3-922b-7d56f7cdaef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnEdit']</value>
      <webElementGuid>7c447e54-daf5-4427-9181-fbe53b520377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvEspecialidades']/tbody/tr[2]/td/a</value>
      <webElementGuid>96d2415a-20a7-4e00-b659-fe328167765d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl02$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=771689cd-f2df-4d0b-95e5-49c431c6ee7b&quot;, false, true))')]</value>
      <webElementGuid>c6767a49-1e64-4fb0-956f-612942eee43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>eb63b15f-4bf2-4b68-b8f8-c24ced93b97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvEspecialidades_ctl02_btnEdit' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl02$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=771689cd-f2df-4d0b-95e5-49c431c6ee7b&quot;, false, true))']</value>
      <webElementGuid>1b62d673-0fea-4150-8379-406d40c3f785</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
