<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3 G.G.Radicaciones_Editar</name>
   <tag></tag>
   <elementGuidId>efbaf390-1565-49e0-8c28-9fc8d31f84d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl04_btnEdit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvEspecialidades_ctl04_btnEdit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a942fb3e-03f6-4dfc-9aa1-3348b5dc469b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvEspecialidades_ctl04_btnEdit</value>
      <webElementGuid>1b06bf0f-12e9-4382-9e20-c97840a8a5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnEditarImg mostrarEditar</value>
      <webElementGuid>49f312a4-2084-4dff-a4af-3f4203d7f857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>imagealign</name>
      <type>Main</type>
      <value>Middle</value>
      <webElementGuid>3cff3f86-fc72-4876-9882-c63a5c714f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl04$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=670ee821-071e-4cc7-8802-35f487fb1022&quot;, false, true))</value>
      <webElementGuid>e22253a1-6b52-4ff0-ac63-bcfb9a1bef4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvEspecialidades_ctl04_btnEdit&quot;)</value>
      <webElementGuid>b8acfb64-6ab4-4f9c-b78a-cc09b6150edc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl04_btnEdit']</value>
      <webElementGuid>0caf1ed2-bac1-4f44-a9ba-37b507c9b596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvEspecialidades']/tbody/tr[4]/td/a</value>
      <webElementGuid>d0444fec-a8c9-4435-b49a-fe8d97c724b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl04$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=670ee821-071e-4cc7-8802-35f487fb1022&quot;, false, true))')]</value>
      <webElementGuid>c923af37-72f3-4fcf-aac4-08cd11faee6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/a</value>
      <webElementGuid>9049aff1-ca8c-4280-91ec-4883524aa572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvEspecialidades_ctl04_btnEdit' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl04$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=670ee821-071e-4cc7-8802-35f487fb1022&quot;, false, true))']</value>
      <webElementGuid>8f3fa0ac-f351-41e6-9d38-18454aa570ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
