<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_4 G.P.Informacion_Editar</name>
   <tag></tag>
   <elementGuidId>e0dec205-e642-4f9f-9de4-01763e535391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl05_btnEdit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvEspecialidades_ctl05_btnEdit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0775902d-1c1a-42cb-8fa4-b9ad0de1aaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvEspecialidades_ctl05_btnEdit</value>
      <webElementGuid>de3df306-ddc6-49aa-b8b8-5d8be9cde5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnEditarImg mostrarEditar</value>
      <webElementGuid>3fbf0ab2-4f35-4dae-8eac-9ef5891e8952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>imagealign</name>
      <type>Main</type>
      <value>Middle</value>
      <webElementGuid>279f0b34-6a3a-403d-b0ea-a2f267eb5ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl05$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=f16c9f71-7dc8-4b0d-889b-9f5728ae573d&quot;, false, true))</value>
      <webElementGuid>761fc3a7-81e7-45f7-b566-ac2f2f854cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvEspecialidades_ctl05_btnEdit&quot;)</value>
      <webElementGuid>c2263404-c273-4291-ac57-0abbfe732ef8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl05_btnEdit']</value>
      <webElementGuid>89dbf179-3df1-4941-a0ef-841d5f167fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvEspecialidades']/tbody/tr[5]/td/a</value>
      <webElementGuid>afc97432-8cb7-4f41-848c-58379bc7cbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl05$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=f16c9f71-7dc8-4b0d-889b-9f5728ae573d&quot;, false, true))')]</value>
      <webElementGuid>2016310a-834f-4590-a112-d54e4082b3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/a</value>
      <webElementGuid>0021b72a-84eb-4a29-a7ea-f619f1de7307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvEspecialidades_ctl05_btnEdit' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl05$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=f16c9f71-7dc8-4b0d-889b-9f5728ae573d&quot;, false, true))']</value>
      <webElementGuid>7ec323cd-1ba1-4ff9-965e-864990de22fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
