<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_6 G.P.Radicaciones_Editar</name>
   <tag></tag>
   <elementGuidId>663bf656-4416-4d60-bd76-1a2a66e702b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnEdit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnEdit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>227dc46e-e26c-401f-934b-279188226d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnEdit</value>
      <webElementGuid>42866123-b6a0-4de3-83c1-5eac55215aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnEditarImg mostrarEditar</value>
      <webElementGuid>8c2d4a5d-e016-4740-9bbd-9c126f8387aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>imagealign</name>
      <type>Main</type>
      <value>Middle</value>
      <webElementGuid>bd0c115b-3646-4b26-ab20-3b7bcbb9de0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl07$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=a139463c-d1f2-4350-84a2-3e1954794d9b&quot;, false, true))</value>
      <webElementGuid>400fac13-a473-4afe-8e0f-80199ec7ff02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnEdit&quot;)</value>
      <webElementGuid>bd9a5077-3da9-4c9e-98b5-db17927d09e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnEdit']</value>
      <webElementGuid>f99b3aae-de91-4da4-9abf-c19ed1ee8b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvEspecialidades']/tbody/tr[7]/td/a</value>
      <webElementGuid>e6da749c-c3c6-48cd-8154-22f4925762d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl07$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=a139463c-d1f2-4350-84a2-3e1954794d9b&quot;, false, true))')]</value>
      <webElementGuid>5ba8a5c1-de92-49a4-8ebc-c85638ecb7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/a</value>
      <webElementGuid>3a41986e-0cbf-4a65-a2a6-60af8db38df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvEspecialidades_ctl07_btnEdit' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder2$gvEspecialidades$ctl07$btnEdit&quot;, &quot;&quot;, false, &quot;&quot;, &quot;frmEspecialidadPorOficinaEdit.aspx?OficinaId=15b7b28a-1956-4948-a8c3-2c72abf0bbfb&amp;TipoClienteId=ca368413-14a3-43a5-b9d0-f8238010a22e&amp;EspecialidadId=a139463c-d1f2-4350-84a2-3e1954794d9b&quot;, false, true))']</value>
      <webElementGuid>af91ca67-6de1-4363-923d-241f4f5219e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
