<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Modo HTML</name>
   <tag></tag>
   <elementGuidId>d2e6bab7-c625-4189-8412-0544851e3b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aef26614-31f4-4a54-a347-a69e7f6b2568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/WebResource.axd?d=v2hrE9eVdmltFqW5yiNif4lPMGg_tdAQL3a6A1k8GLDBSJjCMca5z-ZUERzdJyDrYk649ocI6tyek4aGo71hfF260Ukt9hZoBTljxh6R25HcJpdr2KDHYdrD62uc6Du0gj1qTshffYrtNALIkDrFPLV0HOo1&amp;t=637866756480000000</value>
      <webElementGuid>59d822dc-052c-4cde-838b-464e3993824b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl01</value>
      <webElementGuid>f8719743-4b24-46fa-a91c-cc4b8acff615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>HTML text</value>
      <webElementGuid>2850db26-6962-4697-88af-0020d01f9655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_toolbar_button ajax__htmleditor_toolbar_button_hover</value>
      <webElementGuid>6c907c25-a375-4c2d-bcad-bfff6c892543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl01&quot;)</value>
      <webElementGuid>ab0138ff-7e7c-4bf6-9336-873f14f0c265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl01']</value>
      <webElementGuid>f22cbdf0-60d7-4b48-b62e-14bf2ddcaebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtMensaje_ctl03']/img[2]</value>
      <webElementGuid>eec5b6bf-07ac-4cc0-82a6-3d19674a0e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='HTML text']</value>
      <webElementGuid>e725f8a2-349d-4d94-a0bb-441772b33147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/img[2]</value>
      <webElementGuid>dd8c1e28-3742-42ab-afb0-48926bb99992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/WebResource.axd?d=v2hrE9eVdmltFqW5yiNif4lPMGg_tdAQL3a6A1k8GLDBSJjCMca5z-ZUERzdJyDrYk649ocI6tyek4aGo71hfF260Ukt9hZoBTljxh6R25HcJpdr2KDHYdrD62uc6Du0gj1qTshffYrtNALIkDrFPLV0HOo1&amp;t=637866756480000000' and @id = 'ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl01' and @title = 'HTML text']</value>
      <webElementGuid>b8406ce1-685a-4662-9994-81400b2e98b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
