<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Modo Diseno</name>
   <tag></tag>
   <elementGuidId>820aa6df-e058-4cfa-a989-99b9a6c291ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl00</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>03164df6-57b9-4f6a-b760-426fc34a3613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/WebResource.axd?d=K6hBBt7cIA91H1qzdLBxg10QNh7DXghXL-t9a9srjCReFadxAKoJXRJmdVUvwHpvv_lG5pk30fBg3aIZBse7dEQkaAa1A8hbMpNi2yF6ETNy0zEhETgvyBQYw9xWUepep23mP_0DteY0DLylqmvn4VFcMTA1&amp;t=637866756480000000</value>
      <webElementGuid>cbff5dab-f2b6-41b4-8a09-ca3d185737ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl00</value>
      <webElementGuid>851cc58f-afa1-4554-85e8-79e2d257478a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Design mode</value>
      <webElementGuid>4706b8b7-dd8a-45fc-be6f-3d8cd7657af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_toolbar_button ajax__htmleditor_toolbar_button_active ajax__htmleditor_toolbar_button_hover</value>
      <webElementGuid>a956ef80-a418-4d55-99b2-11183ae7f728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl00&quot;)</value>
      <webElementGuid>bbd660c2-8dc7-4ca2-8895-9e4ea1f025e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl00']</value>
      <webElementGuid>8c72e023-96bb-4479-9b91-3534182c9ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtMensaje_ctl03']/img</value>
      <webElementGuid>49ef8cd6-480a-4833-abb5-a1ec775dbc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Design mode']</value>
      <webElementGuid>dfdfb799-9f91-4bc0-8ca8-4ef4d4f759bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/img</value>
      <webElementGuid>474708ae-4f2b-4e04-ab04-74865a545b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/WebResource.axd?d=K6hBBt7cIA91H1qzdLBxg10QNh7DXghXL-t9a9srjCReFadxAKoJXRJmdVUvwHpvv_lG5pk30fBg3aIZBse7dEQkaAa1A8hbMpNi2yF6ETNy0zEhETgvyBQYw9xWUepep23mP_0DteY0DLylqmvn4VFcMTA1&amp;t=637866756480000000' and @id = 'ctl00_ContentPlaceHolder2_edtMensaje_ctl03_ctl00' and @title = 'Design mode']</value>
      <webElementGuid>f30c7f28-79db-4cda-9793-b7749def0b52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
