<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Paises</name>
   <tag></tag>
   <elementGuidId>011e740c-56ee-43f2-a5db-3312adf9cbf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_ContentPlaceHolder2_ddlEditPaises']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_ddlEditPaises</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b4f2067c-16e6-439c-9350-d70b7a6482f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$ddlEditPaises</value>
      <webElementGuid>994915d8-2fc7-4bb0-97fb-2f80a8554b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$ContentPlaceHolder2$ddlEditPaises\',\'\')', 0)</value>
      <webElementGuid>2962a86f-ad34-45b4-bcda-1f36f46ea098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_ddlEditPaises</value>
      <webElementGuid>544ec2a0-137c-4260-8a35-0a0f347a27cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Colombia

	</value>
      <webElementGuid>38b0af06-fd38-41e1-870e-6320c47c1d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_ddlEditPaises&quot;)</value>
      <webElementGuid>93f3f0fc-343d-4826-a249-f3f93f3d74de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_ContentPlaceHolder2_ddlEditPaises']</value>
      <webElementGuid>6524c80d-7679-4e74-9295-9a2f8358e91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_upRegional']/table/tbody/tr/td[2]/select</value>
      <webElementGuid>236c3f7e-ded4-4b11-bea5-6f92a3b065ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Países:'])[1]/following::select[1]</value>
      <webElementGuid>234c0e9a-8bb6-404d-bbc5-d89b82d1b14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuevo Estado'])[1]/following::select[1]</value>
      <webElementGuid>5467ec07-504d-4ced-bcf8-fe225becd726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::select[1]</value>
      <webElementGuid>37d422db-843b-45eb-91ac-6342fe90f0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código Estado:'])[1]/preceding::select[1]</value>
      <webElementGuid>e361fddb-e353-4491-8f04-a0d90ef67408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1fc097a1-73be-4d01-8c80-ba910140efc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder2$ddlEditPaises' and @id = 'ctl00_ContentPlaceHolder2_ddlEditPaises' and (text() = '
		Colombia

	' or . = '
		Colombia

	')]</value>
      <webElementGuid>c3bd3dfd-c9f7-4923-b6df-6fd4ca6b35e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
