<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TipoEspecialidad</name>
   <tag></tag>
   <elementGuidId>b4faf8db-1d3f-41ac-b81e-d3e71d48533c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_NombreTipoEspecialidad']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_NombreTipoEspecialidad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cd51992-6c6c-4d57-9708-86bb3c14f1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl02$ctl02$FilterTextBox_NombreTipoEspecialidad</value>
      <webElementGuid>89f70b28-89a2-4b66-aaeb-a9773e3049ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0af7185e-8729-4fb4-bc6f-27e7a89a226f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e37a38a2-86a8-4d72-9dba-1d59730cf5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_NombreTipoEspecialidad</value>
      <webElementGuid>63226b0e-e2ed-49d7-a68a-0be60f1422e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rgFilterBox</value>
      <webElementGuid>ed6d7207-ff2a-44e7-b548-e222b093c7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Filter NombreTipoEspecialidad column</value>
      <webElementGuid>e7e5ea7f-b049-4815-9dec-e374745594a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if((event.keyCode == 13)) return false;</value>
      <webElementGuid>fa32476c-819d-4a17-aedf-274264e034f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e32e8976-fdc4-45b3-9a5a-ccbc94d4039b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_NombreTipoEspecialidad&quot;)</value>
      <webElementGuid>f148bf2f-d0c4-4930-b816-26c26f1b339b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_NombreTipoEspecialidad']</value>
      <webElementGuid>613213f4-1a06-48b2-b280-19972d31e13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00']/thead/tr[2]/td[6]/input</value>
      <webElementGuid>5911ba08-b7c9-41ce-a0e3-de1e5a69e9f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>5881bb1d-10f4-4f72-b4f4-23ab01483383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl02$ctl02$FilterTextBox_NombreTipoEspecialidad' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_NombreTipoEspecialidad' and @alt = 'Filter NombreTipoEspecialidad column']</value>
      <webElementGuid>38957c9d-8dff-4365-8cf3-0554809293a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
