<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5 Jornada Oficina Medellin_Borrar</name>
   <tag></tag>
   <elementGuidId>69989b37-c1f1-477a-a182-fcee0a82a8fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvJornadas_ctl06_btnBorrar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvJornadas_ctl06_btnBorrar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>881926a7-5259-41f1-b792-2ca7937715b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('¿Desea eliminar la jornada?');</value>
      <webElementGuid>1c5fc832-8143-490c-aa59-6d0a7a3de7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvJornadas_ctl06_btnBorrar</value>
      <webElementGuid>e38bdbed-c766-4466-bf70-f5e21e95335f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnBorrarImg</value>
      <webElementGuid>59c191b5-c913-48e5-97ef-966445ca3911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvJornadas$ctl06$btnBorrar','')</value>
      <webElementGuid>11bd2659-dee0-4823-b0d0-a2686253314d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvJornadas_ctl06_btnBorrar&quot;)</value>
      <webElementGuid>adf43b1a-adbf-46df-810b-cad75965cbe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvJornadas_ctl06_btnBorrar']</value>
      <webElementGuid>757d1d9b-6468-4dd9-b86f-8a447091f42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvJornadas']/tbody/tr[6]/td[6]/div/a[2]</value>
      <webElementGuid>cf46ee43-65db-40a4-9625-436334774f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvJornadas$ctl06$btnBorrar','')&quot;)]</value>
      <webElementGuid>39996a84-8f2c-41e0-9112-126d7b0f5c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[6]/div/a[2]</value>
      <webElementGuid>d02c13e1-57e4-425e-a66f-59a870d29043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvJornadas_ctl06_btnBorrar' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder2$gvJornadas$ctl06$btnBorrar&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;)]</value>
      <webElementGuid>9efcca9f-302f-4574-844f-8962515d1a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
