<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_3 Jornada Oficina Cartagena</name>
   <tag></tag>
   <elementGuidId>eac6d649-02a8-46ec-8483-c5c507b72c03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvJornadas']/tbody/tr[4]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f8be46df-0b86-47bd-a2b0-2c47b44b66e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jornada Oficina Cartagena</value>
      <webElementGuid>c32f3e49-0655-4aa4-ae31-2f8d0caef26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvJornadas&quot;)/tbody[1]/tr[@class=&quot;trClick&quot;]/td[2]</value>
      <webElementGuid>7156386c-31f2-4aa5-be16-20393e1883e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvJornadas']/tbody/tr[4]/td[2]</value>
      <webElementGuid>f2124f75-b496-4ccf-8dbe-3c9dbdc00ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jornada Oficina Cali'])[1]/following::td[6]</value>
      <webElementGuid>b6c93856-2a3e-4171-bb80-a4ccb4c9d024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jornada Oficina Bogota'])[1]/following::td[12]</value>
      <webElementGuid>916c2478-8bf7-4b37-806e-0449f8666aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jornada Oficina Manizales'])[1]/preceding::td[6]</value>
      <webElementGuid>994d5136-496d-4fa6-8d41-16e5b56b4532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jornada Oficina Medellin'])[1]/preceding::td[12]</value>
      <webElementGuid>408c71e2-12ad-4c01-9b64-9fe6f5daceee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jornada Oficina Cartagena']/parent::*</value>
      <webElementGuid>dd62aae3-0b8d-49da-8cb7-b6e739a776b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/table/tbody/tr[4]/td[2]</value>
      <webElementGuid>7616e2de-ea9e-4621-81b2-0591aaea7755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Jornada Oficina Cartagena' or . = 'Jornada Oficina Cartagena')]</value>
      <webElementGuid>3cde1606-f75f-4d8c-960e-cc7d9a349449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
