<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre Estado</name>
   <tag></tag>
   <elementGuidId>fbb2e05d-0c7a-4bdc-b4b2-39d9b6f2d379</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_txtNombreEstado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_txtNombreEstado</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'ctl00$ContentPlaceHolder2$txtNombreEstado' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_txtNombreEstado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57596178-6da0-45f8-a19b-78472b56d7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$txtNombreEstado</value>
      <webElementGuid>c557b87d-6d10-495c-8044-ba0ca866eabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21631cc9-2a6f-46a7-912c-9b20113d4e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_txtNombreEstado</value>
      <webElementGuid>a520d0d4-6a61-47b8-95e5-f6317f96f4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textoFiltro</value>
      <webElementGuid>42138392-2f06-4c15-9c8a-f5996d27d208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5e7e1506-1db1-48cb-982f-f5e3e2282f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_txtNombreEstado&quot;)</value>
      <webElementGuid>34cce55e-a50b-4b37-b60d-daa72c6fcd71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_txtNombreEstado']</value>
      <webElementGuid>3daf2528-03d7-4a0f-b43e-c25e2302be9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divFiltrosCitas']/div[2]/input</value>
      <webElementGuid>cda4527b-66df-4f25-9ab1-77c180d7cf0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>cf17f0e1-75df-4ceb-b36a-88ceb6a082db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$txtNombreEstado' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_txtNombreEstado']</value>
      <webElementGuid>3197dcec-4431-4636-9e6f-fc8627da0877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
