<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>de9dfa4c-e061-4180-b959-a6b7f77992b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_Pager']/tbody/tr/td/div/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.rgWrap.rgNumPart > a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>350be91c-21b8-4bab-8003-c5c06e45bc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl03$ctl01$ctl06','')</value>
      <webElementGuid>416b58e0-1322-495e-a906-2eb75fbc7098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8429ddc7-9411-449c-9972-f49ef819ef74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_RadGrid1_ctl00_Pager&quot;)/tbody[1]/tr[@class=&quot;rgPager&quot;]/td[@class=&quot;rgPagerCell&quot;]/div[@class=&quot;NextPrevAndNumeric&quot;]/div[@class=&quot;rgWrap rgNumPart&quot;]/a[2]</value>
      <webElementGuid>321e9c8a-1c32-40a3-b7f0-35a3688bc738</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_Pager']/tbody/tr/td/div/div[2]/a[2]</value>
      <webElementGuid>fb2e1ab8-4137-4f42-8c9f-3582fdc86876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'2')])[2]</value>
      <webElementGuid>eb341d56-841e-4433-86ec-95834711b382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código país por defecto'])[1]/following::a[2]</value>
      <webElementGuid>f05136e4-8077-4161-8e6c-db971dc0eede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de citas por día para un mismo usuario y servicio'])[1]/following::a[2]</value>
      <webElementGuid>77bdfe86-15bf-4a26-a3c0-1849ef3feed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page size:'])[1]/preceding::a[2]</value>
      <webElementGuid>3a8f2c95-a5a1-4fea-8bd9-6eaa284adde1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[1]/preceding::a[2]</value>
      <webElementGuid>60c295ab-2d15-4720-a157-c3cdd170e555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl03$ctl01$ctl06','')&quot;)]</value>
      <webElementGuid>c95a5d19-0f6e-4e9c-913e-d124041fb6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/a[2]</value>
      <webElementGuid>9183b1d2-9918-42c6-85e3-048bee744eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl03$ctl01$ctl06&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '2' or . = '2')]</value>
      <webElementGuid>f8c340e9-cdb8-4029-8baf-4ae9b93d8426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
