<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_50</name>
   <tag></tag>
   <elementGuidId>14836375-07ee-4a50-8cc1-6a1df8219e73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl03_ctl01_PageSizeComboBox_DropDown']/div/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.rcbHovered</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>86b1158c-01b2-4470-95f1-2e5583ef4f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rcbHovered</value>
      <webElementGuid>9db0d617-3b98-4ddf-88b8-7b5193992cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>6fa532aa-e43b-4610-acd1-8b7f0ea6326f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl03_ctl01_PageSizeComboBox_DropDown&quot;)/div[@class=&quot;rcbScroll rcbWidth&quot;]/ul[@class=&quot;rcbList&quot;]/li[@class=&quot;rcbHovered&quot;]</value>
      <webElementGuid>3e9fcda9-d98d-483a-9c34-711cdc2fa7a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl03_ctl01_PageSizeComboBox_DropDown']/div/ul/li[3]</value>
      <webElementGuid>3ab1b0c8-862f-48a0-bc44-eb4d8d571726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::li[1]</value>
      <webElementGuid>1cefe4ca-6d8a-4163-880d-23307c4e5ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Módulo de administración'])[1]/preceding::li[1]</value>
      <webElementGuid>cba8fa3d-05be-4b78-bb88-09ac986c9970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='50']/parent::*</value>
      <webElementGuid>cd98d8b5-9d5d-41d8-93f0-ab531f51fb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>7d8687ff-0145-4659-97d0-5d65fbd3e275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '50' or . = '50')]</value>
      <webElementGuid>40b2cb5c-ffe3-410e-a8d2-57057c33cc66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
