<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td2_Fin de Jornada</name>
   <tag></tag>
   <elementGuidId>735d40d4-f9cd-42d6-85b1-d16a50c8158b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_mcMotivos_gvMotivos']/tbody/tr[3]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d43a9c28-e8d1-46be-ac9a-836682764757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fin de Jornada</value>
      <webElementGuid>0dd6db73-78ca-422a-80ed-70136ff273c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_mcMotivos_gvMotivos&quot;)/tbody[1]/tr[@class=&quot;trClick&quot;]/td[2]</value>
      <webElementGuid>1942de5a-b8ce-4a0b-9d42-945e062dbd7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_mcMotivos_gvMotivos']/tbody/tr[3]/td[2]</value>
      <webElementGuid>41a1813d-90f5-4c28-8dc6-0ba9760c1ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Almuerzo'])[1]/following::td[5]</value>
      <webElementGuid>fc146876-f1e4-45c7-a624-1650a1fe3a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hora Fin'])[1]/following::td[7]</value>
      <webElementGuid>8cbe41bb-8de3-4bcb-ae95-3176d1ccab7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba'])[1]/preceding::td[5]</value>
      <webElementGuid>93a5aaa7-b301-42fc-88b8-8c9a3c269ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motivos de cierre por oficina'])[1]/preceding::td[9]</value>
      <webElementGuid>e57dfd91-93ee-4560-8c6b-b194bbb98f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fin de Jornada']/parent::*</value>
      <webElementGuid>4d3d6f58-3757-48ad-8de9-38c46d7431d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]</value>
      <webElementGuid>e447c375-7d85-459f-9ec1-37883575ef02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Fin de Jornada' or . = 'Fin de Jornada')]</value>
      <webElementGuid>0a1bd6c1-61f5-4912-9140-8e0423dd5cda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
