<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Confirmadas</name>
   <tag></tag>
   <elementGuidId>8899b5d3-13e5-44df-be04-fe8ffcf547c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvAgendasXFechas']/tbody/tr/th[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tbody > tr > th:nth-of-type(7)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>f702b4eb-1108-4a27-ba90-3b784e6bf56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>b447ec79-0d61-4a8e-a474-8fcb14890d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmadas</value>
      <webElementGuid>0c790075-2386-4513-be07-9aca7659f339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAgendasXFechas&quot;)/tbody[1]/tr[1]/th[7]</value>
      <webElementGuid>e2f3f61a-d20d-4868-9391-a8cd0f69b9df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAgendasXFechas']/tbody/tr/th[7]</value>
      <webElementGuid>2d8b4ce1-4b5a-408f-8426-96a71777f630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre Agendadas'])[1]/following::th[1]</value>
      <webElementGuid>048ca848-fd30-4279-8c26-92b7b74b2ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reservadas'])[1]/following::th[2]</value>
      <webElementGuid>39e320a6-cc6e-4076-9d13-4128c4600fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Totales:'])[1]/preceding::th[2]</value>
      <webElementGuid>9f6b9ad9-3260-498c-88d0-1087d1ae6adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirmadas']/parent::*</value>
      <webElementGuid>c7d23671-4e35-4f04-848f-8f1c60eb8d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th[7]</value>
      <webElementGuid>ae2496de-6c8d-49dd-a3ce-0102ee7fb5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Confirmadas' or . = 'Confirmadas')]</value>
      <webElementGuid>bb95f2f3-d5f4-4097-97bd-f998ffd563f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
