<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Disponibles</name>
   <tag></tag>
   <elementGuidId>35e90ec5-d1b1-42ff-96c8-09af0fd2d499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvAgendasXFechas']/tbody/tr/th[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tbody > tr > th:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>3f6b2664-8d94-465d-9d42-6af69daf0197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>199d6db0-0798-4588-8001-8f5dd2a559f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disponibles</value>
      <webElementGuid>bda000ba-be1c-4954-84d4-98756d9db0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAgendasXFechas&quot;)/tbody[1]/tr[1]/th[3]</value>
      <webElementGuid>1597ff40-959f-4346-80bb-0411ef136b12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAgendasXFechas']/tbody/tr/th[3]</value>
      <webElementGuid>c6633154-c927-48f1-ba36-f325dcb66c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::th[1]</value>
      <webElementGuid>f8af67ac-df16-4fc6-9fbd-7723f3de6652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha'])[1]/following::th[2]</value>
      <webElementGuid>89d045d9-f8cc-4fda-a3b8-2241095197db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suspendidas'])[1]/preceding::th[1]</value>
      <webElementGuid>8a5bb3d0-334d-4672-9094-1c30c8dab418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reservadas'])[1]/preceding::th[2]</value>
      <webElementGuid>68e11bc7-b4dc-430f-abe0-2af539654754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disponibles']/parent::*</value>
      <webElementGuid>2470b709-a8f7-496f-80f0-9cdb25236cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th[3]</value>
      <webElementGuid>87f75128-d72d-4e8c-9801-0eb126de267a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Disponibles' or . = 'Disponibles')]</value>
      <webElementGuid>41e09687-4f67-4680-a3fb-5c8b236379f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
