<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Reservadas</name>
   <tag></tag>
   <elementGuidId>1ba4d280-209b-40da-8d18-da83e338fc27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvAgendasXFechas']/tbody/tr/th[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tbody > tr > th:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>a0daae8e-c167-458a-9b8b-e46bd8e73865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>47c2595b-9ab9-4a3e-aa50-ca29af888074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reservadas</value>
      <webElementGuid>6ef1bd61-4887-4164-a2fb-9264d6dcc860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAgendasXFechas&quot;)/tbody[1]/tr[1]/th[5]</value>
      <webElementGuid>a6a5d453-dff3-4de8-843c-9b09e4219770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAgendasXFechas']/tbody/tr/th[5]</value>
      <webElementGuid>61f393f9-d0ab-45e1-9fee-72adb44fa8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suspendidas'])[1]/following::th[1]</value>
      <webElementGuid>62334ba0-8c71-4263-8cd7-96fef6a3ec84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disponibles'])[1]/following::th[2]</value>
      <webElementGuid>97626933-044b-4249-a2a1-417c35222a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre Agendadas'])[1]/preceding::th[1]</value>
      <webElementGuid>4be45abe-22d5-47b5-8f7f-f8c2a1fdf56c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmadas'])[1]/preceding::th[2]</value>
      <webElementGuid>dd7c067a-2d19-413d-a466-a81d5b5e0f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reservadas']/parent::*</value>
      <webElementGuid>5671c650-4c32-4576-ace6-31a1f1732120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th[5]</value>
      <webElementGuid>3dc9ca91-7354-486a-9287-bc72d6765a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Reservadas' or . = 'Reservadas')]</value>
      <webElementGuid>11c1754e-e31d-4c6b-baa6-d30244a33752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
