<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Modo HTML</name>
   <tag></tag>
   <elementGuidId>a86bc714-77f1-4c28-bdee-a0f856e3cb96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1d675bb5-83f8-442f-8d28-30f9101b2456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/WebResource.axd?d=v2hrE9eVdmltFqW5yiNif4lPMGg_tdAQL3a6A1k8GLDBSJjCMca5z-ZUERzdJyDrYk649ocI6tyek4aGo71hfF260Ukt9hZoBTljxh6R25HcJpdr2KDHYdrD62uc6Du0gj1qTshffYrtNALIkDrFPLV0HOo1&amp;t=637866756480000000</value>
      <webElementGuid>89f29d8f-38f3-4c70-a746-eb041b02588d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl01</value>
      <webElementGuid>af41e49e-4275-4784-b474-39130696fdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>HTML text</value>
      <webElementGuid>87dff583-8f0f-41bd-a61f-5d3cabae7479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_toolbar_button ajax__htmleditor_toolbar_button_hover</value>
      <webElementGuid>46fc1020-86f9-4a95-84be-277c420391f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl01&quot;)</value>
      <webElementGuid>9b3ed043-67bc-4efc-ac40-6cf3ac178ca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl01']</value>
      <webElementGuid>0b34f90c-f3a0-4ef8-bf5f-9bf861bba7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtPolitica_ctl03']/img[2]</value>
      <webElementGuid>013c8826-30ea-4859-99c4-9c5eebeca211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='HTML text']</value>
      <webElementGuid>53d2a72d-44eb-41c6-a643-b6a9d097e2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/img[2]</value>
      <webElementGuid>33b05530-c181-4584-820e-3ce09996150c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/WebResource.axd?d=v2hrE9eVdmltFqW5yiNif4lPMGg_tdAQL3a6A1k8GLDBSJjCMca5z-ZUERzdJyDrYk649ocI6tyek4aGo71hfF260Ukt9hZoBTljxh6R25HcJpdr2KDHYdrD62uc6Du0gj1qTshffYrtNALIkDrFPLV0HOo1&amp;t=637866756480000000' and @id = 'ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl01' and @title = 'HTML text']</value>
      <webElementGuid>2c35963e-36d7-4e1b-a308-308b11aeed96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
