<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Modo Diseno</name>
   <tag></tag>
   <elementGuidId>c03dfad6-7770-4a4f-ab66-a6b1631b15a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl00</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>518e70fe-2f5d-45dd-a806-1bde40d2dea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/WebResource.axd?d=K6hBBt7cIA91H1qzdLBxg10QNh7DXghXL-t9a9srjCReFadxAKoJXRJmdVUvwHpvv_lG5pk30fBg3aIZBse7dEQkaAa1A8hbMpNi2yF6ETNy0zEhETgvyBQYw9xWUepep23mP_0DteY0DLylqmvn4VFcMTA1&amp;t=637866756480000000</value>
      <webElementGuid>467204f5-c08f-4a7b-be41-67be6fd57468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl00</value>
      <webElementGuid>ba7e7e4d-f144-407d-9d87-d5a18d10d8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Design mode</value>
      <webElementGuid>1ae05210-e1b5-44d3-9ceb-b9f10c87d974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_toolbar_button ajax__htmleditor_toolbar_button_active ajax__htmleditor_toolbar_button_hover</value>
      <webElementGuid>11c039b9-496e-4e8c-bdc1-da3a077a8ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl00&quot;)</value>
      <webElementGuid>508ec971-ca58-4625-8491-7e607f32caa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl00']</value>
      <webElementGuid>32d0ced3-9432-4c6c-869e-cdca2409b7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtPolitica_ctl03']/img</value>
      <webElementGuid>a80e4a4f-877f-450a-8867-08028a401176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Design mode']</value>
      <webElementGuid>70ba182a-c4c4-41a8-8428-ea3c1fdfae29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/img</value>
      <webElementGuid>c0f29fd1-eec8-45c3-8b5d-8aa0b8bcee31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/WebResource.axd?d=K6hBBt7cIA91H1qzdLBxg10QNh7DXghXL-t9a9srjCReFadxAKoJXRJmdVUvwHpvv_lG5pk30fBg3aIZBse7dEQkaAa1A8hbMpNi2yF6ETNy0zEhETgvyBQYw9xWUepep23mP_0DteY0DLylqmvn4VFcMTA1&amp;t=637866756480000000' and @id = 'ctl00_ContentPlaceHolder2_edtPolitica_ctl03_ctl00' and @title = 'Design mode']</value>
      <webElementGuid>5234d18e-e3c6-4dc9-b1a8-913088099bd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
