<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Modo HTML</name>
   <tag></tag>
   <elementGuidId>a1e9d0d2-1264-43c6-9eed-1ac7d09af840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_ContentPlaceHolder2_edtPolitica_ctl02_ctl01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_edtPolitica_ctl02_ctl01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a63364c5-38d0-4141-865d-e784d320704d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_edtPolitica_ctl02_ctl01</value>
      <webElementGuid>2271aafe-8b3d-4717-b154-b7d071cc658b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax__htmleditor_htmlpanel_default</value>
      <webElementGuid>0c9ac6ed-ef0e-4632-ba7e-ea43c9820abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_edtPolitica_ctl02_ctl01&quot;)</value>
      <webElementGuid>df6490a2-166c-4388-8f63-857dbda241f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_ContentPlaceHolder2_edtPolitica_ctl02_ctl01']</value>
      <webElementGuid>095c2edf-47b0-4f2d-9d1f-6e5288914068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_edtPolitica_ctl02']/textarea</value>
      <webElementGuid>7956984c-bd99-4baa-a74e-7f5dfdf09fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b2cf5d71-534f-4868-a9fe-18e307bc5ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ctl00_ContentPlaceHolder2_edtPolitica_ctl02_ctl01']</value>
      <webElementGuid>dbd17c1d-ece4-450f-b3fe-f6231b4f771b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
