<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>upload_ArchivoPDF</name>
   <tag></tag>
   <elementGuidId>0ddcac57-c3aa-43a6-b799-c345ff220f46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_fupPoliticaPDF']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_fupPoliticaPDF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6b21bb4-237d-44f6-b702-fbb9b39f505d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>e50d0070-c67d-4531-8052-46cdc6948724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$fupPoliticaPDF</value>
      <webElementGuid>cb9e95c6-6cb2-42e7-ad35-74d35252b126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_fupPoliticaPDF</value>
      <webElementGuid>1bcc19a1-605f-431f-a423-349158ca72d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_fupPoliticaPDF&quot;)</value>
      <webElementGuid>56b19e38-28a4-459a-a94d-9cb79547e2bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_fupPoliticaPDF']</value>
      <webElementGuid>28f13770-3af1-4957-8522-4aad3919dc3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_uplPoliticaPDF']/input</value>
      <webElementGuid>aa664bd7-5ce0-49a9-9ccc-989a47d91336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>88fe2228-abad-431f-80bf-d829809a4bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'ctl00$ContentPlaceHolder2$fupPoliticaPDF' and @id = 'ctl00_ContentPlaceHolder2_fupPoliticaPDF']</value>
      <webElementGuid>46db98b1-c651-489c-9865-ae4ea5f83924</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
