<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha creacion (ddmmaaaa)</name>
   <tag></tag>
   <elementGuidId>a5628720-6a59-4527-acda-3aea623f2831</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtFechaCreacionFiltrar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtFechaCreacionFiltrar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6eb1c618-b172-4e98-90a1-4ffc863ba634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvAfiliados$ctl01$txtFechaCreacionFiltrar</value>
      <webElementGuid>0506ad76-4f5f-41be-97a3-7d14f856c0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>993687a2-6d32-440c-aef8-d666870c7d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtFechaCreacionFiltrar</value>
      <webElementGuid>fd6d32b7-a491-49f9-bb02-0a79b22b489b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e1b6cee6-a035-4b8c-ba6d-0cabccdd3900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtFechaCreacionFiltrar&quot;)</value>
      <webElementGuid>dc74ebe9-878f-4cb7-a9f5-e101ac5e2959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtFechaCreacionFiltrar']</value>
      <webElementGuid>72aeebbd-a9d2-47dc-acd7-bb5fae7f1ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_tblFechaCreacion']/tbody/tr[2]/td/input</value>
      <webElementGuid>a0311248-5955-4dd8-88d9-0d4123702f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[13]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>b1e15edb-5ff8-4760-8035-2ec830dcb421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$gvAfiliados$ctl01$txtFechaCreacionFiltrar' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtFechaCreacionFiltrar']</value>
      <webElementGuid>79d8fb8d-7ace-44a4-9eef-d9c698c66e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
