<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Celular</name>
   <tag></tag>
   <elementGuidId>42a437eb-1016-4880-99a3-b780b45e9a42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtCelular']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtCelular</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb763974-abda-4fae-8465-ba78282ae8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvAfiliados$ctl01$txtCelular</value>
      <webElementGuid>94e4bb6c-806f-46fc-b6df-83456fbe6b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b936a219-adee-48f0-a9bc-0ca7f2d17a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtCelular</value>
      <webElementGuid>10209955-0a8c-4fdb-8764-03f5b5f3aff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d39ca1d6-d5ab-4199-a051-213697a92ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtCelular&quot;)</value>
      <webElementGuid>baaa6849-f409-4757-9102-a90d9e293c00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtCelular']</value>
      <webElementGuid>80f94944-190c-4fc2-b066-7fcd169a1adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAfiliados']/tbody/tr/th[9]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>37af689c-8d38-45b0-b65d-dd7e49ea311a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[9]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>c7762e42-07e4-4e65-8ff4-0dfa6f9d27d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$gvAfiliados$ctl01$txtCelular' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtCelular']</value>
      <webElementGuid>83590bfd-2f74-4edc-9100-a02a5a9acdea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
