<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre Usuario</name>
   <tag></tag>
   <elementGuidId>6860a7bd-9447-4c77-ae60-931d4f1a8c52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNombreUsuario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNombreUsuario</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebdf94e3-c114-409d-8eed-d1c9d0b5b06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvAfiliados$ctl01$txtNombreUsuario</value>
      <webElementGuid>61ae65be-0d4b-4f8b-a72e-f30a88fda490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f33c5454-cdef-4dbd-b21a-4b9a9927a2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNombreUsuario</value>
      <webElementGuid>aa0b8f42-b374-4a1b-b163-70aadd9c8154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4246ad5e-1c6e-4985-a604-f2196c8dec80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNombreUsuario&quot;)</value>
      <webElementGuid>94c5cbed-ccb6-4db3-a90f-a29dbce82618</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNombreUsuario']</value>
      <webElementGuid>0cf4c8e8-b925-47ce-84d6-255629c1c6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAfiliados']/tbody/tr/th[4]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>61e3d009-67ba-4963-a600-672802b6afd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>76ba433a-7820-4d34-8bac-b2b3dd330086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$gvAfiliados$ctl01$txtNombreUsuario' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNombreUsuario']</value>
      <webElementGuid>c3d6d58d-0209-4b0e-bf17-2e682be4c711</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
