<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telefono</name>
   <tag></tag>
   <elementGuidId>297a89bf-a428-4483-b1c1-b6035699546e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtTelefono']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtTelefono</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb1e8942-eca4-4af1-bb61-3137c27d30ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvAfiliados$ctl01$txtTelefono</value>
      <webElementGuid>35b51ebc-ac39-4a9b-9a61-889d0e88eab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>07e0c682-86d6-408c-a5ba-0b4f9f6b8fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtTelefono</value>
      <webElementGuid>feba606e-a04f-4df0-8ecc-14eaebe31161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>68deb1fc-30ff-4409-ace3-b84ef2148aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtTelefono&quot;)</value>
      <webElementGuid>8618d307-a0aa-41ea-aace-a2ab946f8ab2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtTelefono']</value>
      <webElementGuid>e13bb39d-7de9-4340-8158-c533d1f9d354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAfiliados']/tbody/tr/th[8]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>47cbea49-9988-43cd-a7b1-fb37f6187b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[8]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>056987d8-152f-43b8-b415-e3547ad6c870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$gvAfiliados$ctl01$txtTelefono' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtTelefono']</value>
      <webElementGuid>6cd04713-4daa-42e7-82bf-d0bc5eaef243</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
