<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Identificacion</name>
   <tag></tag>
   <elementGuidId>1482c16e-a55f-4611-8e49-695f289a90ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNumeroIdentificacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNumeroIdentificacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aeb8c53a-fc48-4d6a-a847-349f675483a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvAfiliados$ctl01$txtNumeroIdentificacion</value>
      <webElementGuid>5e7fb8da-1623-43a6-80aa-a8217bc44d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85f3834f-704f-4ebc-8f7f-ecdffd4cfa52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNumeroIdentificacion</value>
      <webElementGuid>b8120f8a-829a-4ed4-8508-d9df5c1b2940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d817fdf0-ec29-40d7-a3f0-e385005d33db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNumeroIdentificacion&quot;)</value>
      <webElementGuid>9c3268d2-6794-471d-80bf-840b3ef1a3c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNumeroIdentificacion']</value>
      <webElementGuid>ea3d71ac-89d4-426d-9af7-bdb450366abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAfiliados']/tbody/tr/th[7]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>1011e930-89f3-4a32-864e-e48dd98d6ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>716900b0-2458-47cb-859d-b335b1d71e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$gvAfiliados$ctl01$txtNumeroIdentificacion' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_txtNumeroIdentificacion']</value>
      <webElementGuid>fbb2b5fe-fa98-40cc-8941-b4d00f9199dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
