<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Activo</name>
   <tag></tag>
   <elementGuidId>cf668cb9-9d9e-44e1-9c6e-b34121624c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvAfiliados']/tbody/tr/th[12]/table/tbody/tr[2]/td/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2493b356-f536-408c-bfe0-a88a38b74975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_chkEsActivoFiltrar</value>
      <webElementGuid>c5d30205-1fac-4cd2-87d4-2b82704889a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAfiliados&quot;)/tbody[1]/tr[1]/th[12]/table[@class=&quot;tablaEncabezado&quot;]/tbody[1]/tr[2]/td[1]/span[1]/label[1]</value>
      <webElementGuid>5c5e4750-8edd-486a-a5c3-eb11ddbd2994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAfiliados']/tbody/tr/th[12]/table/tbody/tr[2]/td/span/label</value>
      <webElementGuid>a788ac30-69a1-4613-8a8e-cd63346e8f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[12]/table/tbody/tr[2]/td/span/label</value>
      <webElementGuid>03e16c22-b31f-4387-b61c-f7f7a840684c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
