<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Penalizado</name>
   <tag></tag>
   <elementGuidId>a1d578f9-b2ce-4ea1-8ad6-f1f00a402165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder2_gvAfiliados']/tbody/tr/th[10]/table/tbody/tr[2]/td/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9a4c919f-73c9-4615-930d-f27a8a321ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvAfiliados_ctl01_chkEsPenalizadoFiltrar</value>
      <webElementGuid>dadf2344-1e29-45ea-8114-9f1ad2d46dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvAfiliados&quot;)/tbody[1]/tr[1]/th[10]/table[@class=&quot;tablaEncabezado&quot;]/tbody[1]/tr[2]/td[1]/span[1]/label[1]</value>
      <webElementGuid>a4b94060-af16-4f51-b035-93d1e43fa1e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvAfiliados']/tbody/tr/th[10]/table/tbody/tr[2]/td/span/label</value>
      <webElementGuid>1e50fb5d-ed1a-42cd-939b-37eb3544866f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>d2223da8-8db5-4f3f-abea-04c96bae0781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
