<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Citas</name>
   <tag></tag>
   <elementGuidId>2cef502b-112d-4b80-ad43-afa2308fa290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='Utilidades.establecerEfectoHeader()'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d62d9900-6062-45ef-b108-b519f005c880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>idpagina</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>90475031-b436-4bbe-a2cb-7b6da412beea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Paginas/Citas/frmInicioCitas.aspx</value>
      <webElementGuid>b838fbf8-4b8e-40ff-a7b4-a784e9c8ff4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utilidades.establecerEfectoHeader()</value>
      <webElementGuid>0ba461e5-13a0-43f2-b853-5b7280b58bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemnumber</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8e0477a2-8f4f-4d1c-a6be-348c6e1cf368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        
                        Citas
                    </value>
      <webElementGuid>ad3a1dd6-71b2-4784-886b-062e4f09b8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_UpdatePanel1&quot;)/div[@class=&quot;divCentral container-fluid&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center&quot;]/div[@class=&quot;contenedorMenuIconos&quot;]/div[@class=&quot;menuIconos&quot;]/div[1]/a[3]</value>
      <webElementGuid>6feabe7d-8bae-4dff-a815-3e48376a2444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='Utilidades.establecerEfectoHeader()'])[3]</value>
      <webElementGuid>7d5dbf7b-0256-4119-a6ed-041dbdd0336f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_UpdatePanel1']/div/div/div/div[2]/div/a[3]</value>
      <webElementGuid>b48eba07-36bb-4921-98c0-f159849c806d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agendas'])[2]/following::a[1]</value>
      <webElementGuid>07f6048d-8d80-4681-b171-b0b71b53a022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuración'])[2]/following::a[2]</value>
      <webElementGuid>1b110ba6-fcca-49d4-8c40-f3c5195f72c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Paginas/Citas/frmInicioCitas.aspx')]</value>
      <webElementGuid>3f914d59-ccf7-4b0c-b43c-ce9e8aa3c4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>9bf87dc7-ba12-4d42-8486-ea038b37b382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Paginas/Citas/frmInicioCitas.aspx' and (text() = '
                        
                        Citas
                    ' or . = '
                        
                        Citas
                    ')]</value>
      <webElementGuid>4c0e9905-5bda-47e9-8d8d-c572155987a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
