<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Configuracion</name>
   <tag></tag>
   <elementGuidId>b13d4d50-ef77-408c-92d1-9b2715dd4a5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='Utilidades.establecerEfectoHeader()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.menuIconos > div > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5e7238ec-fcf2-4fe6-a256-d62d435a8a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>idpagina</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9b1c2e80-b695-4c58-8b34-33fc0dd43595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Paginas/Configuracion/frmInicioConfiguracion.aspx</value>
      <webElementGuid>55c1a32e-1e4c-4b28-92df-c009cf2a977d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utilidades.establecerEfectoHeader()</value>
      <webElementGuid>14907b11-5065-44d0-9e6b-5d5b1936f76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b5719e52-2a7a-46e8-a790-ef7acdce9412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        
                        Configuración
                    </value>
      <webElementGuid>eca4a903-4710-4fb9-b755-5efc90ec5590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_UpdatePanel1&quot;)/div[@class=&quot;divCentral container-fluid&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center&quot;]/div[@class=&quot;contenedorMenuIconos&quot;]/div[@class=&quot;menuIconos&quot;]/div[1]/a[1]</value>
      <webElementGuid>e055530e-b071-4a92-8f45-163bb1d9e39e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='Utilidades.establecerEfectoHeader()']</value>
      <webElementGuid>e74f580c-ecbb-4c97-be34-40a996ce3ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_UpdatePanel1']/div/div/div/div[2]/div/a</value>
      <webElementGuid>4f3acd5d-e7e0-45d9-bb0c-0b7b9b651d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bienvenido'])[1]/following::a[1]</value>
      <webElementGuid>c1256b01-ac18-4254-b153-db9341fef49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[2]/following::a[2]</value>
      <webElementGuid>d804f2ba-a268-4729-b455-f3902b0016b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agendas'])[2]/preceding::a[1]</value>
      <webElementGuid>acb93a01-c44c-44a2-b89d-9447c21248bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Paginas/Configuracion/frmInicioConfiguracion.aspx')]</value>
      <webElementGuid>a114cb5e-e827-4d5d-a75f-7310757f142d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div[2]/div/a</value>
      <webElementGuid>0a80b622-7644-4000-9bde-bb491f7ec511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Paginas/Configuracion/frmInicioConfiguracion.aspx' and (text() = '
                        
                        Configuración
                    ' or . = '
                        
                        Configuración
                    ')]</value>
      <webElementGuid>50a2a0d8-96c0-430c-84fb-140a055f0d61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
