<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_logoCiel</name>
   <tag></tag>
   <elementGuidId>e80a280c-15de-4ab2-9b38-4691a4f937d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='aspnetForm']/div[3]/div[2]/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logoCiel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e8e97f4f-3b89-4cd6-be47-7b23c71ca612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Imagenes/LogoCiel.svg</value>
      <webElementGuid>1832d0b3-c51e-414c-b516-aaf88b80bf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logoCiel</value>
      <webElementGuid>36fd9bab-e6c2-449d-b929-f9aece304bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Ciel ingeniería</value>
      <webElementGuid>58520f2a-79cd-4322-a582-27517e323e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aspnetForm&quot;)/div[@class=&quot;divEnvoltura&quot;]/div[@class=&quot;divHeader&quot;]/div[@class=&quot;divHeaderCabeza d-flex&quot;]/div[@class=&quot;d-flex align-items-center justify-content-between w-100&quot;]/div[@class=&quot;d-flex&quot;]/div[1]/a[1]/img[@class=&quot;logoCiel&quot;]</value>
      <webElementGuid>d8ddeba1-b7e9-4bdb-8565-3ebd6880949e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>301b0087-26d5-4670-8950-3f77744f40cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Ciel ingeniería']</value>
      <webElementGuid>4042e916-41c2-4af6-aace-4ce21ccbd8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>e63c8408-729d-48e2-8710-c543aec4fa0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Imagenes/LogoCiel.svg' and @alt = 'Ciel ingeniería']</value>
      <webElementGuid>2a48984b-ac2b-4b84-96e1-b00a3f9af458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
