<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_C</name>
   <tag></tag>
   <elementGuidId>45af0c4a-6cc2-43d4-acf5-8588f60c444a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ctl00_ContentPlaceHolder2_alkFuncionarios_blAbecedario']/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_alkFuncionarios_blAbecedario > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16cccd38-c7ae-4662-8791-ad29f903ab48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder2$alkFuncionarios$blAbecedario','0')</value>
      <webElementGuid>1931e071-8c26-4cc7-8e8f-773cf36899e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>d2ac12ef-5caf-44b4-a395-1e2fa04f0f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_alkFuncionarios_blAbecedario&quot;)/li[1]/a[1]</value>
      <webElementGuid>8cb46c23-885d-4d95-90a3-6827ba7ce50d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ctl00_ContentPlaceHolder2_alkFuncionarios_blAbecedario']/li/a</value>
      <webElementGuid>bc07b464-c359-4bb4-90c6-5b26cb330c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'C')])[16]</value>
      <webElementGuid>b2beef6e-d2a5-4d43-9f56-f5bde139af19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funcionarios'])[3]/following::a[1]</value>
      <webElementGuid>4c1762db-6a64-4375-be05-3f195fe288f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funcionarios'])[2]/following::a[2]</value>
      <webElementGuid>d468b6ea-5457-4b98-b1f6-fdf985f19f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre funcionario'])[1]/preceding::a[1]</value>
      <webElementGuid>960ce764-d78f-41f6-b0cb-d2545e3d71c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre a mostrar'])[1]/preceding::a[1]</value>
      <webElementGuid>1d9d5d11-8ba9-44af-b11b-ebdb42e86f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='C']/parent::*</value>
      <webElementGuid>9ebfcbd1-7e3f-4a1e-a7e2-37c29616f2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder2$alkFuncionarios$blAbecedario','0')&quot;)]</value>
      <webElementGuid>dfeec51c-dcfb-4436-93f4-b492c977c68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/ul/li/a</value>
      <webElementGuid>641df0ff-826a-44f6-aee7-ac1a1d78f566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder2$alkFuncionarios$blAbecedario&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'C' or . = 'C')]</value>
      <webElementGuid>3b251f28-93d0-49d9-842b-a6ec3f032f9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
