<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_P</name>
   <tag></tag>
   <elementGuidId>de4fc133-77b3-4f9d-b6b0-e566e4d3b038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ctl00_ContentPlaceHolder2_alkFuncionarios_blAbecedario']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_alkFuncionarios_blAbecedario > li:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed10bf5f-db96-489d-9e14-08e979e7b100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder2$alkFuncionarios$blAbecedario','1')</value>
      <webElementGuid>06fcc553-06e0-4234-8391-41808ae4e33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>54ddd0f3-3aa5-4c22-8750-81a92b061b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_alkFuncionarios_blAbecedario&quot;)/li[2]/a[1]</value>
      <webElementGuid>2c2295d8-873b-4b81-814b-6aa23d07d904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ctl00_ContentPlaceHolder2_alkFuncionarios_blAbecedario']/li[2]/a</value>
      <webElementGuid>f4e7a4df-d719-480c-8a91-5607f9446a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'P')])[6]</value>
      <webElementGuid>9e9c463b-34d1-4ffd-b68f-5386f6a5c1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/following::a[1]</value>
      <webElementGuid>12d9b13e-0055-49b8-a702-2e190c9b9fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funcionarios'])[3]/following::a[2]</value>
      <webElementGuid>6ee6bd50-3982-4c61-b442-046085ff4f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre funcionario'])[1]/preceding::a[1]</value>
      <webElementGuid>25152d41-05eb-4a47-85f8-eba0ebc55abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre a mostrar'])[1]/preceding::a[1]</value>
      <webElementGuid>50a07171-10d6-4088-afac-2c8cf62620af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='P']/parent::*</value>
      <webElementGuid>dcfe6fb0-d1d2-411c-a5c3-aeeffd3a26d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder2$alkFuncionarios$blAbecedario','1')&quot;)]</value>
      <webElementGuid>05097043-34ea-4e10-af15-8d3184223da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>5850437c-e763-40cf-9388-cd9b2bbaea4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder2$alkFuncionarios$blAbecedario&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'P' or . = 'P')]</value>
      <webElementGuid>8fc554ec-766b-4f18-adcd-9d8fd0a39565</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
