<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Requisitos</name>
   <tag></tag>
   <elementGuidId>fd5f1f78-49c1-4e84-81d3-8e776f9a35b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Requisitos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Requisitos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cfc6e0b-ccdc-44bc-8e86-0a817aa56da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl02$ctl02$FilterTextBox_Requisitos</value>
      <webElementGuid>8426695b-2726-4843-a5ef-01bd1fc58ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d14164f4-ec78-4d85-a0e3-277ac7233bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1e555053-6788-4f9d-a3f6-358b84872e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Requisitos</value>
      <webElementGuid>728e677d-9445-401e-aaf2-403c3c7e0c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rgFilterBox</value>
      <webElementGuid>19d266ad-59c7-4d96-ab1b-5dcf2ef8b7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Filter Requisitos column</value>
      <webElementGuid>507d8324-71d5-4d75-92a8-1b0d828b1365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if((event.keyCode == 13)) return false;</value>
      <webElementGuid>732c66c8-a2dd-409c-be13-b8506c1defbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>96f33b57-6e2e-437e-b0a5-954e3d706ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Requisitos&quot;)</value>
      <webElementGuid>a5c396b4-e740-4f3c-a507-e248a483a8f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Requisitos']</value>
      <webElementGuid>3291e409-30ed-47fb-a348-135390bcbfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_RadGrid1_ctl00']/thead/tr[2]/td[3]/input</value>
      <webElementGuid>ea9b811b-e8d1-48b7-bd3a-44494ff490c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>0994fb82-c662-48e1-a680-639ca8f9279e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$RadGrid1$ctl00$ctl02$ctl02$FilterTextBox_Requisitos' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_RadGrid1_ctl00_ctl02_ctl02_FilterTextBox_Requisitos' and @alt = 'Filter Requisitos column']</value>
      <webElementGuid>79a87d01-9718-447a-8777-275b94d5375b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
