<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_4 Fechas Unicas por especialidad (Modo Ag. por Especialidades)</name>
   <tag></tag>
   <elementGuidId>f4619ea7-cfc7-46e5-a8fa-5635bdbd1dd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='Utilidades.establecerEfectoHeader()'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3d283aae-34ad-4103-b167-ee837c96af59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>idpagina</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>15b81df7-6ff6-40c0-9258-4dd017a61815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Paginas/Configuracion/ModeloAtencion/frmEspecialidadesPorFechas.aspx</value>
      <webElementGuid>c87a0647-55bc-4229-aeff-764b5461eb68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utilidades.establecerEfectoHeader()</value>
      <webElementGuid>93dacee6-21bd-4c2c-a737-856f46d70216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemnumber</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>17147e18-ea88-4494-9186-757d68468dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        
                        Fechas únicas por especialidad
                    </value>
      <webElementGuid>c52ab369-ef3d-48f2-9536-57aefe5e3119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_UpdatePanel1&quot;)/div[@class=&quot;divCentral container-fluid&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center&quot;]/div[@class=&quot;contenedorMenuIconos&quot;]/div[@class=&quot;menuIconos&quot;]/div[1]/a[4]</value>
      <webElementGuid>1af1f6a8-abfd-4a6e-8180-07571a028d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>365c12da-f16d-4950-8ecf-b2edce245b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>idpagina</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>5be10537-ac21-48ba-8a8f-60b972c6c858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Paginas/Configuracion/ModeloAtencion/frmEspecialidadesPorFechas.aspx</value>
      <webElementGuid>383d49d5-4e4b-4262-9a28-f08c42ae6338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utilidades.establecerEfectoHeader()</value>
      <webElementGuid>fd1456e8-32f6-402f-a27f-686e81ba717c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemnumber</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>97079de1-6c77-4de8-b967-3ecee26a5dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        
                        Fechas únicas por especialidad
                    </value>
      <webElementGuid>6a65f0a7-be9e-43ef-9fc9-3e98344ef3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_UpdatePanel1&quot;)/div[@class=&quot;divCentral container-fluid&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center&quot;]/div[@class=&quot;contenedorMenuIconos&quot;]/div[@class=&quot;menuIconos&quot;]/div[1]/a[4]</value>
      <webElementGuid>50a9d62b-b91e-465b-a380-725e7ae96f68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='Utilidades.establecerEfectoHeader()'])[4]</value>
      <webElementGuid>63098528-55eb-4047-99ee-8122702853c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_UpdatePanel1']/div/div/div/div[2]/div/a[4]</value>
      <webElementGuid>e874b125-be21-4a49-8f33-f26c2f0368c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupos'])[2]/following::a[1]</value>
      <webElementGuid>335d957b-723c-451b-abc0-25317c7346ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicios por oficinas'])[2]/following::a[2]</value>
      <webElementGuid>afab67db-4d5d-4d00-b021-c9bf3e5edb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Paginas/Configuracion/ModeloAtencion/frmEspecialidadesPorFechas.aspx')]</value>
      <webElementGuid>569bc83e-7fcc-46dd-aebb-ebf23741075b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>dc9f951f-a4d2-4895-899f-8a8f3dab92cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Paginas/Configuracion/ModeloAtencion/frmEspecialidadesPorFechas.aspx' and (text() = '
                        
                        Fechas únicas por especialidad
                    ' or . = '
                        
                        Fechas únicas por especialidad
                    ')]</value>
      <webElementGuid>b54d11e6-c6e5-415d-b967-fee8735e7d63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
