<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Hora Fin MM UP</name>
   <tag></tag>
   <elementGuidId>9a6a5cb6-ef67-42d0-acf0-393d59dd4f81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraFinJornada_txtMinuto_bUp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_tspHoraFinJornada_txtMinuto_bUp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37bd7ef1-1797-48ef-9376-d011cf2ad513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97280fd1-401d-4f16-bbe8-bfe8ecb2de1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_tspHoraFinJornada_txtMinuto_bUp</value>
      <webElementGuid>76ffe78d-8f28-4afa-b242-45c51adef666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▲</value>
      <webElementGuid>b0744bd4-2eb3-4337-bbdd-9f963d70c228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_tspHoraFinJornada_txtMinuto_bUp&quot;)</value>
      <webElementGuid>e3aa14a0-0231-4d78-9651-4befdd6ba2ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_tspHoraFinJornada_txtMinuto_bUp']</value>
      <webElementGuid>ddd4ff74-9fd4-44fe-aa2a-306538ccda54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_UpdatePanel1']/div/div/div/div/div[2]/table/tbody/tr[10]/td[2]/div/div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>ea2ae146-2d79-4ac6-82dd-72a19a289d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/div/div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>080049a9-ec14-45e6-b88e-cae0b332729b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ctl00_ContentPlaceHolder2_tspHoraFinJornada_txtMinuto_bUp']</value>
      <webElementGuid>385b8d8e-a5e4-4969-88f6-523e0c8aaa37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
