<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_8 Prueba_Borrar</name>
   <tag></tag>
   <elementGuidId>ddbb399b-5fd0-46d4-9dfe-585f40bf66de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvOficinas_ctl09_btnBorrar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvOficinas_ctl09_btnBorrar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32b77d03-7056-4b30-af29-6617977c60c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('¿Desea eliminar la oficina?');</value>
      <webElementGuid>b3cb66b9-ec37-42c7-91d7-191ea71537d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvOficinas_ctl09_btnBorrar</value>
      <webElementGuid>7e94a943-1ab4-4fc4-b4d8-338e15d4f91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Eliminar oficina</value>
      <webElementGuid>8d70b599-2a9c-4037-bc5b-dbe02343adf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnBorrarImg</value>
      <webElementGuid>cb903d41-d21b-43ab-8c77-4561a8aea1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvOficinas$ctl09$btnBorrar','')</value>
      <webElementGuid>db866c98-e52c-40e3-a049-4fa2e044886e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvOficinas_ctl09_btnBorrar&quot;)</value>
      <webElementGuid>3a808952-528b-40f6-8f35-c5fd4d6fcc9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvOficinas_ctl09_btnBorrar']</value>
      <webElementGuid>cf7d018e-3d2d-4bd8-b6a4-0523cfe40491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvOficinas']/tbody/tr[9]/td[7]/div/a[2]</value>
      <webElementGuid>98667caa-abe0-4d00-b930-04f95448d144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvOficinas$ctl09$btnBorrar','')&quot;)]</value>
      <webElementGuid>db300127-8a39-439d-a854-3e401de259b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[7]/div/a[2]</value>
      <webElementGuid>83edc1a8-7883-42ab-a7a1-ffb052abe693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvOficinas_ctl09_btnBorrar' and @title = 'Eliminar oficina' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder2$gvOficinas$ctl09$btnBorrar&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;)]</value>
      <webElementGuid>27b6bdd1-c139-4789-8098-83f89d2ed0e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
