<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Habilitado</name>
   <tag></tag>
   <elementGuidId>17964a36-04dc-419e-91a1-d49af5abe03f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divCampoAdicionalEdit']/div/div[2]/div/div/table/tbody/tr[10]/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>00a941a6-b633-42b5-8cea-0e339742ecfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_chkHabilitado</value>
      <webElementGuid>b4653298-0ce7-486f-a640-d374d8a3a6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divCampoAdicionalEdit&quot;)/div[@class=&quot;caja&quot;]/div[@class=&quot;cajaContenido&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-6 mb-3&quot;]/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[10]/td[2]/span[@class=&quot;chkAspGeneric&quot;]/label[1]</value>
      <webElementGuid>34f4a42c-5e17-41dd-a462-3dddf4d4608a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCampoAdicionalEdit']/div/div[2]/div/div/table/tbody/tr[10]/td[2]/span/label</value>
      <webElementGuid>75758ec4-fa16-4439-99a0-d105d6e81cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/span/label</value>
      <webElementGuid>814ecd97-a653-44a7-8ccf-e7c5dc57fcdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
